### PR TITLE
Stronger check and override of comments in UglifyJsPlugin options

### PR DESCRIPTION
**Pull request by Dashed**
Fixes https://github.com/webpack/webpack/issues/324

### CODE REVIEW

**Comment by sokra** [comment]
Could you add a test for this?

**Comment by Dashed** [comment]
Sure. Do I add it in `/test/configCases/plugins`?

**Comment by sokra** [comment]
yep

**Comment by Dashed** [comment]
@sokra Added test and rebased.

**Comment by sokra** [comment]
Thanks, great PR

**Pull request merged**
