### PR TITLE
fix: Returning thrown error to prevent unhandled promise

### LINKED ISSUE #12426: Webpack 5 loadModule throws unhandled error if a loader returns error
# Bug Report

**What is the current behavior?**
When calling loadModule in the context of a custom loader, if any loader for that given module type returns an error, Webpack crashes without reporting what the original error is. The resulting error and stack trace is as following:

```
Error: The module created for a LoaderDependency must have an original source
    at compilation.handleModuleCreation.err (/sandbox/node_modules/webpack/lib/dependencies/LoaderPlugin.js:79:16)
    at buildModule.err (/sandbox/node_modules/webpack/lib/Compilation.js:1556:8)
    at hooks.result.callAsync.hookError (/sandbox/node_modules/webpack/lib/util/AsyncQueue.js:281:5)
    at Hook.eval [as callAsync] (eval at create (/sandbox/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/sandbox/node_modules/tapable/lib/Hook.js:18:14)
    at AsyncQueue._handleResult (/sandbox/node_modules/webpack/lib/util/AsyncQueue.js:254:21)
    at _processor (/sandbox/node_modules/webpack/lib/util/AsyncQueue.js:237:11)
    at _modulesCache.store.err (/sandbox/node_modules/webpack/lib/Compilation.js:1263:15)
    at /sandbox/node_modules/webpack/lib/HookWebpackError.js:69:3
    at Hook.eval [as callAsync] (eval at create (/sandbox/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/sandbox/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.store (/sandbox/node_modules/webpack/lib/Cache.js:107:20)
    at CacheFacade.store (/sandbox/node_modules/webpack/lib/CacheFacade.js:282:15)
    at module.build.err (/sandbox/node_modules/webpack/lib/Compilation.js:1254:26)
    at doBuild.err (/sandbox/node_modules/webpack/lib/NormalModule.js:795:12)
    at processResult (/sandbox/node_modules/webpack/lib/NormalModule.js:604:12)
    at runLoaders (/sandbox/node_modules/webpack/lib/NormalModule.js:691:5)
    at /sandbox/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /sandbox/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/sandbox/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.module.exports (/sandbox/loader2.js:3:3)
    at LOADER_EXECUTION (/sandbox/node_modules/loader-runner/lib/LoaderRunner.js:132:14)
    at runSyncOrAsync (/sandbox/node_modules/loader-runner/lib/LoaderRunner.js:133:4)
    at iterateNormalLoaders (/sandbox/node_modules/loader-runner/lib/LoaderRunner.js:250:2)
    at Array.<anonymous> (/sandbox/node_modules/loader-runner/lib/LoaderRunner.js:223:4)
    at runCallbacks (/sandbox/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)
    at _provider.call (/sandbox/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:200:4)
    at /sandbox/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Reproduction steps:**
The reproduction requires two different file types to be included on the webpack configuration:
1. A file type configured with a loader that will return an error (through emitError or calling `callback(error)`).
2. A second file type configured with a loader that will call `this.loadModule`, passing as argument the path to a file matching the first file type.
Minimal reproduction steps available on the following code sandbox: https://codesandbox.io/s/wpk-loadmodule-err-j7uom?file=/loader.js

A real-life scenario example would be the following:

index.js -> 
`@import "index.html";`

index.html ->
```
<html><head>
    <link href="index.css" type="text/css" rel="stylesheet">
</head><body></body></html>
```
index.css ->
`Anything that causes a syntax error.`

Loaders for HTML files: ["file-loader", "extract-loader", 'html-loader"]
Loaders for CSS files: ["file-loader', "extract-loader", "css-loader"]

**What is the expected behavior?**
Webpack should not crash, and instead correctly report the error thrown by the loader.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Reproduced on webpack 5.4, 5.11 and 5.14. I can confirm that this issue does not reproduce on webpack 4.

From a brief analysis of the thrown error, I've noticed that the done callback from `handleModuleCreation` on the file `LoaderPlugin.js` expects the module to have an `originalSource` set. However, on `NormalModule.js` when `doBuild` has an error, it is simply marking the module as failed and returning, and at that point `this._source` has never been set.

As I don't know the full context of why the error is not immediately returned from `doBuild`'s callback, my suggestion would be to either:
1. Initialize a module's _source using the module's raw content.
2. On `LoaderPlugin` besides checking `err`, also check the module.errors before proceeding.
3. Return the error on `doBuild`'s callback.

I am willing to contribute with the fix as this is something that will impact my team's development with webpack.

### PR DESCRIPTION
**Pull request by fcaminada**
This PR addresses #12426 by aborting the LoaderPlugin loadModule execution when the loaded module contains errors, and also ensuring that the thrown error is correctly handled by webpack's stack (by calling `callback` with the error instead of directly throwing).
Without this, the error is not correctly handled and node throws "Unhandled promise", making the process dangle on specific node versions. Another side-effect of this is that the original error message caused by the loader is never shown, making it a really hard problem to debug.

**What kind of change does this PR introduce?**

fixes #12426. Handling loaded module errors on LoaderPlugin.js and correctly handling errors case the loaded module has no sources (I couldn't find a practical case where this case happens other than the module containing errors, but I changed this handling anyways to prevent the process dangling).

**Did you add tests for your changes?**
Yes, added a test for checking that loadModule correctly handles the loaded module's error and aborts gracefully. This test also confirms that the causing error is correctly reported on webpack stats.

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
No extra documentation needed, this just improves upon error handling for loaders that use "loadModule".

### CODE REVIEW

**Comment by alexander-akait** [comment]
@fcaminada Can you rebase (maybe it fix the CI error)

**Review by sokra — APPROVED** [review]

**Comment by alexander-akait** [comment]
@fcaminada Can you accept CLA?

**Comment by fcaminada** [comment]
Done. My apologies, I did not notice that check

Em qua, 10 de fev de 2021 02:44, Alexander Akait <notifications@github.com>
escreveu:

**Comment by alexander-akait** [comment]
@fcaminada You need to rewrite email in your PRs, as you can see they are not assign to your github user, thanks

**Comment by fcaminada** [comment]
> @fcaminada You need to rewrite email in your PRs, as you can see they are not assign to your github user, thanks

What do you mean? The email I used is the same one assigned to my GitHub account

**Comment by alexander-akait** [comment]
@fcaminada Look at your commits in this PR, they don't have your avatar, because email used in commits is not the same as you use in github

**Comment by sokra** [comment]
Thanks

**Pull request merged**
