### PR TITLE
fix: default cache for multi compiler mode

### PR DESCRIPTION
**Pull request by alexander-akait**
**What kind of change does this PR introduce?**

bug fix

**Did you add tests for your changes?**

No, maybe you can provide there I should put it, `TestCasesCachePack.test` doesn't support multi compiler tests

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

I think no

### CODE REVIEW

**Review by sokra — CHANGES_REQUESTED** [review]
Automatically adjusting duplicate cache names might cause problems when running a build on a partial config, e. g. with `--config-name`, or with `parallel-webpack`.

I thinks it's better to force the user to use unique `name`s for the configs. E. g. with a warning if there are duplicate config names, and an error when the same cache location is used multiple times.

**Comment by vankop** [comment]
should we close this?

**Comment by alexander-akait** [comment]
@vankop I think we should output warnings/errors in this case, you can finish work :+1:

**Comment by vankop** [comment]
@sokra right now 2+ caches will try to write in same "default" cache?

**Comment by alexander-akait** [comment]
Yes

**Comment by vankop** [comment]
open for discussion #14843

**Pull request closed without merging**
