### PR TITLE
refactor(ES6): upgrade Compilation to ES6

### PR DESCRIPTION
**Pull request by ahmedelgabri**
**What kind of change does this PR introduce?**

ES5 => ES6 refactor

**Did you add tests for your changes?**

all tests are passing

**Summary**

Refactoring to ES2015/6

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by TheLarkInn** [comment]
Impressive work. Well done.

**Comment by TheLarkInn** [comment]
Thank you so much. This class was not an easy refactor. 🙇 👏 🍾

**Comment by ahmedelgabri** [comment]
> Thank you so much. This class was not an easy refactor. 🙇 👏 🍾

It's just too long 😄

**Comment by ahomatthew** [comment]
@ahmedelgabri I think you unintentionally introduced a bug where if you are missing a file that is imported `_this` is prematurely being set to null before the error callback happens.

Here -> https://github.com/webpack/webpack/blob/master/lib/Compilation.js#L222 _this is set to null by the time it fires, and therefore triggers quiet the red herring.

**Comment by ahmedelgabri** [comment]
@ahomatthew I'm not sure if it was me or is it related to something else because when I look at the file before my changes It's exactly the same after I converted it:

`_this = null ` https://github.com/webpack/webpack/blob/7dae8fbc0025935b068e222a41efc7f624765043/lib/Compilation.js#L330

`_this.errors.push(err);` https://github.com/webpack/webpack/blob/7dae8fbc0025935b068e222a41efc7f624765043/lib/Compilation.js#L198

**Comment by ahomatthew** [comment]
Ah got it, I'll file a bug.

**Pull request merged**
