### PR TITLE
Mark Base64 as global in mocha

### PR DESCRIPTION
**Pull request by ooflorent**
**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

no

**If relevant, link to documentation update:**

n/a

**Summary**

Without this, some tests ran with `--check-leaks` fail and hide other failures. This global binding is provided by `js-base64`.

**Does this PR introduce a breaking change?**

no

### CODE REVIEW

**Comment by ooflorent** [comment]
The leak come from js-base64 which is a dependency of postcss. Fixing it should be done prettier deep in the dependency chain. I think webpack has to live with it for some time. Hence the globals parameter.

**Comment by sokra** [comment]
Ok. Could you still check if it's possible to move these options into mocha.opt? This way we at least don't introduce additional leaks.

**Comment by ooflorent** [comment]
@sokra I've made the changes.

**Comment by sokra** [comment]
Thanks

**Pull request merged**
