### PR TITLE
Fix/webpack 4 high vulnerability min upgrade

### PR DESCRIPTION
**Pull request by martinoppitz**
**What kind of change does this PR introduce?**

vulnerability with high severity

**Did you add tests for your changes?**

no

**Does this PR introduce a breaking change?**

maybe (i think not ... tiny)

**What needs to be documented once your changes are merged?**

nothing

### CODE REVIEW

**Comment by evilebottnawi** [comment]
It is a breaking change also

**Comment by evilebottnawi** [comment]
Just update to `1.4.4` https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v1.4.4

**Comment by andrew-itscript** [comment]
Is there any news on it? Can anyone to update `terser-webpack-plugin` to `1.4.4`

**Comment by evilebottnawi** [comment]
@andrew-itscript you can regenerate lock file locally

**Pull request closed without merging**
