### PR TITLE
Break on circular reference in Stats

### LINKED ISSUE #6501: Infinite loop in Stats.js
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
```
unhandledRejection Invalid string length RangeError: Invalid string length
    at formatError (C:\Users\yuric.PARIPASSU\Git Repo\dashboard-frontend-html\node_modules\webpack\lib\Stats.js:223:30)
    at Array.map (<anonymous>)
    at Stats.toJson (C:\Users\yuric.PARIPASSU\Git Repo\dashboard-frontend-html\node_modules\webpack\lib\Stats.js:231:56)
    at Compiler.<anonymous> (C:\Users\yuric.PARIPASSU\Git Repo\dashboard-frontend-html\node_modules\html-webpack-plugin\index.js:68:44)
    at next (C:\Users\yuric.PARIPASSU\Git Repo\dashboard-frontend-html\node_modules\tapable\lib\Tapable.js:204:14)
    at Compiler.<anonymous> (C:\Users\yuric.PARIPASSU\Git Repo\dashboard-frontend-html\node_modules\fork-ts-checker-webpack-plugin\lib\index.js:173:17)
    at Compiler.applyPluginsAsyncSeries (C:\Users\yuric.PARIPASSU\Git Repo\dashboard-frontend-html\node_modules\tapable\lib\Tapable.js:206:13)
    at Compiler.emitAssets (C:\Users\yuric.PARIPASSU\Git Repo\dashboard-frontend-html\node_modules\webpack\lib\Compiler.js:354:8)
    at onCompiled (C:\Users\yuric.PARIPASSU\Git Repo\dashboard-frontend-html\node_modules\webpack\lib\Compiler.js:58:19)
    at applyPluginsAsync.err (C:\Users\yuric.PARIPASSU\Git Repo\dashboard-frontend-html\node_modules\webpack\lib\Compiler.js:510:14)
    at next (C:\Users\yuric.PARIPASSU\Git Repo\dashboard-frontend-html\node_modules\tapable\lib\Tapable.js:202:11)
    at Compiler.<anonymous> (C:\Users\yuric.PARIPASSU\Git Repo\dashboard-frontend-html\node_modules\webpack\lib\CachePlugin.js:78:5)
    at next (C:\Users\yuric.PARIPASSU\Git Repo\dashboard-frontend-html\node_modules\tapable\lib\Tapable.js:204:14)
    at C:\Users\yuric.PARIPASSU\Git Repo\dashboard-frontend-html\node_modules\hard-source-webpack-plugin\index.js:2018:7
    at <anonymous>
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Basically what I have is a index file, requiring a file, and this file ends up requiring the index file. 
When generating the error text, the `while(current.issuer)` loop in Stats.js never ends, resulting in the `Invalid string length` error.

Sample of text variable before the error:
```
[4mC:\Users\yuric.PARIPASSU\Git Repo\dashboard-frontend-html\app\api\DataSourceFieldGroupViewDTO.ts[24m
  [2m1:18[22m  [33mwarning[39m  'DataSourceFieldGroupViewDTO' is not defined  [2mno-undef[22m
  [2m2:5[22m   [33mwarning[39m  'idFieldGroup' is not defined                 [2mno-undef[22m

[33m[1m✖ 2 problems (0 errors, 2 warnings)[22m[39m
[33m[1m[22m[39m
 @ ./app/api/index.ts
 @ ./app/core/data-source/service/DataSourceMetadataService.ts
 @ ./app/core/data-source/service/index.ts
 @ ./app/core/data-source/index.ts
 @ ./app/core/data-source/dao/local/FormattedDataSourceDaoLocal.ts
 @ ./app/core/data-source/dao/index.ts
 @ ./app/core/data-source/service/DataSourceWriteService.ts
 @ ./app/core/data-source/service/index.ts
 @ ./app/core/data-source/index.ts
 @ ./app/core/data-source/dao/local/FormattedDataSourceDaoLocal.ts
 @ ./app/core/data-source/dao/index.ts
 @ ./app/core/data-source/service/DataSourceWriteService.ts
 @ ./app/core/data-source/service/index.ts
 @ ./app/core/data-source/index.ts
 @ ./app/core/data-source/dao/local/FormattedDataSourceDaoLocal.ts
 @ ./app/core/data-source/dao/index.ts
 @ ./app/core/data-source/service/DataSourceWriteService.ts
```

**What is the expected behavior?**
the loop should stop when a repeated issuer is detected.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
webpack 3.11.0

### PR DESCRIPTION
**Pull request by ooflorent**
**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

no

**If relevant, link to documentation update:**

n/a

**Summary**

Fixes #6501 

**Does this PR introduce a breaking change?**

no

**Other information**

I couldn't reproduce the issue.

### CODE REVIEW

**Comment by ooflorent** [comment]
@sokra Sure. I tried but failed to reproduce what is described in #6501. I'll try harder 💪

**Comment by ooflorent** [comment]
@ypconstante could you help setup a reproduction for this? I've tried many things but it fails.

**Comment by DerJacques** [comment]
Hey @ooflorent. We are experiencing this exact issue, but only when running webpack with the [hard source webpack plugin](https://github.com/mzgoddard/hard-source-webpack-plugin/). I have been unable to create a setup that reproduces the issue reliably, but for us, hard-source seems to be the culprit.

**Comment by sokra** [comment]
Closing because no test case can be constructed. Technically because of the invariant of the Module class this can't even happen. I assume there is an error in some 3rd party lib causing this.

**Pull request closed without merging**
