### PR TITLE
bugfixed: Webpack 5 is compiling twice in watch mode sometimes

### PR DESCRIPTION
**Pull request by qieqie7**
**What kind of change does this PR introduce?**
a bugfix. Webpack 5 is compiling twice in watch mode sometimes. I think aggregateTimeout should be increased. 
https://github.com/webpack/webpack/issues/12140
https://github.com/jantimon/html-webpack-plugin/issues/1576

image

**Did you add tests for your changes?**
yes. In my own project.

**Does this PR introduce a breaking change?**
No.

**What needs to be documented once your changes are merged?**
No.

### CODE REVIEW

**Comment by alexander-akait** [comment]
This is not valid fix

**Comment by qieqie7** [comment]
The bug cannot be reproduced in debugger mode. I saw that the default value was 200ms before. Why was it changed to 20ms? I think it is possible to increase on the previous value. This can ensure the efficiency of execution while avoiding some problems that may be caused by the system

**Comment by qieqie7** [comment]
image
image

**Comment by qieqie7** [comment]
@alexander-akait .It looks like the problem is because of chokidar. I use chokidar to listen for file changes. It triggers two updates. I found this issue https://github.com/paulmillr/chokidar/issues/610. His maintainer suggested using the debounce function to solve this problem. Thanks for reading.

**Comment by alexander-akait** [comment]
Do you have problems with static files only?

**Comment by qieqie7** [comment]
which static files? I don't understand.

**Comment by alexander-akait** [comment]
When you have double compilation? When you touch which files?

**Comment by fireairforce** [comment]
> maybe you can try https://github.com/qieqie7/double-complication .
> 
> There may be two compilations when I edit this project's `src/index.js`
> 
> macos 12.3.1 node 14.19.1 pnpm 7.0.0 (npm 8.7.0) vscode 1.67.0

this demo was too small, i use a react-app demo, when i set `aggregateTimeout: 600`, it will still build twice, i think change this might not be a valid way, it may cause other problems

**Comment by qieqie7** [comment]
> > maybe you can try https://github.com/qieqie7/double-complication .
> > There may be two compilations when I edit this project's `src/index.js`
> > macos 12.3.1 node 14.19.1 pnpm 7.0.0 (npm 8.7.0) vscode 1.67.0
> 
> this demo was too small, i use a react-app demo, when i set `aggregateTimeout: 600`, it will still build twice, i think change this might not be a valid way, it may cause other problems

It looks like the problem is because of chokidar. Chokidar uses fsevents to monitor file changes in mac. Maybe you can help take a look at this module.

**Comment by nikolaik** [comment]
I found it was because of eslint running every time I save a file in my editor, which I suspect result in an initial save and then, after 20+ ms, eslint finishes and the last save happens.

**Comment by qieqie7** [comment]
> I found it was because of eslint running every time I save a file in my editor, which I suspect result in an initial save and then, after 20+ ms, eslint finishes and the last save happens.

image

@nikolaik  I used the text editor that comes with the system. But the problem still occurs.

**Comment by nikolaik** [comment]
@qieqie7 You might be hit by this #15431

**Comment by alexander-akait** [comment]
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!

**Pull request closed without merging**
