### PR TITLE
refactor(es6): Upgrade Parser Plugins which depend on AbstractPlugin to es6

### LINKED ISSUE #3674: Refactor Abstract Plugin `this._plugins` object to `Map`.
Per notes from @Kovensky. We could refactor [`this._plugins`](https://github.com/webpack/webpack/pull/3669/files#diff-98d86f85810fbbe76e0d3d0ec2843a5eR17) to use `Map` instead of an object. However, this plugin is used in a bunch of places and would be a larger refactoring job. Will link this to existing PR where noted but this is an open opportunity for anyone to submit a PR for. 

 https://github.com/webpack/webpack/pull/3669#discussion_r94292340

### PR DESCRIPTION
**Pull request by chicoxyzzy**
**What kind of change does this PR introduce?**

Refactor

**Did you add tests for your changes?**

Existing Tests are passing

**If relevant, link to documentation update:**

N/A

**Summary**

update Parser Plugins which depend on AbstractPlugin to ES6 and remove AbstractPlugin

fixes #3674

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
Done 🎉

**Comment by chicoxyzzy** [comment]
First 5 commits are separate files refactoring. Last one is removing of AbstractPlugin.

**Comment by TheLarkInn** [comment]
Killer work. This is great. Thank you so much!!!

**Comment by sokra** [comment]
👍

**Pull request merged**
