### PR TITLE
Initial script for export all entities

### PR DESCRIPTION
**Pull request by barak007**
**What kind of change does this PR introduce?**

This PR introduce a simple script that can auto generate index files that exposes internal webpack entities.
The idea is that the index files are committed and when necessary can be generated again.
If auto generation is not welcome I can just use it once to generate initial indexes and manually remove/add exports.
Once the idea is approved I think that it will be preferred to organize the top level lib files more carefully inside folders for easier generation. and maybe also generate the main webpack index file that way.

I also exported `AsyncDependenciesBlock` manually in the main index

> I only generated few folders to show the idea.

**Did you add tests for your changes?**

No. In this stage I only want to know if the idea is acceptable and if so what and how exactly we want to test.

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

* All exported entities? - this is a huge effort that should be contributed as time passes.

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Some of them plugins and tools are internal and should not be exported, for example `processExportInfo`, otherwise we can change many things because it will be breaking change

**Comment by barak007** [comment]
how to determine what should be public?

**Comment by alexander-akait** [comment]
Let's solve it in another PR, here just solve original issue

**Comment by barak007** [comment]
Ok I open a PR that resolve only the issue that originally raised  #12987

**Comment by sokra** [comment]
Actually my idea with these manual exports was that we export as least as possible as everything exported becomes part of the public api and we can't easily change it anymore because it may cause breaking changes.

**Comment by barak007** [comment]
I have a lot to say here but since we are not going to agree I will spare this.

**Comment by alexander-akait** [comment]
@barak007 What do you need more?

**Pull request closed without merging**
