### PR TITLE
export EntryObject for typescript usage

### PR DESCRIPTION
**Pull request by chenxsan**
**What kind of change does this PR introduce?**

export `EntryObject` for typescript usage:

```ts
import type {EntryObject} from 'webpack'
const entry: EntryObject = {
  main: './src/index.js'
}
```

Currently I have to define it myself https://github.com/chenxsan/voidjs/blob/master/packages/voidjs-cli/src/DevServer/index.ts#L35:

```
export interface EntryObject {
  [index: string]:
    | [string, ...string[]]
    | {
        import: string | string[]
        dependOn: string | string[]
      }
}
```

**Did you add tests for your changes?**
No, I believe it's not needed.

**Does this PR introduce a breaking change?**
Nope.

**What needs to be documented once your changes are merged?**
Nothing.

### CODE REVIEW

**Review by vankop — APPROVED** [review]

**Comment by alexander-akait** [comment]
Why do not use:
```ts
import type { Configuration } from 'webpack'
const entry: Configuration["entry"] = {
  main: './src/index.js'
}
```

**Comment by chenxsan** [comment]
> Why do not use:
> 
> ```ts
> import type { Configuration } from 'webpack'
> const entry: Configuration["entry"] = {
>   main: './src/index.js'
> }
> ```

Thanks for sharing, it does work in my use case. However I just want  `EntryObject` specifically, I don't want a gorilla (`Configuration["entry"]`) holding a banana (`EntryObject`) even that banana is what I need.

In addition, when I export my entry to use in another file, it will soon get into trouble although it's just a trivial example:

image

**Comment by alexander-akait** [comment]
In this case, we need to export all nested types...

**Comment by sokra** [comment]
Thanks

**Pull request merged**
