### PR TITLE
Initial spike for dumping a profile

### PR DESCRIPTION
**Pull request by samccone**
Add the ability to dump a profile from the profiling plugin.

For now this dumps to events.log but this is very much only a spike

### CODE REVIEW

**Comment by samccone** [comment]
:wave: @TheLarkInn :)

**Comment by TheLarkInn** [comment]
Thanks a shitton Sam.

**Comment by TheLarkInn** [comment]
I'll fix the string quote stuff and hook up the schema and everything else.

**Comment by TheLarkInn** [comment]
Actually now that I think about it, @samccone what are the typical steps for this to be setup with node --inspect and profiling. Is this recorded to "just work" in node debugger?

**Comment by samccone** [comment]
hmm the setup imho for this would be be someone would run webpack --trace=foo.json
Then go into chrome devtools or about://tracing and drop foo.json in. 📊 

This profiling is not really the same as a CPU profile from webpack.. however we could totally merge both reports together into 1 uber trace if we wanted.

**Pull request merged**
