### PR TITLE
add option to polyfill node's root variable on bundling

### PR DESCRIPTION
**Pull request by goldensunliu**
proposed fix for https://github.com/webpack/webpack/issues/1085

### CODE REVIEW

**Comment by sokra** [comment]
please add root to the test case

**Comment by bebraw** [comment]
@goldensunliu Do you want to have another look?

**Comment by goldensunliu** [comment]
@bebraw I will

**Comment by SpaceK33z** [comment]
I'm closing this issue because of inactivity. Feel free to make a new PR.

**Pull request closed without merging**
