### PR TITLE
Moved types to devDependencies

### PR DESCRIPTION
**Pull request by atassis**
There is no need to keep types in production dependencies.

**What kind of change does this PR introduce?**
refactoring

**Did you add tests for your changes?**
No need.

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
None

### CODE REVIEW

**Review by alexander-akait — CHANGES_REQUESTED** [review]
No, types should be in dependencies

**Comment by atassis** [comment]
Can you explain why?

**Comment by alexander-akait** [comment]
Because types is the part of package, with types typescript fails

**Comment by atassis** [comment]
Okay, I see now types are provided since webpack 5, my bad

**Pull request closed without merging**
