### PR TITLE
analyse source code for side effects

### PR DESCRIPTION
**Pull request by sokra**
**What kind of change does this PR introduce?**
feature

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
* `optimization.sideEffects` will also flag modules as side effect free when they contain only side effect free statements

### CODE REVIEW

**Comment by vankop** [comment]
what if `module a -> module b(side effect free) -> module c(side effect free) -> module d(with/possible side effect)` (-> is "imports") will webpack render modules b,c ? in case when no exports consumed (`import "b";`). Did not see a test case for that or maybe I missed something..

Will this works with css-loader, mini-css?

**Comment by sokra** [comment]
> what if `module a -> module b(side effect free) -> module c(side effect free) -> module d(with/possible side effect)` (-> is "imports") will webpack render modules b,c ?

Yes, that's also in the test cases. the `import "module c"` as side effects in this case to module b is not side effect free

**Comment by vankop** [comment]
>Yes, that's also in the test cases. the import "module c" as side effects in this case to module b is not side effect free
yes, it is transitively with side effect.

**Comment by sokra** [comment]
> Will this works with css-loader, mini-css?

Yes, that was implemented for mini-css.

It needs a minimal change to opt-in and flag it's CssDependency with `TRANSITIVE_ONLY` side effects.

**Comment by maapteh** [comment]
awesome

**Pull request merged**
