### PR TITLE
allow RegExp as managed and immutable paths

### PR DESCRIPTION
**Pull request by sokra**
add all node_modules as managedPaths in futureDefaults

**What kind of change does this PR introduce?**
feature

**Did you add tests for your changes?**
no

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

**Comment by joshhogg** [comment]
I noticed there isn't much in the documents for this, but it could be very helpful if it was in there. I wouldn't mind making the change, but could use a bit of insight into the design approach. 

- I noticed that the same patterns that work for `rules[n].exclude` patterns don't work here. ie: `/.*node_modules((?!non-managed-lib).)*$/`
- I also noticed that the code keeps track of both files and directories to watch, is there a way to specify just a directory easily? 

If I had a package / shared library that I wanted webpack to keep an eye on, called `non-managed-lib`, how would I write the RegEx for it? What was the intent? RegEx is not my strongest. I came up with something like this:
`/^(.+?[\\/]node_modules)[\\/]((?!non-managed-lib)).*[\\/]*/)` but that seems to add the files individually as well, and not just the directories.

**Comment by alexander-akait** [comment]
PR welcome for docs (we have an issue)

**Comment by IronGeek** [comment]
Is there a specific reason why regex is chosen over the original requested feature here: https://github.com/webpack/webpack/issues/12112?

I've tried using regex to define a negative pattern for excluding specific folders  (non managed paths), but my experience so far is somewhat similiar with @joshhogg above. I've got a lot of warning saying:

```
<w> Managed item _<some/managed/folder/>_ isn't a directory or doesn't contain a package.json
```

TBH, I myself prefer if the managed and immutable paths configuration is similiar the to rule exclude/ include pattern

**Comment by cattermo** [comment]
Did anyone ever manage to use this feature? Just seems totally broken. We got the same error as IronGeek. 

Ping @sokra

**Comment by alexander-akait** [comment]
@cattermo Can you provide an exanple of the problem?

**Comment by cattermo** [comment]
> @cattermo Can you provide an exanple of the problem?

Here is a small repository to reproduce the problem. 
https://github.com/cattermo/webpack-managed-path-regex

I'm using a pretty standard Regex to include all but one package in `managedPaths`: 
`/node_modules\/(?!(@azure\/msal-browser)\/).*/`

When running webpack I get error 
```
/**/webpack-managed-path-regex/node_modules/webpack/lib/FileSystemInfo.js:791
	let i = managedPath.length;
	                    ^

TypeError: Cannot read properties of undefined (reading 'length')
    at getManagedItem (/**/webpack-managed-path-regex/node_modules/webpack/lib/FileSystemInfo.js:791:22)
    at checkManaged (/**/webpack-managed-path-regex/node_modules/webpack/lib/FileSystemInfo.js:2021:26)
    at captureNonManaged (/**/webpack-managed-path-regex/node_modules/webpack/lib/FileSystemInfo.js:2044:10)
    at FileSystemInfo.createSnapshot (/**/webpack-managed-path-regex/node_modules/webpack/lib/FileSystemInfo.js:2127:25)
    at handleBuildDone (/**/webpack-managed-path-regex/node_modules/webpack/lib/NormalModule.js:1046:32)
    at handleParseResult (/**/webpack-managed-path-regex/node_modules/webpack/lib/NormalModule.js:991:12)
    at /**/webpack-managed-path-regex/node_modules/webpack/lib/NormalModule.js:1098:4
    at processResult (/**/webpack-managed-path-regex/node_modules/webpack/lib/NormalModule.js:800:11)
    at /**/webpack-managed-path-regex/node_modules/webpack/lib/NormalModule.js:860:5
    at /**/webpack-managed-path-regex/node_modules/loader-runner/lib/LoaderRunner.js:407:3

**Comment by alexander-akait** [comment]
@cattermo Sorry for delay, please use `/(node_modules\/(?!(@azure\/msal-browser)\/)).*/`, 

You can look at the default value - `/^(.+?[\\/]node_modules)[\\/]/` (for npm), here you should have a directory (not true/false), i.e. using group (`()`). 

I think we should document this. Feel free to questions

**Comment by cattermo** [comment]
> @cattermo Sorry for delay, please use `/(node_modules\/(?!(@azure\/msal-browser)\/)).*/` or just `/(node_modules\/(?!(@azure\/msal-browser)\/))/`
> 
> You can look at the default value - `/^(.+?[\\/]node_modules)[\\/]/` (for npm), here you should have a directory (not true/false), i.e. using group (`()`) on the part of path. Also I recommend to use `[//\]`, because I think you need windows here.
> 
> But it will add `node_modules` to a manager path, but I think you expected to add all except `@azure/msal-browser`...
> 
> Try this:
> 
> ```
> /^(.+?[\\/]node_modules[\\/](?!(@azure[\\/]msal-browser))(@.+?[\\/])?.+?)[\\/]/
> ```
> 
> Looks tricky, but should work.
> 
> I think we should document this. Feel free to ask questions.

So we just needed the capture group 🤦‍♀️
Thanks for the help! Would be great if this was documented since Regex in rules works differently.

**Comment by auaustorg-ms** [comment]
I am trying to do something similar:

`/^(.+?[\\/]node_modules[\\/](?!(@foo|@bar))(@.+?[\\/])?.+?)[\\/]/`, which works, but I get some warnings like the following:

`Managed item <absolute path>/node_modules/@reduxjs isn't a directory or doesn't contain a package.json (see snapshot.managedPaths option)`

What is the correct regex? I can't even turn off the warning logs. It seems like these logs get logged even if I set up logging to only log errors. Any advice would be great. Thank you so much!

**Comment by Sayan751** [comment]
> I am trying to do something similar:
> 
> `/^(.+?[\\/]node_modules[\\/](?!(@foo|@bar))(@.+?[\\/])?.+?)[\\/]/`, which works, but I get some warnings like the following:
> 
> `Managed item <absolute path>/node_modules/@reduxjs isn't a directory or doesn't contain a package.json (see snapshot.managedPaths option)`
> 
> What is the correct regex? I can't even turn off the warning logs. It seems like these logs get logged even if I set up logging to only log errors. Any advice would be great. Thank you so much!

I am having the same issue. Also, it seems that due to this issue, I am also having the following error from chokidar. If I comment out the `snapshot` configuration, the chokidar error also disappears.

```
LOG from webpack.FileSystemInfo
<w> Managed item ABSOLUTE_PATH\node_modules\@types isn't a directory or doesn't contain a package.json (see snapshot.managedPaths option)
<w> Managed item ABSOLUTE_PATH\node_modules\@redux-devtools isn't a directory or doesn't contain a package.json (see snapshot.managedPaths option)
+ 13 hidden lines

webpack 5.75.0 compiled successfully in 16355 ms
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (ABSOLUTE_PATH\node_modules\chokidar\index.js:647:10)
    at ReaddirpStream.NodeFsHandler._boundHandleError (ABSOLUTE_PATH\node_modules\chokidar\lib\nodefs-handler.js:303:43)
    at ReaddirpStream.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'lstat',
  path: 'C:\\pagefile.sys'
}
```

**Comment by alexander-akait** [comment]
Without configuration I can't help, will be better if somebody create a minimum reproducible test repo, thank you

**Comment by Sayan751** [comment]
@alexander-akait Here is my configuration

```js
snapshot: {
  managedPaths: [
    /^(.+?[\\/]node_modules[\\/](?!(@scope1[\\/])|(@scope2[\\/])|(prefix-.+?[\\/])).+?)[\\/]/
  ]
}
```

The intent is to instruct the webpack to ignore changes in the node module other than `[@scope1|@scope2|prefix-*]/**/*.*`.

**Comment by alexander-akait** [comment]
> /^(.+?[\\/]node_modules[\\/](?!(@azure[\\/]msal-browser))(@.+?[\\/])?.+?)[\\/]/

As you can see you need to provide nested directories (like `msal-browser`, yes, you can change it on `[\\/].+?[\\/]`), otherwise `node_modules\@types` will be consideren as a package

**Comment by gmferise** [comment]
Following what was documented, I tried using a regex like:

`^(.+?[\\/]node_modules[\\/](?!(@ignoreme))(@.+?[\\/])?.+?)[\\/]`

Yet I was still seeing warnings from improper matching:

`Managed item <absolute path>/node_modules/@next isn't a directory or doesn't contain a package.json (see snapshot.managedPaths option)`.

From what I can tell, this regex is actually the correct one:

`^(.+?[\\/]node_modules)[\\/](?!(@ignoreme))(@.+?[\\/])?.+?[\\/]`

The only difference here is what is returned in the first capture group. It seems that when matched against a given path, the regex should output what managed folder it belongs to in capture group 1. From what I can tell, every path is checked against the regex, rather than skipping ones "known" to be within a managed folder.

Hope this helps someone else!

**Comment by alexander-akait** [comment]
@Sayan751 I am fine with array, do you want to send a PR? Should be not hard

**Comment by Sayan751** [comment]
@alexander-akait I have created a PR for this. You may review, and let me know any further changes are required.

**Pull request merged**
