### PR TITLE
replace .charCodeAt() with .startsWidth()

### PR DESCRIPTION
**Pull request by Yinzhuo19970516**
**What kind of change does this PR introduce?**
lib/NormalModuleFactory.js
replace .charCodeAt() with .startsWidth()
code is more understandable

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

**Comment by alexander-akait** [comment]
Tests are failed

**Review by sokra — CHANGES_REQUESTED** [review]
`charCodeAt` is used for performance reasons.

Could you measure the performance difference between both versions.

**Comment by Yinzhuo19970516** [comment]
> `charCodeAt` is used for performance reasons.
> 
> Could you measure the performance difference between both versions.

image
https://hasty.dev/HHHum1ZQlt0XwKsvGiFZAO

**Comment by alexander-akait** [comment]
Yeah, looks like `charCodeAt` is faster, so let's close, anyway thank you fro your PR

**Pull request closed without merging**
