### PR TITLE
hot.accept tap interceptor returns T/F based on the number of args

### PR DESCRIPTION
**Pull request by justinhelmer**
addresses #6919

**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

yes

**If relevant, link to documentation update:**

N/A

**Summary**

#6919 

**Does this PR introduce a breaking change?**

Not to any external interface

### CODE REVIEW

**Comment by ooflorent** [comment]
For the test case, create a folder named `issue-6962` inside `test/hotCases/` and:

- create `test/hotCases/issue-6962/webpack.config.js` with the buggy config
- add your files to assert the `DefinePlugin` worked and the HMR is still working

You can run the _hot_ test suite using:

```
yarn test:integration --grep Hot
```

**Comment by ooflorent** [comment]
If you returns `true` for the hook it means that the parser must stop the traversing so the arguments are not parsed.

For single argument `module.hot.accept` you must return `true` because no further processing is required. However, if there are more arguments, you should return `false` or continue the parsing then return `true`:

```js
parser.walkExpression(expr.arguments[1]); // other args are ignored
return true;
```

**Comment by justinhelmer** [comment]
I squashed into the original commit which is why I cannot resolve the requested change.

**Comment by sokra** [comment]
Thanks

**Comment by justinhelmer** [comment]
@sokra @ooflorent - what about wp3? (per #6919)

**Comment by ooflorent** [comment]
Could you submit a PR for the v3 branch?

**Comment by justinhelmer** [comment]
@ooflorent - I would love to, but am currently blocked. Awaiting feedback from someone who is knowledgeable of the system. Please see my most recent two comments on #6919

**Pull request merged**
