### PR TITLE
Upgrade chrome-trace-event to use its types + add some JSDoc to ProfilingPlugin

### PR DESCRIPTION
**Pull request by mohsen1**
**What kind of change does this PR introduce?**
Bug fix

**Did you add tests for your changes?**
No

**If relevant, link to documentation update:**
N/A

**Summary**
By converting chrome-trace-event and linking the converted code to webpack I noticed we're using the module wrong:

https://github.com/samccone/chrome-trace-event/pull/4

This change tries to fix API usage but I'm not sure what was the intended behavior. Per those errors this never worked before because `tracer.trace` is undefined and `tracer.counter` is not a number. 

**Does this PR introduce a breaking change?**
Not sure 

**Other information**

### CODE REVIEW

**Comment by sokra** [comment]
The CI says otherwise? Maybe the dependency need to be updated?

**Comment by mohsen1** [comment]
@sokra

**Comment by mohsen1** [comment]
@TheLarkInn

**Comment by mohsen1** [comment]
@webpack/core-team this is ready to go

**Comment by mohsen1** [comment]
@sokra

**Comment by mohsen1** [comment]
This is good to go

**Comment by mohsen1** [comment]
ping @TheLarkInn

**Pull request closed without merging**
