### PR TITLE
make chunkLoadTimeout option configurable

### PR DESCRIPTION
**Pull request by restrry**
**What kind of change does this PR introduce?**

feature

**Did you add tests for your changes?**

No tests for options, except schema

**If relevant, link to documentation update:**

In progress

**Summary**

User has no ability to configure chunkLoadTimeout option, since it's missed in schema

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by restrry** [comment]
that [script.timeout](https://github.com/webpack/webpack/blob/f2a6439b59edf1bbacdbfa3d7a702ee6f3671af8/lib/JsonpMainTemplatePlugin.js#L56) is used anywhere?

**Comment by sokra** [comment]
> that script.timeout is used anywhere?

I through it's a browser property, but google can't find it. Maybe this doesn't exist...

**Comment by restrry** [comment]
I have some concerns about testing the feature in the current PR:
1. `chunkLoadTimeout ` in current implementation works only for web pages and chunks are being loaded via script tag
2. tests are run in node environment
3. to make test feasible we need to introduce stub environment for web page, `jsdom` ie. 

Also I didn't manage to find any tests for `JsonpMainTemplatePlugin`. So I'd suggest creating another issue with developing testing infra for `JsonpMainTemplatePlugin` module.
What do you think?

**Comment by sokra** [comment]
yep you are right.

**Comment by restrry** [comment]
@sokra should I create task for adding testing environment for such cases ?

**Comment by wyqbailey** [comment]
great job!

**Pull request merged**
