### PR TITLE
Use Parser#hooks instead of Tapable#plugin

### PR DESCRIPTION
**Pull request by ooflorent**
**What kind of change does this PR introduce?**

refactoring

**Did you add tests for your changes?**

no

**If relevant, link to documentation update:**

n/a

**Summary**

Replace deprecated `Tapable#plugin` calls by `Hook#tap` calls.
After this PR, almost all `plugin` calls would be replaced! 🎉

**Does this PR introduce a breaking change?**

no

### CODE REVIEW

**Comment by ooflorent** [comment]
@sokra Do you want me to rebase the PR?

**Comment by ooflorent** [comment]
I've rebased the PR. Conflicts are gone.

**Comment by ooflorent** [comment]
Everything is fine now 🎉

**Comment by sokra** [comment]
Thanks

**Pull request merged**
