### PR TITLE
fix: remove redundant parentheses

### PR DESCRIPTION
**Pull request by DanielRuf**
This PR removes some redundant parentheses.

**What kind of change does this PR introduce?**
Bugfix

**Did you add tests for your changes?**
No

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**

### CODE REVIEW

**Comment by montogeek** [comment]
This project uses Prettier formatter, this kind of change is handle automatically by it.
Maybe it is better to update it?

**Comment by DanielRuf** [comment]
> this kind of change is handle automatically by it.

Then it would be part of CI and produce failing CIs but I do not see such CI config.

**Comment by DanielRuf** [comment]
> Maybe it is better to update it?

Probably. Not sure if a newer version of prettier does this correctly. Not a big fan of prettier.

https://github.com/webpack/webpack/pull/9284/checks?check_run_id=149094140

**Comment by DanielRuf** [comment]
I'll try to bump the related prettier dependencies and configs.

**Comment by DanielRuf** [comment]
Upgrading the related dependencies does not seem to maky any difference.
Closing due to this.

**Pull request closed without merging**
