### PR TITLE
SourceMapDevToolPlugin: Enable path stripping from source map filenam…

### LINKED ISSUE #5554: SourceMapDevToolPlugin may support the absolute sourceMappingURL
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The source maps comments are  always attached like this  `//# sourceMappingURL=../srcMap/js/test1.js.map`  with a **relative** url.  It will be very usefull if  supports the absolute url.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
It will be very usefull  if it supports the absolute url. 
The use case : 
The comment is  like this `//# sourceMappingURL=http://10.30.1.11/srcMap/js/test1.js.map`,  and we could serve the source map in a server which can only be accessed by developers.
With this,  developers can reproduce the bugs in `production` environment and access the source map with a VPN. Meanwhile, the others will not.

I looked into the  `SourceMapDevToolPlugin.js` file.  It's easy to modify the code to support the feature.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

### PR DESCRIPTION
**Pull request by EugeneHlushko**
…e path when using custom append. Fix a bug where outside directory path was appended to URL (../)

**What kind of change does this PR introduce?**
Improvement and a bugfix

**Did you add tests for your changes?**
No, did not find SourceMapDevToolPlugin tests, not sure its worth to start implementing those from this PR.

**If relevant, link to documentation update:**
https://github.com/webpack/webpack.js.org/pull/1707
```diff
+ The documentation PR is updated again in regard of this PR
```

**Summary**
Enable path stripping from source map filename path when using custom append. Fix a bug where outside directory path was appended to source map URL (../). Fixes #5554

**Does this PR introduce a breaking change?**
No

**Other information**
None

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
Hi @sokra 
Wouldnt path.relative always add `../` when doing a build on the upper level when used against source file?

**Comment by sokra** [comment]
btw. why should somebody store SourceMap outside of the build directory? This defeats the propose of a build directory.

**Comment by EugeneHlushko** [comment]
Why i've picked this up is that some time ago i had similar setup to the one issue creator had so i thought it might be useful.

What we did was getting source maps outside of build directory and in post-build hook uploading them to S3 bucket which had been limiting access to our internal VPN ip address pool. where bundles would point the url with appropriate source map name e.g. https://10.10.10.10/project/sourcemaps/js/bundle-[hash].js.map

```
project
 | files...
└───build
│       │   bundle-[hash].js
│       │   ...
│   
└───sourcemaps
│       │   bundle-[hash].js.map
│       │   ...
```

I know that we could filter out source maps during deploy of the `build` in a static build setup. or configure nginx to limit access to the maps in public `build` directory or whatsoever.

**Comment by sokra** [comment]
``` text
project
│  files...
└───build
│       └───public
│       │       │   bundle-[hash].js
│       │       │   ...
│       │   
│       └───sourcemaps
│       │       │   bundle-[hash].js.map
│       │       │   ...
```

**Comment by sokra** [comment]
I guess in this scenario it makes sense to have a `context` and `publicPath` option.

``` js
output.filename: "public/bundle-[hash].js"
new SourceMapDevToolPlugin({
  filename: "sourcemaps/[file].map",
  publicPath: "https://10.10.10.10/project/", // <- emits absolute urls with this prefix
  fileContext: "public" // <- makes the [file] argument relative to this directory
})
```

=> `https://10.10.10.10/project/bundle-[hash].js.map`

**Comment by EugeneHlushko** [comment]
Yeah this is a matter of configuration now, but in this same case wouldn't we get `../sourcemaps/` while telling the path to go `relative` from `root/build/public/[file].js` to `root/build/souremaps/[file].js.map`

**Comment by EugeneHlushko** [comment]
hi @sokra i plan to work on this this Sat, any thoughts on how to deal with current append in regard of this? What i thought was checking if `publicPath ` isset then override the `append` argument.

**Comment by sokra** [comment]
`publicPath` only modifies `[url]` before `append` is used.

**Comment by EugeneHlushko** [comment]
ok seems like it does what we wanted, a test case added. pls check @sokra

**Comment by EugeneHlushko** [comment]
Hi @sokra 
Looks good to me if works. Want me to adda test case when `publicPath` used without `fileContext`?

**Comment by EugeneHlushko** [comment]
Documentation PR has been updated. https://github.com/webpack/webpack.js.org/pull/1707/files

**Comment by EugeneHlushko** [comment]
Hi @sokra this is kinda hanging in the air, any comments on the PR itself?

**Comment by sokra** [comment]
Thanks

**Pull request merged**
