### PR TITLE
Normalize property access for imports and exports

### LINKED ISSUE #17135: Normalize property access for imports and exports
## Feature request

Currently webpack exports using quote notation and imports using dot notation.

e.g., look at the use of the "*a*" property:
```
...
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "a": function() { return /* binding */ ActionOperation; }
/* harmony export */ });
...
var ActionOperation = __webpack_require__(86792);
class ProcessActionOperation extends ActionOperation/* ActionOperation */.a {
...
```

Some optimizing compilers such as the Google Closure Compiler see these as different.  They use the quote notation as a way to say, "hands off" when it comes to minifying variable names so that external interfaces can be preserved.  This leads to it seeing x["somevar"] and x.somevar as two different properties, such that x.somevar is minified and x["somevar"] is converted to x.somevar (shorter by one char but not minified).  See [the Closure docs](https://developers.google.com/closure/compiler/docs/api-tutorial3#propnames) for more.

**What is the expected behavior?**

It's important for webpack to be consistent in the generation and consumption of properties - either dot notation or quote notation.  This was mostly OK in webpack 4; webpack 5 introduced breaking changes.

**What is motivation or use case for adding/changing the behavior?**

Get webpack 5 to generate output compatible with the Google Closure Compiler.

**How should this be implemented in your opinion?**

The proposed change is relatively straightforward.  A new method `propertyName` will be introduced using similar logic to `propertyAccess`.  This will be used instead of JSON.stringify when creating property names.

**Are you willing to work on this yourself?**

Yes

### PR DESCRIPTION
**Pull request by bworline**
fixes #17135  

### <samp>🤖 Generated by Copilot at 2b2fed5</samp>

This pull request improves the code generation and optimization of harmony modules and their dependencies. It introduces a new `propertyName` function and module that ensures valid and consistent property names for export and import keys. It also fixes a bug in the `ConcatenatedModule` plugin and adds test cases for the import-export-format feature.

### <samp>🤖 Generated by Copilot at 2b2fed5</samp>

*  Add `propertyName` function and module to generate valid JS property names for harmony exports ([link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-0342f86e328a87c47d6f8774da92286f85b22c8da403c651556558139e55b610R1-R79), [link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-6321ce7b02e6ffde09945cc25ea272d1c47b6b53d5e0b8314b7835aee706513cR22), [link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-6321ce7b02e6ffde09945cc25ea272d1c47b6b53d5e0b8314b7835aee706513cL1222-R1223), [link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-95163456d908f22a8890eddaa37b822d43f46427eacca095f0a81a2f1c1eb1d8R11), [link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-95163456d908f22a8890eddaa37b822d43f46427eacca095f0a81a2f1c1eb1d8L153-R154), [link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-d34dd78b4ea6b37ac0551517562d61f39d0fc50699240a065ec8b13b37e2ed66R38), [link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-d34dd78b4ea6b37ac0551517562d61f39d0fc50699240a065ec8b13b37e2ed66L1487-R1488), [link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-d34dd78b4ea6b37ac0551517562d61f39d0fc50699240a065ec8b13b37e2ed66L1532-R1535), [link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-f94c283ed7ab0c2d55c51de7eb19c77e792031b09cecdf0f99bdb205703c2adfL80-R81))
*  Replace `JSON.stringify` with `propertyAccess` function to generate valid JS property access expressions for harmony exports ([link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-a589af16bdcbd682b34e532fe49dc23a5c831c5313d229de7b1817c98319c11fR11), [link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-a589af16bdcbd682b34e532fe49dc23a5c831c5313d229de7b1817c98319c11fL175-R178))
*  Move constants `SAFE_IDENTIFIER` and `RESERVED_IDENTIFIER` from `propertyAccess` module to `propertyName` module ([link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-ea95106ee448a96b949a56b3f8ba4c90dbb69789a4e3d47f35a388a66278c70eL8-R11))
*  Add test cases for import-export-format feature, which checks the consistency of property access syntax for various module types and optimization options ([link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-c62203f3d340531362b9a66fdbfcdefa5bc0261a3aa0dd94b9a02ce52ebc1ae1R1-R3), [link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-0ab822ea6a1cd9f2d5a1393397ce519104a8ce552be3c4de4a4b01a19a6bf22bR1-R5), [link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-f54d437d26d2af67fb5d7c30817512fc7348a807136557e0d42793bde7b41ecdR1), [link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-505c1829ad63114d173ac19cede7a48491f1f8b5c3694f376b9a99ea30dd6dd8R1-R5), [link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-8f8e0d42a1a273f5eb69b922ee5970bd3e454da7ed35286de4e1588df4c9889fR1-R52), [link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-f02a0988dba637868eab622c55354ee57cee0b46294bc967c2495bf2ba75f81aR1-R14))
*  Add unit tests for `propertyAccess` and `propertyName` functions ([link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-bda760f4d3368cdf70f404837585665d707dd6ffaed7416c0342c6939d1090aaR1-R26), [link](https://github.com/webpack/webpack/pull/17137/files?diff=unified&w=0#diff-02921ff45c78972924783ed9619fa60fb05e9e16a9d168b2a0682b4d7ef639b4R1-R15))

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]
Looks good, can you accept CLA?

**Review by TheLarkInn — APPROVED** [review]
Looks great from what I can tell!

**Comment by TheLarkInn** [comment]
@alexander-akait: I want to hold off on merging this because @bworline shared a case where there might be some TDZ/Variable/Export ordering issues from this PR's generated bundles.

**Comment by bworline** [comment]
> @alexander-akait: I want to hold off on merging this because @bworline shared a case where there might be some TDZ/Variable/Export ordering issues from this PR's generated bundles.

In the bundle0.js generated by this new ConfigCases test, I noticed that the concatenated module logic is generating code that is out-of-order.  Essentially, this:

```
console.log(apple);
...
var apple = 45;
```

Admittedly I did some crazy things with import and export including a circular reference, but I'm thinking it should either yell at me, produce correctly ordered code (if possible), or bail out of concatenating.

To be clear this is existing behavior and not something introduced by this PR.

**Comment by alexander-akait** [comment]
@bworline Can you provide a test case where I can look at this?

**Comment by TheLarkInn** [comment]
> To be clear this is existing behavior and not something introduced by this PR.

I wasn't aware of this detail, however we should probably look into this 😅 (I'll follow up).

**Comment by bworline** [comment]
@TheLarkInn is there anything else needed before this PR can be merged?

**Comment by alexander-akait** [comment]
@bworline Is it ready to review?

> In the bundle0.js generated by this new ConfigCases test, I noticed that the concatenated module logic is generating code that is out-of-order. Essentially, this:

`bundle0.js` is the default output filename in our test cases, can you provide path to `bundle0.js`?

**Comment by alexander-akait** [comment]
@bworline I looked at this PR and found the problem, shorty - circular dependecies and yes, it was not introduced by this PR, so I think we can safely merge it, catching these cases are tricky, maybe we can disable concat modules for circular dependecies, but in other way our logic works correcntly with many other cases (and simple cases with cirucal dependecies) and disabling this can be a problem, so I prefer to merge this as is and open a new issue about it

**Review by TheLarkInn — APPROVED** [review]

**Comment by TheLarkInn** [comment]
Thank you for this change!

**Pull request merged**
