### PR TITLE
Fix: entrypoints use filename when runtimeChunk is used

### PR DESCRIPTION
**Pull request by SevInf**
**What kind of change does this PR introduce?**

Fix for #6598. Achieved by forcing `ChunkTemplate` to use filename tempalte if chunk contains entry module. So, chunks without runtime will still use `ChunkTemplate`,  but filename will stay the same.

**Did you add tests for your changes?**

I adjusted `statsCases/runtime-chunk-single` to include `output.chunkTemplate`. It now also ensures that `filename` is used for entrypoints regardless of runtime chunk. Let me know if you prefer separate test for it.

**Does this PR introduce a breaking change?**

I don't think so, but it might break workarounds for original issue, like renaming plugins. 

**What needs to be documented once your changes are merged?**

~I don't think any changes to documentation are necessary.~

EDIT(sokra):

Now all chunks that are not referenced on-demand use `filename`. All chunks referenced on-demand use `chunkFilename`.

### CODE REVIEW

**Comment by ooflorent** [comment]
This is a breaking change

**Comment by SevInf** [comment]
@ooflorent this was the behavior in webpack 3. [Source](https://github.com/webpack/webpack/blob/v3.12.0/lib/Compilation.js#L1380). Judging from the fact that #6598 and #6604 exist, i don't think the change in webpack 4 was intentional. In #6598 @sokra mentions:

>All chunks are equal, technically a chunk used at entry time could also used on-demand for another entry. 

Which could be a reason for the change. In practice though, it is not possible and webpack [actively prevents this](https://github.com/webpack/webpack/blob/master/lib/AsyncDependencyToInitialChunkError.js#L11).

**Comment by sokra** [comment]
> In practice though, it is not possible

It's possible. Not even that unlikely to happen with multiple entrypoints, on demand chunks and the recommended splitChunks configuration.

**Comment by sokra** [comment]
Technically this change could still be done, as it only affects chunks with entry modules and these should be safe to change the filename for. But it's a breaking change so we have to delay it until the next major version.

**Comment by SevInf** [comment]
> Not even that unlikely to happen with multiple entrypoints, on demand chunks and the recommended splitChunks configuration.

@sokra what is the recommended splitChunks configuration? [See this example](https://github.com/SevInf/webpack-entry-ondemand). `a.js` and `b.js` are entrypoints and `a` also loads `b` on demand. `runtimeChunk` is set to single, `splitChunk` is  default. Build ends with and error:

>ERROR in ./src/a.js
>It's not allowed to load an initial chunk on demand. The chunk name "b" is already used by an entrypoint.

**Comment by sokra** [comment]
> what is the recommended splitChunks configuration?

`splitChunks.chunks: "all"`

> It's not allowed to load an initial chunk on demand. The chunk name "b" is already used by an entrypoint.

You are not allowed to reuse the chunk name. Don't give it a name or give it another name.

---

In your example you can create a chunk which is initial for entrypoint b and on demand for entrypoint a with these changes:

``` js
// a.js
import(/* webpackChunkName: "async-b" */ './b');
```

``` js
// b.js
console.log('hello'); console.log('hello'); console.log('hello'); 
/* repeated often so the file is over 30kb */
console.log('hello'); console.log('hello'); console.log('hello'); 
```

``` js
// webpack.config.js
module.exports = {
    mode: 'development',
    entry: {
        a: './src/a.js',
        b: './src/b.js'
    },
    optimization: {
        runtimeChunk: 'single',
        splitChunks: {
            chunks: "all"
        }
    },
    stats: {
        chunkGroups: true
    }
};
```

`yarn upgrade webpack` elsewise you run into a already fixed bug.

```
Hash: 14f81cacd4b492386ffe
Version: webpack 4.10.1
Time: 415ms
Built at: 2018-05-29 16:50:02
     Asset       Size   Chunks             Chunk Names
      a.js  474 bytes        a  [emitted]  a
async-b.js   60.8 KiB  async-b  [emitted]  async-b
      b.js  110 bytes        b  [emitted]  b
runtime.js   8.76 KiB  runtime  [emitted]  runtime
Entrypoint a = runtime.js a.js
Entrypoint b = runtime.js async-b.js b.js
Chunk Group async-b = async-b.js
[./src/a.js] 49 bytes {a} [built]
[./src/b.js] 60.4 KiB {async-b} [built]
```

`async-b.js` is the chunk. It must get `chunkFilename` to be loaded by the runtime. So not all initial chunks can get `filename` as it was with webpack 3.

But as I mentioned before chunks with entrypoints (here: `a.js` and `b.js`) could get `filename`. So I'm happy to merge this PR for the next major version.

**Comment by ooflorent** [comment]
@SevInf Could you rebase your branch on `next` and change the target branch of this PR to it?

**Comment by SevInf** [comment]
@ooflorent done

**Comment by sokra** [comment]
Thanks

**Pull request merged**
