### PR TITLE
simplify numberToIdentifer method

### PR DESCRIPTION
**Pull request by timse**
**What kind of change does this PR introduce?**

refactoring

**Did you add tests for your changes?**

there are tests in place, this is just a refactoring

**Summary**

I am currently reading large parts of the webpack source to get a better understanding what is happening and I kind of tripped over this method here. This refactoring is by all means not necessary, I just felt reading the Method took me longer than necessary, especially `AZ2_COUNT` and `Z2_CODE` feel unnecessary and making it harder to read. 

**Does this PR introduce a breaking change?**

No, its a refactoring

**Other information**

I guess it makes it a little easier to read, if that is reason enough.

### CODE REVIEW

**Comment by ev1stensberg** [comment]
Did you run ´beautify´ before the PR?

**Comment by timse** [comment]
yes i did, nothing showed up, the failing test is unrelated to my code, if I see that correctly

**Comment by Kovensky** [comment]
It's actually broken in `master`

**Comment by TheLarkInn** [comment]
Try rebasing master. I pushed a change to fix this flakeyness in one of my PR's also.

**Comment by sokra** [comment]
Thanks

**Pull request merged**
