### PR TITLE
Refactor parser (and introduce es6)

### PR DESCRIPTION
**Pull request by timse**
**What kind of change does this PR introduce?**

refactoring

**Did you add tests for your changes?**

Tests coverage existed already

**If relevant, link to documentation update:**

N/A

**Summary**

Refactored the parser. (this is only a first step to see direction and needs cleanup, but this is already getting too huge).
It splits the logic of the parser into seperate units instead of heaving all of them being taken care of at the same time.
Also it uses acorns walker to traverse the AST instead of the previously self implemented traverser.

**Does this PR introduce a breaking change?**

Maybe (not sure about dependencies to `evaluate ...` plugin part
could be reimplemented for backwards compat

**Other information**

this was a long and hard process. some of the `bugs` during refactor took literal days to find, please dont be too hard on it 😰

### CODE REVIEW

**Comment by timse** [comment]
rebased against master, removed most breaking changes

the only one left is, that:
 - `parser.walkStatement(s)`
 - `parser.walkExpression(s)` 

does no longer exist and is now `this.traverseNodeInCurrentScope`.

However "stubs" that call `traverseNodeInCurrentScope` could be readded. I just doubt anyone ever used those methods?

**Comment by TheLarkInn** [comment]
@sokra we should take a look at this. This is a huge plus to the parser

**Comment by sokra** [comment]
Could you pick the `refactor parser to be a class` into a separate PR?

I want to get this into the code fast. After that remaining PR should have a better diff.

**Comment by timse** [comment]
on it :)

**Comment by sokra** [comment]
I'll merge #4635 at first and rebase this on top of this...

#4635 includes the first commit of this PR.

**Comment by timse** [comment]
Whats the reasoning behind merging #4635 first? This PR contains #4635, merging it first, will however probably create a merge conflict no one can untangle.

**Comment by sokra** [comment]
> Whats the reasoning behind merging #4635 first? This PR contains most(all?) of #4635. However merging it first, will however probably create a merge conflict no one can untangle.

It's a small and easy to review PR doing **as single thing**. Your PR does multiple things, so it's just a gigantic PR which is difficult to review. Parts of it are good, parts not. That's not good.

Do small PR which change **a single thing**.

---

I rebased the PR. I probably pick some parts of it into separate. But I'm pretty sure I'll be unable to merge the whole PR.

**Comment by timse** [comment]
I tried to keep it small, but since the parser is everything in one, the parser, walker, transformer, visitor its not as easy as it sounds to keep this small.

**Comment by sokra** [comment]
outdated

**Pull request closed without merging**
