### PR TITLE
Use relative path

### PR DESCRIPTION
**Pull request by zxcabs**
Use relative path for NormalModule#identifier
fix for error https://github.com/webpack/webpack/issues/644

### CODE REVIEW

**Comment by zxcabs** [comment]
:up:

**Comment by zxcabs** [comment]
@sokra ?

**Comment by sokra** [comment]
I cannot merge this... but I'll try to find another solution.

**Comment by zxcabs** [comment]
why not? :(

**Comment by hufeng** [comment]
@sokra  why not? :(

**Comment by liouh** [comment]
+1

I ran into this problem as well (not using sourcemaps). Here are the steps I used to reproduce this:

1. Check out repo
2. Run webpack
3. Rename the repo directory
4. Run webpack again
5. New output has a whole different set of hashes

Diffing the build artifacts, the only difference I see is the line containing the id-to-hash mappings:

```
75c75
< /******/ 			script.src = __webpack_require__.p + "" + "ee43f52bc378424e5c4f" + "." + {"1":"d991bdcdeed9c6063436","2":"72bbe8978519ba0192bb","3":"d0e26fc646183d5d6af5","4":"fa4e73f02ef4d5b161f7","5":"724ca13c597afc8b95d0","6":"522bb9a459c461779e55","7":"2f5ec38ee8e3f5240760","8":"d62113b4db92ae9a6805","9":"bd8f21b18791f8f29d0c","10":"45d75956edd38447d413","11":"1dfee83bdf855bfab635","12":"2815cc4d4812bb060bc7","13":"83a4861ae379321d486b","14":"7dc9618b49c3b92dfa06","15":"a0ad42c9989e4024307b","16":"0277cc689ed667d2a059","17":"2622e7980a60e435961d","18":"b1f7141d128fbca2baeb","19":"d95761617d21eced40de","20":"e10c5a4fc0d0d4e15cdd","21":"638e3a5ba5b6c474436a","22":"36c90deacc90f1da9a71","23":"661a4dff4eb141732200","24":"785c1aae9047e9a89adc","25":"077f51e3441c4f74ab28","26":"036e93156f2dc667f65b","27":"2e0d8cec0e33480f3bd1","28":"9a053c456d4ae32d1c7f","29":"d0f79b15a53908599b03"}[chunkId] + ".js";
---
> /******/ 			script.src = __webpack_require__.p + "" + "9e532737191e3f640f9e" + "." + {"1":"41e7bb4f37ee1ba1f4e5","2":"59a46dacbdc9fc98a22a","3":"c4190f9b30be6fad3eea","4":"737d42b346fed6904c18","5":"724ca13c597afc8b95d0","6":"522bb9a459c461779e55","7":"2f5ec38ee8e3f5240760","8":"d62113b4db92ae9a6805","9":"bd8f21b18791f8f29d0c","10":"45d75956edd38447d413","11":"1dfee83bdf855bfab635","12":"2815cc4d4812bb060bc7","13":"83a4861ae379321d486b","14":"7dc9618b49c3b92dfa06","15":"a0ad42c9989e4024307b","16":"0277cc689ed667d2a059","17":"2622e7980a60e435961d","18":"b1f7141d128fbca2baeb","19":"d95761617d21eced40de","20":"e10c5a4fc0d0d4e15cdd","21":"638e3a5ba5b6c474436a","22":"36c90deacc90f1da9a71","23":"661a4dff4eb141732200","24":"785c1aae9047e9a89adc","25":"077f51e3441c4f74ab28","26":"036e93156f2dc667f65b","27":"2e0d8cec0e33480f3bd1","28":"9a053c456d4ae32d1c7f","29":"d0f79b15a53908599b03"}[chunkId] + ".js";
```

This quirk makes it inconvenient when working with a CDN. Even if a file has not changed, I'm forced to upload new versions -- losing the long-term caching benefit.

Any recommended workarounds?

Thanks.

**Comment by zxcabs** [comment]
fix in webpack 1.8.2

**Comment by dmitry** [comment]
Still an issue in 1.12.2: https://github.com/webpack/webpack/issues/1479

**Pull request closed without merging**
