### PR TITLE
fix: remove duplicate code blocks in condition and switch-case

### PR DESCRIPTION
**Pull request by DanielRuf**
This PR removes duplicate code blocks in a condition and in a few switch-case statements.

**What kind of change does this PR introduce?**
Bugfix

**Did you add tests for your changes?**
No

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**

### CODE REVIEW

**Comment by DanielRuf** [comment]
> * This need to be

Small typo, should be probably `This needs to be`

**Comment by montogeek** [comment]
Could you please add tests?

**Comment by DanielRuf** [comment]
> Could you please add tests?

For what exactly? Please take a closer look at the changes. These do not change the programmatic flow of webpack ;-)

**Comment by sokra** [comment]
Thanks

**Pull request merged**
