### PR TITLE
Using DllPlugin with multiple chunks ends without emitting chunks.

### PR DESCRIPTION
**Pull request by jnwng**
When utilizing code-splitting via a statement like `require.ensure` in addition to the `DllPlugin`, the webpack process would emit the Dll manifest, but not the chunks corresponding to that manifest.

According to [async#forEach](https://github.com/caolan/async#eacharr-iterator-callback), the callback must be called at the completion of every iteration - when utilizing code-splitting, the shortcut branch here would never call the iterator callback, which in turn meant that the `emit` callback never got called, causing the chunks generated by webpack to not get emitted.

Adding the completion callback results in the behavior we expect - the manifest and the chunks corresponding to that manifest both get emitted.

### CODE REVIEW

**Comment by jnwng** [comment]
@sokra I added a small test that would have broken prior to the bugfix, however, the test harness complains about tests not being exported. the compiled file ends with `module.exports = __webpack_require__;` whereas i would expect it to end with `module.exports = __webpack_require__(0);` to actually run the test. 

i suspect that this is due to the nature of the DllPlugin exporting files to be referenced via the DllReferencePlugin - how do you suggest that i move forward on testing this (or, due to the complexity of testing those two plugins, perhaps i can omit the test here for this bug fix?)

**Comment by sokra** [comment]
You can use only the `LibManifestPlugin` instead of the `DllPlugin`. The only difference is the behavior of the entry points. Than try to validate the manifest in the test case.

**Comment by jnwng** [comment]
this can be backported to webpack 1.12 as a patch too - what's the best way to get it in 1.12.10?

**Comment by sokra** [comment]
Thanks

**Pull request merged**
