### PR TITLE
chore(deps): update `schema-utils`

### PR DESCRIPTION
**Pull request by evilebottnawi**
**What kind of change does this PR introduce?**

refactoring

**Did you add tests for your changes?**

No need

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

Nothing

### CODE REVIEW

**Review by sokra — APPROVED** [review]
Linting issue. yarn yarn-lint-fix

**Comment by evilebottnawi** [comment]
@sokra fixed, maybe we can implement export of `schema-utils` in this PR (for plugins)?

**Review by sokra — APPROVED** [review]

**Comment by sokra** [comment]
Thanks

**Comment by sokra** [comment]
> maybe we can implement export of `schema-utils` in this PR (for plugins)?

yep, but in the separate PR as this one is so clean already

**Pull request merged**
