### PR TITLE
bump webassemblyjs

### PR DESCRIPTION
**Pull request by xtuc**
**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

Fixes some licensing issues, https://github.com/xtuc/webassemblyjs/issues/452.

### CODE REVIEW

**Comment by sokra** [comment]
@DavidStaheli 

image

`-1m`?

**Comment by xtuc** [comment]
In checks it reported 
screenshot from 2018-09-21 11-29-17

**Comment by sokra** [comment]
Thanks

**Comment by DavidStaheli** [comment]
@sokra, regarding "-1m"... Wow... your mail arrives before it's sent. Thanks for letting me know so we can fix it.

**Comment by DavidStaheli** [comment]
Hi @sokra.  It turns out that the build completing in `-1m` is actually from GitHub and not data we're sending.

**Pull request merged**
