### PR TITLE
WIP : Lib(Asset) : Code refactor - Destructing object 

### PR DESCRIPTION
**Pull request by jeffin143**
**What kind of change does this PR introduce?**
refactoring

**Did you add tests for your changes?**
NA

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
None

### CODE REVIEW

**Comment by dmitryuk** [comment]
Could you shortly describe, why your way to set variables is better than current one?

**Comment by evilebottnawi** [comment]
I agree, changes only in some places create noise in git and unnecessary, we need to turn on eslint rule to make it consistent and update throughout the codebase

**Comment by jeffin143** [comment]
> I agree, changes only in some places create noise in git and unnecessary, we need to turn on eslint rule to make it consistent and update throughout the codebase

I was doing a subfolder by subfolder , so that I don't break anything 

May be es lint is good

**Comment by jeffin143** [comment]
> Could you shortly describe, why your way to set variables is better than the current one?

I just used destructuring as in other lines -> https://github.com/webpack/webpack/blob/1c228160c20d8649452bacbe2884e6513863e7cb/lib/asset/AssetModulesPlugin.js#L149

I was going through assets folder and hence changes it accordingly

**Comment by evilebottnawi** [comment]
Please enable rule and do refactor on all code base in the one PR, it is not big changes to separate on few PRs

**Comment by ScriptedAlchemy** [comment]
Yeah agreed, eslint auto-fix should refactor this in one go

**Comment by jeffin143** [comment]
@evilebottnawi and @ScriptedAlchemy PTAL, I guess linting fails of some other issue, 

Can we be quick on this because webpack is growing fast and there are many merge conflicts if pr is stagnant for a while

**Comment by ScriptedAlchemy** [comment]
Those are typescript errors

**Pull request closed without merging**
