### PR TITLE
fix IgnoreWarningsPlugin plugin not working

### PR DESCRIPTION
**Pull request by JarynChen**
**What kind of change does this PR introduce?**
a bugfix

**Did you add tests for your changes?**
I have tested manually

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
No need to modify

### CODE REVIEW

**Comment by alexander-akait** [comment]
I don't think it is bug fix

**Comment by JarynChen** [comment]
> I don't think it is bug fix

I tested it for several days. According to the current official code, this plugin cannot be executed normally, and the callback in compiler.hooks.afterCompile.tap cannot be entered normally. I wonder if there are any precautions for use.

**Comment by alexander-akait** [comment]
Please create reproducible test repo

**Comment by JarynChen** [comment]
> Please create reproducible test repo

OK，i close the pr first，I'll create a reproducible test repository later，thanks

**Pull request closed without merging**
