### PR TITLE
fix: resolving cjs and mjs

### PR DESCRIPTION
**Pull request by alexander-akait**
**What kind of change does this PR introduce?**

bugfix:
- allow to resolve default entry `index.cjs` and `index.mjs`
- allow to resolve `dep.cjs`

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

In theory yes, but I think it is bugfix

**What needs to be documented once your changes are merged?**

Maybe

### CODE REVIEW

**Comment by sokra** [comment]
How does node.js behave?

**Comment by evilebottnawi** [comment]
Do you mean `require('./file')`, where `file.cjs`?

**Comment by sokra** [comment]
Yes. Does that work?

**Comment by evilebottnawi** [comment]
@sokra hm, you are right `cjs` is not working on node (very weird, I always think it should work :smile: ), should we support cjs/mjs entry points, because I think it will be popular in future

**Comment by sokra** [comment]
Node.js doesn't implement automatic extensions for .cjs and .mjs.
The JS ecosystem is trending in the direction of not automatically adding extensions.
Browsers can't automatically add extensions.
Each extension has a performance cost for resolving.

So I think we better don't do that.

**Pull request closed without merging**
