### PR TITLE
Fixes #5392 - Allow destructuring using EnvironmentPlugin

### LINKED ISSUE #5392: EnvironmentPlugin: destructuring process.env doesn't work
**Do you want to request a *feature* or report a *bug*?**
report a *bug*

**What is the current behavior?**
Destructuring `process.env` doesn't work.
`console.log(MY_VAR);` logs `undefined`

**Steps to reproduce.**

webpack.config.js

```js
const path = require("path");
const {EnvironmentPlugin} = require("webpack");

module.exports = {
    entry: "./main.js",
    output: {
        path: path.resolve(__dirname),
        filename: "bundle.js"
    },
    plugins: [
        new EnvironmentPlugin(["MY_VAR"])
    ]
};
```

main.js

```js
const {MY_VAR} = process.env;
console.log(MY_VAR); // logs undefined
console.log(process.env.MY_VAR); // logs "test"
```

command

```bash
MY_VAR=test webpack
```

**What is the expected behavior?**
`console.log(MY_VAR);` should log "test"

Node.js version: 8.2.1
webpack version: 3.4.1
OS version: Ubuntu 17.04

### PR DESCRIPTION
**Pull request by THernandez03**
I'm getting the exact same problem described in the issue (#5392). So I review the previous approaches to solve it (#8721), but I think is not necessary to change the current behavior. Just need to add destructured info to DefinePlugin.

**What kind of change does this PR introduce?**

It's a bugfix

**Did you add tests for your changes?**

Not yet... Just need help how to do that and I will make the tests

**Does this PR introduce a breaking change?**

No, just adding more elements to the array of env definitions that we want to use. After that we will use DefinePlugin as always.

**What needs to be documented once your changes are merged?**

Improve EnvironmentPlugin documentation adding examples using object destructuring.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Please accept CLA and tests

**Comment by THernandez03** [comment]
I tried to add the right test for this case, but i don't understand what's happening. I'm getting locally the same error as the one in [CI](https://travis-ci.org/webpack/webpack/jobs/633407569?utm_medium=notification&utm_source=github_status) [(link to the error)](https://travis-ci.org/webpack/webpack/jobs/633407569?utm_medium=notification&utm_source=github_status).

Please, can someone help me to do it ?

**Comment by THernandez03** [comment]
I tried to add the right test for this case, but i don't understand what's happening. I'm getting locally the same error as the one in [CI](https://travis-ci.org/webpack/webpack/jobs/633407569?utm_medium=notification&utm_source=github_status) [(link to the error)](https://travis-ci.org/webpack/webpack/jobs/633407569?utm_medium=notification&utm_source=github_status).

Please, can someone help me to do it ?

**Comment by THernandez03** [comment]
I tried to update this PR rebasing from master due to the recent `webpack@5` release, but still getting that huge error... I don't know why I'm getting this and how to solve it... somebody can help me with this ?? @evilebottnawi

**Comment by vankop** [comment]
Thanks for your contribution. I am closing PR because it is too stale..

**Pull request closed without merging**
