### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by e-cloud**
**Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)(dependencies update)
- [ ] Build related changes
- [ ] CI related changes

**What is the current behavior?** (You can also link to an open issue here)
should.js compare two object deeply without their prototype
acorn doesn't report duplicated variable declarations

**What is the new behavior?**
should.js compare two object deeply with their prototype
acorn will report duplicated variable declarations

**Does this PR introduce a breaking change?**
- [x] Yes
- [ ] No

If this PR contains a breaking change, please describe the following... 

* Impact: Only if someone uses duplicated variable declarations with es6 module system(which is illegal) before, that will break down the webpack build flow.
* Migration path for existing applications: 
avoid duplicated variable declarations
* Github Issue(s) this is regarding:
#1792 

Other Information:
this PR can be merged only after #3193 is merged.

### CODE REVIEW

**Comment by TheLarkInn** [comment]
Could you resolve conflicts? And update branch?

**Comment by e-cloud** [comment]
rebased, but it still fails the test until #3193 is merged

**Comment by e-cloud** [comment]
@TheLarkInn why do often merge master into the PR branch? IMHO, that would make the commit tree  redundant somehow.

**Comment by TheLarkInn** [comment]
I'm just updating the branch w/ the native github feature.

**Comment by e-cloud** [comment]
Ah, I see. Did it have some conflicts which makes you update the branch?

**Comment by TheLarkInn** [comment]
Yes

**Pull request merged**
