### PR TITLE
fix(resolve): allows filesysteminfo to resolve files that have #'s

### LINKED ISSUE #12156: Unable to resolve loaders if directory contains an octothorpe
# Bug report

**What is the current behavior?**

Webpack is unable to resolve loaders if the folder name contains # (octothorpe/number sign/pound/hash)
The error output shows a whitespace character being added in front of the symbol which in turn causes the required files not to be found.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a project where the root directory or any directory leading up to it has a name containing the #-symbol, e.g. "#Test".
Add webpack and any loader (e.g. ts-loader) as dependencies.
When trying to run a webpack build it will throw an exception such as the following;
(Note the prepended whitespace in the error message which is not seen in the require stack)
```
ERROR in ../ #Test/src/main.ts
Module build failed (from ../ #Test/node_modules/ts-loader/index.js):
Error: Cannot find module 'C:\Projects\ #Test\node_modules\ts-loader\index.js'
Require stack:
- C:\Projects\#Test\node_modules\loader-runner\lib\loadLoader.js
- C:\Projects\#Test\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Projects\#Test\node_modules\webpack\lib\NormalModule.js
- C:\Projects\#Test\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Projects\#Test\node_modules\webpack\lib\Compiler.js
- C:\Projects\#Test\node_modules\webpack\lib\webpack.js
- C:\Projects\#Test\node_modules\webpack\lib\index.js
- C:\Projects\#Test\node_modules\webpack-cli\lib\utils\package-exists.js
- C:\Projects\#Test\node_modules\webpack-cli\lib\webpack-cli.js
- C:\Projects\#Test\node_modules\webpack-cli\lib\bootstrap.js
- C:\Projects\#Test\node_modules\webpack-cli\bin\cli.js
- C:\Projects\#Test\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (C:\Projects\#Test\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at loadLoader (C:\Projects\#Test\node_modules\loader-runner\lib\loadLoader.js:19:17)
    at iteratePitchingLoaders (C:\Projects\#Test\node_modules\loader-runner\lib\LoaderRunner.js:183:2)
    at runLoaders (C:\Projects\#Test\node_modules\loader-runner\lib\LoaderRunner.js:396:2)
    at NormalModule.doBuild (C:\Projects\#Test\node_modules\webpack\lib\NormalModule.js:631:3)
    at NormalModule.build (C:\Projects\#Test\node_modules\webpack\lib\NormalModule.js:775:15)
    at C:\Projects\#Test\node_modules\webpack\lib\Compilation.js:1193:12
```

**What is the expected behavior?**
Loaders being found regardless of special characters in the full path name.

**Other relevant information:**
webpack version: 5.10.0
Node.js version: 14.15.1
Operating System: Windows 10
Additional tools: -

### LINKED ISSUE #13148: Persistent cache throws warning about build dependency resolution because it's missing a \u0000 char
# Bug report

**What is the current behavior?**

```webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Resolving '.pnpm/es5-ext@0.10.53/node_modules/es5-ext/array/#/clear' in /Users/scamden/creditiq/uno/common/temp/node_modules/.pnpm/es6-iterator@2.0.3/node_modules/es6-iterator for build dependencies doesn't lead to expected result '/Users/scamden/creditiq/uno/common/temp/node_modules/.pnpm/es5-ext@0.10.53/node_modules/es5-ext/array/#/clear.js', but to '/Users/scamden/creditiq/uno/common/temp/node_modules/.pnpm/es5-ext@0.10.53/node_modules/es5-ext/array/#/clear.js' instead. Resolving dependencies are ignored for this path.```

warning on writing persistent cache in development mode if the dep has a # in the path and has already been loaded by node prior to dependency resolution for the cache.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/creditiq/simple-repros/tree/webpack-cache-resolution-warning

Repro:
1. Clone the above
2. `npm run build`

Result:
warning above

Expected:
 no warning

 I have tracked the bug down to a \u0000 in the resolved result (that was added by webpack code when escaping the # one stack frame above the warning) that is not there in the `job.expected` value.

 The expected value in my case was resolved via the require.cache inside the RBDT_FILE_DEPENDENCIES job as a RBDT_RESOLVE_CJS_FILE_AS_CHILD. I checked every path and child path one level deep in that cache and not one value had a \u0000 in it so I'm guessing the fix is to escape # with \0 when the file was found in the require.cache, but the code is a bit over my head so hopefully this lead gives someone more familiar a light bulb. Maybe alternatively the expected and result values should be compared with any \0 stripped out. Hopefully a maintainer will know 😬 I've made a PR for the latter because it feels lower risk, but if the right solution is to add escaping to paths found in the require.cache, I'm happy to do that as instead :) 

webpack version:  5.31.0
Node.js version: 14.16.0
Operating System: Mac OS X Catalina
Additional tools:

### PR DESCRIPTION
**Pull request by scamden**
escaped with \0

i don't understand the reasoning behind @sokra's escaping in enhanced resolve well enough to know if this makes sense or is basically just undoing the hard work he did to distinguish these characters from fragments. maybe he can chime in if this makes no sense to do

closes #13148
closes #12156

@sokra  not sure if the escaping in the commit below was meant to be used in other places but it breaks here. i'm very new to all of this code so let me know if this direction is wrong. 
https://github.com/webpack/enhanced-resolve/commit/17cf8fee0769cafce3067aa4d169cefad26e107a

**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

not yet. once again not sure if this is the right direction or just a regression of the fragment work in enhanced resolve

**Does this PR introduce a breaking change?**

nope

**What needs to be documented once your changes are merged?**

nada

### CODE REVIEW

**Comment by sokra** [comment]
Could you sign the CLA? https://cla.js.foundation/webpack/webpack?pullRequest=13157

**Review by sokra — APPROVED** [review]

**Comment by scamden** [comment]
ah very nice. i figured there must be something that keeps the enhanced-resolve logic encapsulated. we already have the split up result in the third argument. (probably would have seen that if the code were typescript haha, i'm spoiled now and can hardly read plain js). thanks for the follow up here

**Comment by sokra** [comment]
> probably would have seen that if the code were typescript haha, i'm spoiled now and can hardly read plain js

There are type definitions, but they need some improvements... Too many `any`s:

``` ts
	export function create(
		options?: any
	): (
		context?: any,
		path?: any,
		request?: any,
		resolveContext?: any,
		callback?: any
	) => void;
```

from https://github.com/webpack/enhanced-resolve/blob/c4aa24d665ba4169d423588e39e050bc434f580d/types.d.ts#L465-L473

They are generated from this line of code: https://github.com/webpack/enhanced-resolve/blob/c4aa24d665ba4169d423588e39e050bc434f580d/lib/index.js#L66

If you want to you could add some JSDoc to improve the types. Run `yarn special-lint-fix` to regenerate `types.d.ts`.

**Comment by sokra** [comment]
Thanks

**Comment by scamden** [comment]
ya i dug down until i found the `any` haha, i could have figured it out from context in the `finishResolved` function but my brain just isn't attuned to it. 

why not slowly convert the code to real TS? too much compile time?

**Pull request merged**
