### PR TITLE
fix global in `electron-renderer` target

### LINKED ISSUE #10035: Uncaught ReferenceError: global is not defined
# Bug report

I have an `Electron` based application. we do `webpack ` in the render process. It throws error when I run the app
`Uncaught ReferenceError: global is not defined`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
It should not throw this error when I run the application

**Other relevant information:**
here is the Error:
```
index.js?e792:25 Uncaught ReferenceError: global is not defined
    at eval (index.js?e792:25)
    at Object../node_modules/@babel/polyfill/lib/index.js (feb33beb921cb1f5a1b3.worker.js:97)
    at __webpack_require__ (feb33beb921cb1f5a1b3.worker.js:20)
    at eval (eval at ./node_modules/babel-loader/lib/index.js?{"babelrc":false,"presets":["@babel/preset-env", "@babel/preset-react"]}!./node_modules/ts-loader/index.js?{"transpileOnly":true,"configFile":"tsconfig.webpack.json"}!./node_modules/ts-loader/index.js?!./packages/myApp/modules/frameworks/file-provider/box-provider/webworker/box.worker.ts (feb33beb921cb1f5a1b3.worker.js:526), <anonymous>:2:73)
    at Module../node_modules/babel-loader/lib/index.js?{"babelrc":false,"presets":["@babel/preset-env", "@babel/preset-react"]}!./node_modules/ts-loader/index.js?{"transpileOnly":true,"configFile":"tsconfig.webpack.json"}!./node_modules/ts-loader/index.js?!./packages/myApp/modules/frameworks/file-provider/box-provider/webworker/box.worker.ts (feb33beb921cb1f5a1b3.worker.js:526)
    at __webpack_require__ (feb33beb921cb1f5a1b3.worker.js:20)
    at feb33beb921cb1f5a1b3.worker.js:84
    at feb33beb921cb1f5a1b3.worker.js:87
```

Note: Since it is an electron app: 
config.target = "electron-renderer";
{global:true};

webpack version:  ^4.41.2
Node.js version: 10.16.3
Operating System: windows 10
"@babel/core": "^7.6.4"
Additional tools: chrome 78
Electron version : 7.1.1

### PR DESCRIPTION
**Pull request by xcodebuild**
fix #10035, and fix some releatd test case which is not working

**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

**Comment by xcodebuild** [comment]
@evilebottnawi I have accpeted CLA long ago, but the bot always say it's not signed yet.

image

**Comment by evilebottnawi** [comment]
@xcodebuild do you use the same email for commits and CLA?

**Comment by xcodebuild** [comment]
> @xcodebuild do you use the same email for commits and CLA?

Yes, both `me@xcodebuild.com`

**Comment by evilebottnawi** [comment]
@xcodebuild fixed

**Comment by xcodebuild** [comment]
@evilebottnawi `CLA` turns into `not signed yet` again

**Comment by evilebottnawi** [comment]
@xcodebuilddo something on CLA side, all is fine, do not worry

**Comment by evilebottnawi** [comment]
@xcodebuild Sorry for delay, I think this fix wrong, because it depends on `webPreferences.nodeIntegration`, with `true` value `global`/`nodeBuiltins` and `require` exists, with `false` you should use `target: 'web'`, because you compiler your application just web page

**Pull request closed without merging**
