### PR TITLE
Changed name of memorize function to memoize

### PR DESCRIPTION
**Pull request by highonweb**
Hi
I am new to opensource contribution and I was interested in webpack so I started going through the codebase.
There was a function named memorize I didn't know what it did. after a couple of searches I came to know it was called memoize function.

**What kind of change does this PR introduce?**
It changes name of a function to more accurate one making it easy to understand the codebase for new contributors like me

**Did you add tests for your changes?**
This doesn't require any tests

**Does this PR introduce a breaking change?**
I don't think so since it is an util

**What needs to be documented once your changes are merged?**

Nothing

### CODE REVIEW

**Comment by alexander-akait** [comment]
No thanks. There's no benefit here.

**Comment by highonweb** [comment]
ok

**Review by sokra — APPROVED** [review]
Yes that's correct and we should change the function to the correct naming

**Comment by sokra** [comment]
Thanks

**Pull request merged**
