### PR TITLE
Fix #12310

### LINKED ISSUE #12310: Webpack 5 generates syntax error for 'define'
# Bug report

**What is the current behavior?**

Webpack 5 generates syntax error for 'define' 

**If the current behavior is a bug, please provide the steps to reproduce.**

Given an input like this:

```javascript
// transport
if ( typeof define === 'function' && define.amd ) {
  // AMD
  define( 'eventie/eventie',eventie );
} else {
  // browser global
  window.eventie = eventie;
}
```

The line with the `define` call results in this generated code in webpack 5:

```javascript
!(__WEBPACK_LOCAL_MODULE_1__factory = (eventie), (typeof __WEBPACK_LOCAL_MODULE_1__factory === 'function' ? (__WEBPACK_LOCAL_MODULE_1__module = { id: "eventie/eventie", exports: {}, loaded: false }), (__WEBPACK_LOCAL_MODULE_1__ = __WEBPACK_LOCAL_MODULE_1__factory.call(__WEBPACK_LOCAL_MODULE_1__module.exports, __webpack_require__, __WEBPACK_LOCAL_MODULE_1__module.exports, __WEBPACK_LOCAL_MODULE_1__module)), (__WEBPACK_LOCAL_MODULE_1__module.loaded = true), __WEBPACK_LOCAL_MODULE_1__ === undefined && (__WEBPACK_LOCAL_MODULE_1__ = __WEBPACK_LOCAL_MODULE_1__module.exports) : __WEBPACK_LOCAL_MODULE_1__ = __WEBPACK_LOCAL_MODULE_1__factory));
```

which can be reduced to this:

```javascript
  !(a, (b ? (c), (d), (e), f && (g) : h));
```

which is a syntax error, and makes Terser fail:

```
ERROR in common.js from Terser
Unexpected token punc «,», expected punc «:» [...]
```

You can check the syntax error on Chrome's console or terser online: https://xem.github.io/terser-online/

(The code generated in webpack 4 is fine, it looks something like `!(__WEBPACK_LOCAL_MODULE_1__factory = (eventie), (a), b = (c ? (d) : e), (f), g && (h));`

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.11.1
Node.js version: 12.18.2
Operating System: macOS Cataline
Additional tools: nope

### PR DESCRIPTION
**Pull request by sarimarton**
The modified line was syntactically incorrect

Fixes https://github.com/webpack/webpack/issues/12310

**What kind of change does this PR introduce?**

bugfix for an obvious JS syntax error

**Did you add tests for your changes?**

Up to you guys

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

nothing

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]
Can you add test?

**Comment by alexander-akait** [comment]
And please accept CLA

**Comment by sarimarton** [comment]
> Can you add test?

I think the best would be to make the creator of that part of the code have a look on this. Otherways I'm fine with patch-package...

**Review by sokra — CHANGES_REQUESTED** [review]
Looks good, please also add an test case for this. You can add a case to `test/cases/parsing/local-modules`.

**Comment by sarimarton** [comment]
> Looks good, please also add an test case for this. You can add a case to `test/cases/parsing/local-modules`.

Sorry, i don't know how to add a test for this. The files you're referring to (`test/cases/parsing/local-modules/index.js`), as far as I can understand, are not relevant, as they test the behavior of `define` calls. This is a transformation issue. There's a plain syntax error in one of the transformation templates. I suppose those templates don't have a test yet, otherwise this bug would have been uncovered earlier. But again, I might be missing something about the test suite, I've read `test/README.md` which didn't really help me in where to look to cover this bug.

**Comment by alexander-akait** [comment]
Can you add test here https://github.com/webpack/webpack/tree/master/test/configCases

**Comment by sokra** [comment]
Thanks

**Pull request merged**
