### PR TITLE
Set deterministic module ids in prod by default

### LINKED ISSUE #8268: Hashed module ids by default
## Feature request

**What is the expected behavior?**

Consistent chunk hash

**What is motivation or use case for adding/changing the behavior?**

After [this PR](https://github.com/webpack/webpack/pull/8029) we have got worst long-term caching "out of the box" because modules id were changed very often (even if don't change these modules) and chunk hash was changed too (because modules id were in bootstrap code).

**How should this be implemented in your opinion?**

`optimization.moduleIds: 'hashed'` in prod-mode by default

**Are you willing to work on this yourself?**
yes

### PR DESCRIPTION
**Pull request by smelukov**
closes #8268

**What kind of change does this PR introduce?**

build related change

**Did you add tests for your changes?**

just updated snapshots

**Does this PR introduce a breaking change?**

no (?)

**What needs to be documented once your changes are merged?**

about `optimization.moduleIds`

### CODE REVIEW

**Comment by smelukov** [comment]
Any ideas what’s wrong with tests?

**Comment by sokra** [comment]
The CI on the `next` branch was a bit unstable.

**Comment by smelukov** [comment]
Thanks!

**Comment by sokra** [comment]
Thanks

**Pull request merged**
