### PR TITLE
replaced calls to Object.assign with objectAssign to support node 0.12.x

### PR DESCRIPTION
**Pull request by MarkusKramer**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ x] Bugfix

**What is the current behavior?**
Issue #3041. With node 0.12.x it fails with
```
/node_modules/webpack/lib/NormalModuleFactory.js:217
            return callback(null, Object.assign({}, item, {
                                         ^
TypeError: undefined is not a function
```

**Does this PR introduce a breaking change?**
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by sokra** [comment]
Thanks for the fix.

**Comment by sokra** [comment]
@TheLarkin merge it. Can't merge from phone. A test for `module.rules[].parser.node` may be added.

**Comment by TheLarkInn** [comment]
@MarkusKramer would you be willing to write the test for this? Otherwise make an issue for the test and I'll merge.

**Comment by MarkusKramer** [comment]
Sorry, I know next to nothing about these three modules and don't feel that I could write a test for them.
I could rewrite it to

    require('object-assign')({}, localOptions, parserOptions.node);

to increase test coverage ;-) (jocking)

@TheLarkInn I've created issue #3081

**Pull request merged**
