### PR TITLE
Export more types

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
Export more types.
Refers https://github.com/webpack/webpack/issues/11630#issuecomment-783608255

### <samp>🤖 Generated by Copilot at 5460618</samp>

This change adds type definitions for the `Externals` option in `lib/index.js`. This improves the type checking and documentation of how webpack handles external modules.

### <samp>🤖 Generated by Copilot at 5460618</samp>

* Add type definitions for `Externals` option and related types ([link](https://github.com/webpack/webpack/pull/12774/files?diff=unified&w=0#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1R14-R18))

**Did you add tests for your changes?**
NA

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
Nothing

### CODE REVIEW

**Comment by sokra** [comment]
Why is this needed? That are internal types. Shouldn't be `Externals` enough?

**Comment by alexander-akait** [comment]
cc @AviVahl

**Comment by AviVahl** [comment]
`Externals` is using those types, inherently making them not internal. In general, every type *referenced by public API* should be exposed. If I'm a consumer of that API, I may need to reference those types when creating abstractions and/or using the API.

In this specific instance, my team has code generating externals configuration. While the `Externals` union is useful to type-check everything that's allowed into the `'externals'` field, it's not useful when creating actual values and using them. In our case, the code was creating an externals function right before executing webpack: https://github.com/wixplosives/engine/pull/653/files#diff-d6ec012a7a03496d87dca423d476cc98a58436e956d2c0fce21dd47baf0a6bedL292 I've had to use multiple workarounds around the missing exports.

**Comment by alexander-akait** [comment]
@snitin315 Can we rebase?

**Comment by snitin315** [comment]
@alexander-akait Done.

**Review by alexander-akait — APPROVED** [review]

**Review by TheLarkInn — APPROVED** [review]
Nice!

**Pull request merged**
