### PR TITLE
chore(deps): update `jest`

### PR DESCRIPTION
**Pull request by evilebottnawi**
**What kind of change does this PR introduce?**

Update deps

**Did you add tests for your changes?**

Existing tests

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

Nothing

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Looks jest buggy with some of regexp

**Comment by evilebottnawi** [comment]
Issue in jest repo: https://github.com/facebook/jest/issues/9614

**Comment by vankop** [comment]
@evilebottnawi  but in CI all is ok.. I have already mentioned this problem but did not investigate it..

**Comment by evilebottnawi** [comment]
@vankop https://github.com/webpack/webpack/pull/10443/files  and https://github.com/webpack/webpack/pull/10443/files#diff-683c19e6bbc651ff5c95f16d8915e990R75 are workarounds

**Pull request merged**
