### PR TITLE
Adding types

### PR DESCRIPTION
**Pull request by Brian-McBride**
**What kind of change does this PR introduce?**

This exposes more type definitions that are required for proper plugin development using Typescript.

**Did you add tests for your changes?**

There are no existing type tests. Added the types and ran the `fix` script as directed.

**Does this PR introduce a breaking change?**

Np, there are no type changes, just adding to the final export. The `fix` script changed the actual definition file. My edit was only to `lib/index.js`

**What needs to be documented once your changes are merged?**

Nothing. Typescript is self documentation.

### CODE REVIEW

**Comment by alexander-akait** [comment]
Can you accept CLA?

**Comment by Brian-McBride** [comment]
> Can you accept CLA?

I would be happy to. I'm looking for a link to accept it.

**Comment by Brian-McBride** [comment]
Weird that checks failed now. 
`6 files have unexpected coverage changes not visible in diff`
Something is amiss with the codecov. Only 2 files were changed and that was exposing more types. 
Seems odd that code coverage would drop in anyway.

**Comment by alexander-akait** [comment]
Ignore this

**Review by alexander-akait — COMMENTED** [review]
Please avoid changes in code

**Comment by cr0cK** [comment]
Any chance to see this reviewed and merged?

**Comment by sokra** [comment]
This PR is broken and I can't modify it. Closing in favor of https://github.com/webpack/webpack/pull/14855

**Pull request closed without merging**
