### PR TITLE
feat: add warning for asyncModule

### PR DESCRIPTION
**Pull request by ahabhgk**
related to #11874

Downgrade the async/await is too hard, there must have a async function that capture the user's top-level-await, so I don't think there is a way to downgrade the code, which can capture the await and not using async function.

So this PR only add a warning for it.

**What kind of change does this PR introduce?**

- Add `output.environment.asyncFunction`
- Add warning for asyncModule (topLevelAwait, asyncWebAssembly) when the target environment doesn't support async/await

**Did you add tests for your changes?**
Add `configCases/async-module/environment-not-support-async-warning`

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

Add `output.environment.asyncFunction`

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Thank you

**Comment by steverep** [comment]
> Downgrade the async/await is too hard, there must have a async function that capture the user's top-level-await, so I don't think there is a way to downgrade the code, which can capture the await and not using async function.

The async function can be transpiled to a generator: https://www.npmjs.com/package/transform-async-modules-webpack-plugin

@alexander-akait is there an easy way I can suppress this warning from inside my plugin?  I was looking to just apply an instance of `IgnoreWarningsPlugin`, but it looks like that may not be eexposed on the compiler instance somewhere (or maybe the types aren't)?

**Comment by ahabhgk** [comment]
> The async function can be transpiled to a generator: https://www.npmjs.com/package/transform-async-modules-webpack-plugin

Yes, it's easy to transpile it in renderModuleContent hook using babel, but without babel, I've consider to manually transpile it with `Dependency` and add a `async_to_generator` runtime to downgrade to es6, it's easy in [some cases](https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA0ssrsxLVkgrzUsuyczPUyhPTSpITM6OTwQJx%2Bfmp5TmpGpoKlRzKQBBYnliZomCIVctAA1q8Ug1AAAA&config=H4sIAAAAAAAAA12RSW7DMAxF9z6FwXUWbYF20Tv0EKxCOwo0QaSDuIHvXkmOFdnQRnqf4vD56Poerqzgu3%2Bka3oEjEyxvhPh2QneEwFSFllFHQROm3rlLA1omApaVgUE40hSfvHH2%2FsnbDyi48FH25aIhEoaUNAQiS8ZLqcXPtONjA%2BWXI6XOFEjxsmJtpSL4iTeomhVO61ZwIcUpf92U%2BY5tQ1GD%2FM2TpN4NP43oV18wrfk1YHlCbWY0sMF04FGXLrjbdl5Zrxn2pcHq93aUzVLeRuSNXzsEyy60dB%2BG90zO1h%2Fnor43LPMgdbtfMEraCtWE4Pmn%2B1ndrtb%2FgGAuJ10MwIAAA%3D%3D), but what really make it hard is [`for await`](https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA0ssrsxLVkgrzUsuyczPUyhPTSpITM6OTwQJx%2Bfmp5TmpGpoKlRzKQBBWn6RQmJ5YmaJgkZOaolCokJ%2BmkJ0LFC2lqsWALEfkMlIAAAA&config=H4sIAAAAAAAAA12RSW7DMAxF9z6FwXUWbYF20Tv0EKxCOwo0QaSDuIHvXkmOFdnQRnqf4vD56Poerqzgu3%2Bka3oEjEyxvhPh2QneEwFSFllFHQROm3rlLA1omApaVgUE40hSfvHH2%2FsnbDyi48FH25aIhEoaUNAQiS8ZLqcXPtONjA%2BWXI6XOFEjxsmJtpSL4iTeomhVO61ZwIcUpf92U%2BY5tQ1GD%2FM2TpN4NP43oV18wrfk1YHlCbWY0sMF04FGXLrjbdl5Zrxn2pcHq93aUzVLeRuSNXzsEyy60dB%2BG90zO1h%2Fnor43LPMgdbtfMEraCtWE4Pmn%2B1ndrtb%2FgGAuJ10MwIAAA%3D%3D), and downgrade to es5 is even harder.

> @alexander-akait is there an easy way I can suppress this warning from inside my plugin? 

```js
apply(compiler) {
  (compiler.options.ignoreWarnings ??= []).push((warning) => warning.name === 'EnvironmentNotSupportAsyncWarning')
  // ...
}
```

this should work, but maybe apply `IgnoreWarningsPlugin` is a better way, I'm not sure should we expose it on the compiler? @alexander-akait

**Comment by alexander-akait** [comment]
Another solution - `new IgnoreWarningsPlugin(...options).apply(compiler);` and pass options to ignore this error

**Comment by steverep** [comment]
> Another solution - `new IgnoreWarningsPlugin(...options).apply(compiler);` and pass options to ignore this error

That's what I tried first, but that plugin is not exposed in the API.  The snippet from @ahabhgk does work though.  I had thought it was too late to manipulate options.

PS - Using `ignoreWarnings` makes it awkward or impossible to use `stats.hasWarnings()` because it still returns `true` even if they are all ignored.  Not sure if that's a bug or intentional.realize it wasn't too

**Pull request merged**
