### PR TITLE
Fix incorrect path cropping in RequestShortener

### PR DESCRIPTION
**Pull request by ilgonmic**
Fix https://github.com/webpack/webpack/issues/9764

**What kind of change does this PR introduce?**
bugfix

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by ilgonmic** [comment]
Yes, I need some time to understand CI problem
And then I can add tests

**Comment by ilgonmic** [comment]
@evilebottnawi Add unit tests for `RequestShortener`

**Comment by sokra** [comment]
Thanks

**Pull request merged**
