### PR TITLE
Allow regex for watchOptions.ignored

### PR DESCRIPTION
**Pull request by tribou**
In webpack@4.x.x, I was using a RegExp for `watchOptions.ignored` to ignore all directories under `node_modules` except for one. (e.g. `/node_modules[\\/](?!my-module)/`)

When following the webpack.js.org documentation, I tried to use a RegExp for `watchOptions.ignored` in v5.0.0-beta.29, and that caused this error:

```
Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.watchOptions.ignored should be one of these:
   [non-empty string, ...] | non-empty string
   -> Ignore some files from watching (glob pattern).
   Details:
    * configuration.watchOptions.ignored should be an array:
      [non-empty string, ...]
    * configuration.watchOptions.ignored should be a non-empty string.
      -> A single glob pattern for files that should be ignored from watching.
```

This pull request removes the validation restriction and allows using a RegExp for `watchOptions.ignored` as already shown in this documentation:

https://webpack.js.org/configuration/watch/#watchoptionsignored

**What kind of change does this PR introduce?**

This change fixes a regression where users were previously able to use a plain RegExp for `watchOptions.ignored` in v4.x.x but can no longer do so in v5.0.0-beta.

Note: I also tried using the `WatchIgnorePlugin` to pass a RegEx, and although I did not get any validation errors, it did not work with the same RegExp to watch only a single node_module for some reason.

**Did you add tests for your changes?**

TODO: if this change is acceptable, I can add tests

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

I believe the existing documentation (https://webpack.js.org/configuration/watch/#watchoptionsignored) may be sufficient.

### CODE REVIEW

**Review by evilebottnawi — COMMENTED** [review]
Can you accept CLA and add tests?

**Comment by sokra** [comment]
Please also run `yarn special-lint-fix` to update some type declarations from the schema change.

**Comment by tribou** [comment]
I tried re-running the tests locally with

`node --max-old-space-size=4096 node_modules/jest-cli/bin/jest --testMatch "<rootDir>/test/*.test.js" --coverage --ci --reporters=jest-junit --runInBand --detectOpenHandles`

<details><summary>RESULT</summary>

Jest has detected the following 2 open handles potentially keeping Jest from exiting:

  ●  WORKER

      351 |                                                                                               `;
      352 |                                                                                               // eslint-disable-next-line node/no-unsupported-features/node-builtins
    > 353 |                                                                                               this.worker = new (require("worker_threads").Worker)(
          |                                                                                                             ^
      354 |                                                                                               workerBootstrap,
      355 |                                                                                               {
      356 |                                                                                               eval: true

      at new Worker (test/ConfigTestCases.template.js:353:30)
      at test/js/ConfigCacheTestCases/worker/web-worker/main.js:261:17
      at Object.<anonymous> (test/helpers/createLazyTestEnv.js:12:13)


  ●  WORKER

      351 |                                                                                               `;
      352 |                                                                                               // eslint-disable-next-line node/no-unsupported-features/node-builtins
    > 353 |                                                                                               this.worker = new (require("worker_threads").Worker)(
          |                                                                                                             ^
      354 |                                                                                               workerBootstrap,
      355 |                                                                                               {
      356 |                                                                                               eval: true

      at new Worker (test/ConfigTestCases.template.js:353:30)
      at test/js/ConfigTestCases/worker/web-worker/main.js:261:17
      at Object.<anonymous> (test/helpers/createLazyTestEnv.js:12:13)
</details>

Then specifically running

`yarn jest ConfigTestCases --detectOpenHandles`

<details><summary>RESULT</summary>

  ● ConfigTestCases › parsing › node-stuff-plugin-off › node-stuff-plugin-off should compile

    : Timeout - Async callback was not invoked within the 20000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 20000ms timeout specified by jest.setTimeout.Error:

      156 |                                                     }, 20000);
      157 |                                             }
    > 158 |                                             it(`${testName} should compile`, done => {
          |                                             ^
      159 |                                                     rimraf.sync(outputDirectory);
      160 |                                                     fs.mkdirSync(outputDirectory, { recursive: true });
      161 |                                                     const deprecationTracker = deprecationTracking.start();

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (test/ConfigTestCases.template.js:158:7)

  ● ConfigTestCases › parsing › relative-filedirname › relative-filedirname should compile

    TypeError: Cannot convert undefined or null to object
        at Function.from (<anonymous>)

      34 |              const map = interception;
      35 |              interception = undefined;
    > 36 |              return Array.from(map)
         |                           ^
      37 |                      .sort(([a], [b]) => {
      38 |                              if (a < b) return -1;
      39 |                              if (a > b) return 1;

      at test/helpers/deprecationTracking.js:36:16
      at test/ConfigTestCases.template.js:163:30
      at lib/webpack.js:123:6
      at lib/HookWebpackError.js:69:3
      at Hook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
      at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (node_modules/tapable/lib/Hook.js:18:14)
      at Cache.shutdown (lib/Cache.js:150:23)
      at Compiler.close (lib/Compiler.js:999:14)
      at lib/webpack.js:122:14

</details>

At this point, I need some help as I'm having trouble understanding the source of the errors and if it's related to changing `watchOptions.ignored`. 😕

**Review by sokra — APPROVED** [review]

**Comment by sokra** [comment]
Thanks

**Pull request merged**
