### PR TITLE
Ensure the HMRPlugin assigns module.hot before NodeStuffPlugin

### PR DESCRIPTION
**Pull request by shellscape**
**What kind of change does this PR introduce?**

This is a fix/modification

**Did you add tests for your changes?**

n/a

**If relevant, link to documentation update:**

n/a

**Summary**

This is a fix/modification to ensure that the HotModuleReplacementPlugin has precedence when setting the value for `module.hot`, regardless of where in the lifecycle the HotModuleReplacementPlugin is applied.

Previously, if the HMR plugin was applied _after_ the NodeStuffPlugin, `module.hot` would be evaluated as falsy in the client, even if the HMR plugin was applied afterwards.

Change per discussion with @sokra 

**Does this PR introduce a breaking change?**

No

**Other information**

### CODE REVIEW

**Comment by shellscape** [comment]
@sokra can you advise on the CI failures?

**Comment by ooflorent** [comment]
There are styling issues

**Comment by sokra** [comment]
You should send the PR to the next branch.

**Comment by shellscape** [comment]
@sokra need this to land in 3.x as well for that crowd. otherwise I'll have to keep duplicate code in hot-client and version check. is it reasonable to release as a patch for 3.x as well?

**Comment by sokra** [comment]
> is it reasonable to release as a patch for 3.x as well?

sadly not, because the pre-v4 plugin system doesn't support custom order of taping

**Comment by ooflorent** [comment]
@shellscape I think is completely broken on this PR. You should close it and create a new one targeting `next`.

**Comment by sokra** [comment]
You can always fix PRs. `git rebase next` and resolving the conflict should fix it.

**Comment by sokra** [comment]
Thanks

**Pull request merged**
