### PR TITLE
chore: Minor typographical fixes

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Fixes include:-
- typo fixes
- grammatical corrections

**What kind of change does this PR introduce?**

refactoring

**Did you add tests for your changes?**
N/A

**Does this PR introduce a breaking change?**
Nope

**What needs to be documented once your changes are merged?**
N/A

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
cc @sokra

**Comment by jamesgeorge007** [comment]
cc @sokra

**Comment by jamesgeorge007** [comment]
cc @sokra

**Comment by sokra** [comment]
Thanks

**Pull request merged**
