### PR TITLE
Multiple build support

### PR DESCRIPTION
**Pull request by sokra**
#1059 

Work in progress...

* [X] DelegatedPlugin, which delegates requests to a require function defined in another module (this may be an external module).
* [x] Plugin, which uses DelegatedPlugin + ExternalsPlugin to load a part of the code base from another bundle, which exports a require function. You feed it with a manifest file
* [x] Plugin, which generates the manifest file
* [x] Loader/Plugin, which provides a entry point which exports the require function and include modules in the bundle.
* [x] merge it
* [ ] add it to the documentation

### CODE REVIEW

**Comment by kpdecker** [comment]
How much of this overlaps with the circus plugin project?
https://github.com/walmartlabs/circus

https://github.com/webpack/webpack/pull/1017#issuecomment-100132157 sounds very much like what that is doing itself.

**Comment by sokra** [comment]
@divmain @baer @geekdave Feel free to try this PR.

---

This PR adds the possiblity to create "dll"s (dynamic linked libraries), which contain a bunch of modules. Dlls can be referenced by other bundles (or dlls). There are two modes how dlls can be referenced: by scope or by context.

By scope: The dll user provides a scope for the dll. All modules in the dll can now be accessed under the scope module name. i. e. `scope: "dll"`: `require("dll/module")` will reference `./module` in the dll.

By context: The dll user provides a directory on disk which has equal content as the `context` provided when the dll was build. This basically expects that the dll contains a pre-built part of the application.

---

### How to build a dll

https://github.com/webpack/webpack/tree/multi-build/examples/dll

* Use the `DllPlugin`
  * provide a `path` option, where to save the manifest file
  * optionally provide a `name` option to embed the library name into the manifest.
    * In most cases the same value as `output.library`
* Provide the `output.library` (and optionally `output.libraryTarget`) to specify how to export the dll.
  * i. e. `library: "abc", libraryTarget: "var"` to export it to the global var `abc` or `libraryTarget: "commonjs2"` to export it as CommonJs module

### How to use a dll

* Use the `DllReferencePlugin`
  * Pass the manifest content as `manifest` option i. e. require it like in the example
  * Pass either `context` as option
    * This uses the "by context" mode
  * Or pass `scope` as option
    * Optionally pass `sourceType` if you provide a value to `output.libraryTarget` (possible options see `ExternalsPlugin`)

---

Pros of dlls:

* Cached separate (Can be deployed separatly)
* Build separate (Faster to build the application)

Cons of dlls:

* More HTTP requests (slower startup)
* Complexer workflow (multiple build steps, more config)

**Comment by divmain** [comment]
@sokra, I'll be looking this through tomorrow.  Thanks for the quick turn-around!

**Comment by divmain** [comment]
@sokra, this all looks very good to me.  We'll be building on top of this in the days to come - and may have feedback at a later date - but don't want to be a gating factor for you here.  Thanks again for adding this, we appreciate it!

**Comment by divmain** [comment]
Any ETA on when this might be merged into master?

**Pull request merged**
