### PR TITLE
Drop node 4 support

### PR DESCRIPTION
**Pull request by timse**
**What kind of change does this PR introduce?**

requirements

**Did you add tests for your changes?**

N/A

**If relevant, link to documentation update:**

N/A

**Summary**

As LTS for v4 was dropped its time to update minimum requirement of node to v6

**Does this PR introduce a breaking change?**

yes as in older node versions may no longer work if this gets merged and features of v6 of node get merged too.

**Other information**

The latest LTS is 6.10+ which also is supported by AWS lambda, therefore it may be reasonable to only support v6+ for the next release

### CODE REVIEW

**Comment by TheLarkInn** [comment]
We follow the maintenence end date which is 2018-04-01 per the [LTS Chart](https://github.com/nodejs/LTS#lts-schedule1) so I think we'd need to wait a year.

**Comment by timse** [comment]
meh, aye :P

**Comment by xtuc** [comment]
Why do you want to drop Node 4 now?

Since Node is officially supported many people rely on that.

**Comment by sokra** [comment]
Done on next branch

**Pull request closed without merging**
