### PR TITLE
chore(deps): update webassemblyjs to support wasm with exception opcodes

### PR DESCRIPTION
**Pull request by bpowers**
Today, webpack will fail if `.wasm` files are referenced that are built with support for exceptions in the following way:

```
Creating an optimized production build...
Failed to compile.

Module parse failed: Unexpected section: 0xd
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
Error: Unexpected section: 0xd


error Command failed with exit code 1.
```

This was fixed upstream in https://github.com/xtuc/webassemblyjs/pull/1117 and a new release of the `webassemblyjs/*` dependencies cut.  This PR updates webpack to use these new dependencies.

**What kind of change does this PR introduce?**

Dependency update

**Did you add tests for your changes?**

No - "just" a dependency update.

**Does this PR introduce a breaking change?**

No.

**What needs to be documented once your changes are merged?**

- WebAssembly modules built with [exception-handling](https://github.com/WebAssembly/exception-handling/blob/main/proposals/exception-handling/Exceptions.md) are now supported by WebPack.

### CODE REVIEW

**Comment by bpowers** [comment]
This actually looks blocked on https://github.com/webpack/webpack/pull/16050

**Comment by bpowers** [comment]
This actually looks blocked on https://github.com/xtuc/webassemblyjs/issues/1132

**Comment by alexander-akait** [comment]
@xtuc can you look at https://github.com/xtuc/webassemblyjs/issues/1132

**Review by sokra — APPROVED** [review]

**Comment by alexander-akait** [comment]
Sorry for big delay, already fixed in master

**Pull request closed without merging**
