### PR TITLE
Use anyOf in place of oneOf where intended

### PR DESCRIPTION
**Pull request by gajus**
Fixes https://github.com/webpack/webpack/issues/3019#issuecomment-248218429

### CODE REVIEW

**Comment by sokra** [comment]
What did you use to sort the keys?

**Comment by gajus** [comment]
> What did you use to sort the keys?

I highly advise using key sorting.

1. It ensures clean commit history.
1. It makes schema scanning predictable (it is easy to miss a property thats added in an arbitrary position; you wouldn't miss it if you knew that properties are sorted alphabetically, you'd know exactly where to look for the property.

From my personal experience managing large JSON config files (e.g. [eslint-config-canonical](https://github.com/gajus/eslint-config-canonical/blob/master/eslintrc.json)), keeping JSON in a consistent format keeps away a lot of trouble.

Furthermore, this step can be automated using https://github.com/zaach/jsonlint tool. In fact, thats exactly what I do with a precommit hook in the [latter repository](https://github.com/gajus/eslint-config-canonical/blob/master/package.json#L40):

```bash
jsonlint --sort-keys --in-place --indent '  ' ./eslintrc.json && echo '' >> ./eslintrc.json
```

I would also advise to use the same practise in the documentation.

Of course, if you insist on "natural" order, I will revert the style change.

**Comment by sokra** [comment]
No the order is great. Would you like to add the linting in another PR?

**Comment by sokra** [comment]
Thank

**Pull request merged**
