### PR TITLE
ci: run tests on node v19

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
CI (also need update deps).

Run tests on node 19 as well.

**Did you add tests for your changes?**
No need.

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
Nothing

### CODE REVIEW

**Comment by snitin315** [comment]
I believe we need to update jest.

**Comment by alexander-akait** [comment]
Wierd:

>   Unable to find JEST_STATE_SYMBOL in Symbol(jest-native-promise), Symbol(jest-native-now), Symbol(jest-native-read-file), Symbol(jest-native-write-file), Symbol(jest-native-exists-file), Symbol($$jest-matchers-object), Symbol(graceful-fs.queue)

> I believe we need to update jest.

Yeah, but we still need to run tests on Node.js v10, anyway we try to update jest and install old version of jest for v10

**Comment by TheLarkInn** [comment]
@snitin315 

This is the suspect code: 

https://github.com/webpack/webpack/blob/b7fc4d876deb958d7ee81ecc00a312e39a354a44/test/helpers/createLazyTestEnv.js#L1-L12

It appears to break due to any Node version > 16

**Comment by alexander-akait** [comment]
I will look at this

**Comment by alexander-akait** [comment]
@SimenB Friendly ping, maybe you can give us some advices, I tried to find why it doesn't work on v18 and no luck, I found jest has `require("jest-circus/build/state").getState()`, but it looks like return no current state, because `currentDescribeBlock.tests` is empty. So what is the big different between jest v27 on Node v16 and Node v18? May it be a bug?

**Pull request closed without merging**
