### PR TITLE
docs: added webpack-cli info guide for more information question

### PR DESCRIPTION
**Pull request by anikethsaha**
`webpack-cli info` give more detailed information about the system and packages.

**What kind of change does this PR introduce?**
issue template

**Did you add tests for your changes?**
No

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
None

### CODE REVIEW

**Comment by montogeek** [comment]
Not sure if people will install another package just to get that information:
image

It is better to rather show the commands for each information: `node -v`, etc.

**Comment by anikethsaha** [comment]
What about using `npx` then ?

**Comment by anikethsaha** [comment]
true, we can **or** like if users have that package then add it else manually

**Comment by anikethsaha** [comment]
true !!....then we can add `npm -g` here instead of `npx` in docs or what say installing `info` globally when not installed message comes in as the `init` package does. ?

**Comment by anikethsaha** [comment]
Or I guess we can leave the current template 👍

**Comment by anikethsaha** [comment]
Yeah...we can make it install at global scope from webpack-cli like its implemented in `init` package.
I guess we can wait for v4 for webpack-cli to implement that

**Pull request closed without merging**
