### PR TITLE
Refactor null dependency to es6

### PR DESCRIPTION
**Pull request by timse**
**What kind of change does this PR introduce?**

refactor

**Did you add tests for your changes?**

current tests should pass

**If relevant, link to documentation update:**

N/A

**Summary**

upgrade NullDependency to es6

**Does this PR introduce a breaking change?**

No

**Other information**

This PR is optimistically based on the successful merge and therefore relies on these:
- [x] #3734
- [x] #3729
- [x] #3728
- [x] #3710
- [x] #3708
- [x] #3705

### CODE REVIEW

**Comment by TheLarkInn** [comment]
@timse WOOT!!! We got dependent PR's reviewed. Go ahead and sync branch, resolve conflicts and lets see where we stand.

**Comment by TheLarkInn** [comment]
Also can you please rebase prev commits from other PR's.

**Comment by timse** [comment]
nice :)!

done

**Comment by timse** [comment]
we can close this thing right :)?

thanks!

**Pull request closed without merging**
