### PR TITLE
[fix] set charset as 'utf-8' in sourcemap plugin in branch webpack-1,…

### PR DESCRIPTION
**Pull request by jaredleechn**
sync webpack/webpack#1797 to branch 'webpack-1'

… fix webpack/webpack#859

### CODE REVIEW

**Comment by sokra** [comment]
Thanks

**Comment by jaredleechn** [comment]
@sokra 

Can you make a release with `webpack@1.x` including this fix?

Very thanks

**Comment by liunian** [comment]
@jaredleechn +1

**Comment by pedrospdc** [comment]
+1

**Pull request merged**
