### PR TITLE
refactor(ES6): upgrade NodeHotUpdateChunkTemplatePlugin to ES6

### PR DESCRIPTION
**Pull request by shubheksha**
What kind of change does this PR introduce?
refactor, ES5 => ES6

Did you add tests for your changes?
No, all existing tests pass

If relevant, link to documentation update:
N/A

Summary
upgraded NodeHotUpdateChunkTemplatePlugin to ES6

Does this PR introduce a breaking change?
No

### CODE REVIEW

**Comment by naknode** [comment]
NodeChunkTemplatePlugin was converted (and approved) #3792 about an hour ago. 

(Btw, this is a good problem to have! But keep your eye open. Webpack getting many new contributors!)

**Comment by shubheksha** [comment]
@naknode, that was a different file, I think.

**Comment by TheLarkInn** [comment]
Yeah the names get confusing. I'll try to do my best to keep an eye out for dupes.

**Comment by naknode** [comment]
@shubheksha @TheLarkInn  Ahh agast! Thank you. Indeed quite similar.

**Pull request merged**
