### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by singhaditya28**
Updated to-date to reduce redundancy.

**What kind of change does this PR introduce?**

Code refactoring

**Did you add tests for your changes?**

Yes, have doone all the tests

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

Nothing, as such

### CODE REVIEW

**Comment by singhaditya28** [comment]
Updated CLA

**Comment by sokra** [comment]
We don't need these unrelated things in the ignore file

**Comment by singhaditya28** [comment]
@sokra FYIP : All the extensions are created like .log , etc.  are created when using webpack.
So the are not unrelated

**Comment by sokra** [comment]
Where is a .jar or .class file created? This is JavaScript not Java

**Comment by singhaditya28** [comment]
JVM Javascript engine like Rhino or Nashorn often create such files. So, are included, just in case.

PS: Any suggestions are welcomed 👍 😃

**Pull request closed without merging**
