### PR TITLE
Only output color if --color is explicitly specified; default to false.

### PR DESCRIPTION
**Pull request by pavellishin**
Addresses #1824

### CODE REVIEW

**Comment by pavellishin** [comment]
The failing test seems to also fail on master, not related to this PR.

**Comment by sokra** [comment]
Why changing this? Why should colors be off by default?

**Comment by pavellishin** [comment]
> Why changing this? Why should colors be off by default?

Well, both [the documentation](https://github.com/webpack/webpack/blob/master/bin/webpack.js#L23) and [the examples](https://webpack.github.io/docs/tutorials/getting-started/#pretty-output) both seem to very strongly suggest that `--colors` is how you enable colors.

I'd be fine with flipping this around by removing the `--colors` option and adding `--no-color` instead, but regardless, there should be a way to turn color off. 

(One specific reason that I personally ran into is that Jenkins outputs the literal bash color codes. I don't know if this is due to a bug in `supports-color` or not, but it's annoying)

```
19:27:48 Hash: [1m458e077c1dd5ada275eb[22m
19:27:48 Version: webpack [1m1.12.9[22m
19:27:48 Time: [1m14050[22mms
19:27:48        [1mAsset[22m     [1mSize[22m  [1mChunks[22m  [1m[22m           [1mChunk Names[22m
19:27:48     [1m[32mtests.js[39m[22m  3.17 MB       [1m0[22m  [1m[32m[emitted][39m[22m  tests
19:27:48 [1m[32mtests.js.map[39m[22m  3.79 MB       [1m0[22m  [1m[32m[emitted][39m[22m  tests
19:27:48    [0] [1mmulti tests[22m 28 bytes {[1m[33m0[39m[22m}[1m[32m [built][39m[22m
19:27:48  [195] [1m./lib __tests__\/.*\.js$[22m 854 bytes {[1m[33m0[39m[22m}[1m[32m [built][39m[22m
19:27:48     + 864 hidden modules

```

**Comment by sokra** [comment]
https://github.com/chalk/supports-color#info

> It obeys the --color and --no-color CLI flags.

**Comment by pavellishin** [comment]
I still think it's wonky for a project to depend on an internal dependency to handle this, instead of explicitly handling it via config, but updating docs would be fine for now.

Is that something I can do? I didn't see a repo for the documentation...

**Comment by sokra** [comment]
There is a repo (webpack/docs), but there is also a Edit button on the documentation page, which brings you directly to the edit window...

**Pull request closed without merging**
