### PR TITLE
docs(example): update examples template

### PR DESCRIPTION
**Pull request by zhaoshengjun**
**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:
 This should fix issue #3050 . Update examples to 2.1.0-beta.25. 

**What is the current behavior?** (You can also link to an open issue here)
Run `buildAll.js` will fail on some examples.

**What is the new behavior?**
Run `buildAll.js` will success.

**Does this PR introduce a breaking change?**
- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the following... 

* Impact:
* Migration path for existing applications: 
* Github Issue(s) this is regarding:

**Other information**:

### CODE REVIEW

**Comment by TheLarkInn** [comment]
@zhaoshengjun what is the level of effort to make the `buildAll.js` script executable and convert to a npm script like:

`npm run build:examples`

**Comment by zhaoshengjun** [comment]
It will take less than a minute (literally) to add such a script.:smile:

Is this another PR?

**Comment by TheLarkInn** [comment]
I'll accept in the same PR. Just want to make it easier for us to build these from the npm scripts section.

**Comment by zhaoshengjun** [comment]
Done!

**Comment by TheLarkInn** [comment]
Thank you so much.

**Pull request merged**
