### PR TITLE
IgnorePlugin: merge checkResource with checkContext, now single function

### PR DESCRIPTION
**Pull request by iliakan**
As discussed in #8499

### CODE REVIEW

**Comment by ooflorent** [comment]
This is a breaking change since you removed an option. Please do this on `next` branch or keep `checkContext` with a deprecation message.

**Comment by iliakan** [comment]
The previous change of `IgnorePlugin` that introduced functions is quite recent, and it was never documented. 

It was made in 4.x branch.

**Comment by iliakan** [comment]
I'll keep checkContext and add deprecation till v5, no problem.

**Comment by iliakan** [comment]
I returned `checkContext`. Should be no compat issues now.

P.S. Please note, that the previous change of `IgnorePlugin` that introduced functions is quite recent, and it was never documented.

**Comment by sokra** [comment]
Thanks

**Pull request merged**
