### PR TITLE
Remove CircleCI

### PR DESCRIPTION
**Pull request by ooflorent**
Remove CircleCI since it is not used.

**What kind of change does this PR introduce?**

build related change

**Did you add tests for your changes?**

no

**Does this PR introduce a breaking change?**

no

**What needs to be documented once your changes are merged?**

nothing

### CODE REVIEW

**Comment by montogeek** [comment]
Why was it added?

**Comment by evilebottnawi** [comment]
@ooflorent we use `CircleCI` in webpack-contrib, should we avoid using this CI too?

**Comment by ooflorent** [comment]
@evilebottnawi I don't think so. In webpack's codebase this file is not relevant. Elsewhere it's perfectly fine!

**Comment by sokra** [comment]
Thanks

**Pull request merged**
