### PR TITLE
child compiler features

### PR DESCRIPTION
**Pull request by sokra**
**What kind of change does this PR introduce?**
feature

**Did you add tests for your changes?**
not yet (TODO)

**If relevant, link to documentation update:**
not yet (TODO)

**Summary**
allow to apply plugins to child compiler
allow to match on compiler name in rules

see also #4177

**Does this PR introduce a breaking change?**
no

### CODE REVIEW

**Comment by patrikx3** [comment]
hello! when is it going to be work in npm? right now ngtool/webpack is broken...

**Comment by sokra** [comment]
maybe next week

**Comment by patrikx3** [comment]
never mind whenever, but thanks

**Comment by jorawarsingh** [comment]
any updates? thanks

**Comment by patrikx3** [comment]
there was an update, but still same error

**Comment by jorawarsingh** [comment]
# 420

**Comment by patrikx3** [comment]
what is 420? 4/20? April 20th?

**Comment by jorawarsingh** [comment]
sorry it is an open issue in extrect-text-plugin by me. It is marked as bug, i was trying to ref it to that issue.

**Comment by patrikx3** [comment]
ahhh, i was thinking too much smoking :)

**Comment by jorawarsingh** [comment]
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues

**Pull request merged**
