### PR TITLE
rename noEmitOnErrors to emitOnErrors

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
refactor

**Did you add tests for your changes?**
updated snapshot.

**Does this PR introduce a breaking change?**
Maybe yes.

**What needs to be documented once your changes are merged?**
Optimization.noEmitOnErrors is changed to Optimization.emitOnErrors

### CODE REVIEW

**Comment by evilebottnawi** [comment]
We should not change it on webpack side, maybe we should add more meta information for `cli` helper

**Comment by snitin315** [comment]
This was suggested by @sokra, 
Also, with `--optimization-no-emit-on-errors` CLI add `--no-optimization-no-emit-on-errors` (maybe can confuse sometime?), 
for `--optimization-emit-on-errors` -> `--no-optimization-emit-on-errors`

**Comment by snitin315** [comment]
> maybe we should add more meta information for cli helper

Information like?

**Comment by sokra** [comment]
Yes, I suggessed that. Negative flags are a bad practice and we best should avoid them. They are confusing to read (`noSomething: false` or `disableSomething: false`).
But this should be changed with deprecation. I also did a PR: #11193 (Didn't know that you were working on that sorry)

**Comment by snitin315** [comment]
>(Didn't know that you were working on that sorry)

No worries, I will close this one.

**Pull request closed without merging**
