### PR TITLE
README.md: add badge count badge

### PR DESCRIPTION
**Pull request by defunctzombie**
This readme contains an impressive number of badges! You should be proud and show off how many you have by using another badge \o/

### CODE REVIEW

**Comment by sokra** [comment]
awsome, but the badge is broken... server seem to be overloaded...

**Comment by defunctzombie** [comment]
Ok, brought the server back up. Seems like it went to sleep on heroku :( I'll have to see how I can prevent that. The app wasn't actually crashed so unclear to me why it didn't start on heroku.

**Comment by ooflorent** [comment]
Unfortunately the badge does not seem to work.

badges

Including the new one, the badge should count `12`, not `9`.

**Comment by defunctzombie** [comment]
Hm, counts 11 for me because it is looking at the readme on master (which
doesn't have the branch yet)

**Comment by defunctzombie** [comment]
Also one of the badges might be breaking the image analysis (the one with
the logo) I'll have to take a look at that or create a whitelist.

**Comment by sokra** [comment]
Thanks

**Pull request merged**
