### PR TITLE
fix: update environment support for KaiOS browser

### PR DESCRIPTION
**Pull request by steverep**
## Summary

Addresses issues for KaiOS browser mentioned in https://github.com/webpack/webpack/issues/14226#issuecomment-1560486380 by adding version 3.0 support to various environment features.

### <samp>🤖 Generated by Copilot at eb106af</samp>

Add support for `KaiOS` browser to `es` targets. This enables webpack to produce code that works on KaiOS devices.

## Details

KaiOS browser [version 3.0 is based on Gecko 84](https://en.wikipedia.org/wiki/KaiOS#Release_history), so this PR simply adds it wherever it makes sense based on the Firefox support.  Note that for big features like dynamic import, this brings Webpack in line with [CanIUse data](https://caniuse.com/es6-module-dynamic-import).

### <samp>🤖 Generated by Copilot at eb106af</samp>

*  Add support for KaiOS browser to various ES targets in `lib/config/browserslistTargetHandler.js` ([link](https://github.com/webpack/webpack/pull/17395/files?diff=unified&w=0#diff-d571d6fc7f85b101259c6a59a71656bd50b320c4ac41dfc8dda105847ead863fL123-R123), [link](https://github.com/webpack/webpack/pull/17395/files?diff=unified&w=0#diff-d571d6fc7f85b101259c6a59a71656bd50b320c4ac41dfc8dda105847ead863fL190-R190), [link](https://github.com/webpack/webpack/pull/17395/files?diff=unified&w=0#diff-d571d6fc7f85b101259c6a59a71656bd50b320c4ac41dfc8dda105847ead863fL209-R209), [link](https://github.com/webpack/webpack/pull/17395/files?diff=unified&w=0#diff-d571d6fc7f85b101259c6a59a71656bd50b320c4ac41dfc8dda105847ead863fL228-R228), [link](https://github.com/webpack/webpack/pull/17395/files?diff=unified&w=0#diff-d571d6fc7f85b101259c6a59a71656bd50b320c4ac41dfc8dda105847ead863fL249-R249), [link](https://github.com/webpack/webpack/pull/17395/files?diff=unified&w=0#diff-d571d6fc7f85b101259c6a59a71656bd50b320c4ac41dfc8dda105847ead863fL272-R272), [link](https://github.com/webpack/webpack/pull/17395/files?diff=unified&w=0#diff-d571d6fc7f85b101259c6a59a71656bd50b320c4ac41dfc8dda105847ead863fL291-R291))

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Review by alexander-akait — APPROVED** [review]

**Comment by steverep** [comment]
Looks like the snapshots need updating... just haven't learned to do that yet

**Comment by alexander-akait** [comment]
@steverep Do you need a help to update them?

**Comment by steverep** [comment]
Busy with several other things at the moment.  If you could push it that'd be great.

**Comment by alexander-akait** [comment]
@steverep :+1: I will finish

**Comment by steverep** [comment]
Thanks! 🙇🏻‍♂️

**Review by hexiaokang — APPROVED** [review]

**Review by TheLarkInn — APPROVED** [review]

**Comment by TheLarkInn** [comment]
@steverep Congrats on your first contribution to webpack! 🎉

**Pull request merged**
