### PR TITLE
Allow exports of multiple modules for libraries #2809

### PR DESCRIPTION
**Pull request by wictorwilen**
The configuration setting output.exportAllModuels:boolean allows multiple exports, instead of just the last one. For more information see: #2809

### CODE REVIEW

**Comment by TheLarkInn** [comment]
Can you add tests for this? You can use examples in test cases.

**Comment by TheLarkInn** [comment]
And in the examples section with a short write-up.

**Comment by wictorwilen** [comment]
@TheLarkInn - added a sample for the configuration option, as I had hard to understand how your tests are built

**Comment by sokra** [comment]
see issue comment

**Pull request closed without merging**
