### PR TITLE
feat: tree shakable output for module library

### PR DESCRIPTION
**Pull request by fi3ework**
**What kind of change does this PR introduce?**

A prototype PR trying to implement part of #17121. This PR is still rough at present,  any modification suggestions and implementation ideas are welcomed. 🙌🙌🙌.

We're trying to bundle high-quality output NPM libraries with Webpack / Rspack in ESM format. For now, all exported identifiers are defined and re-declarad from `__webpack_exports__`, which makes live-binding and tree-shaking broken when consuming the ESM package (as described in https://github.com/webpack/webpack/issues/2933#issuecomment-874330847), and that's what this PR trying to tackle.

This PR tries to only fix the issue in a limited scene when simultaneously satisfies the following conditions:

1. `output.library.type` is `"module"`: The premise of this problem is ESM library.
2. `optimization.concatenateModules` is `true`: the modules need to be flatten in the same top-level scope.
3. Requires only one chunk in the EntryPoint chunkGroup, only then the concatenatedModule in the top level, which means `optimization.runtimeChunk` is unapplicable.

I created a [gist](https://gist.github.com/fi3ework/108bc3fefa003464315a3773740c0a09/revisions) to demonstrate how this PR changes the output, the file to be bundled are some regular ESM inputs and there's also a CJS input.

The change is quite straightforward: 

1. Adding a bail hook in `lib/optimize/ConcatenatedModule.js` and skip defining properties on `__webpack_exports__` when the hook returns `true`.
2. If defining properties on `__webpack_exports__` is skipped, the final exports name from ConcatenatedModule will be saved in `buildMeta.exportsFinalName` to let `lib/library/ModuleLibraryPlugin.js` consumsing it afterwards.
2. `lib/library/ModuleLibraryPlugin.js` will tap the hook foreamentioned and return `true` to instruct skipping the defining.
3. If the defining is skipping, in `renderStartup` of `lib/library/ModuleLibraryPlugin.js` will try to read `buildMeta.exportsFinalName` from the module and complete the module export with the finalName and `exportInfo.name` directly without leveraging `__webpack_exports__`.

Some unperfect implements and concerns:

1. When `output.library.type` is `module`, skip IIFE wrap in `lib/javascript/JavascriptModulesPlugin.js` directly.
2. Requires only one chunk in EntryPoint chunksGroup, single chunk could meet common usage of library bundling.

**Did you add tests for your changes?**

Yes, consuming a ESM library and the unused exports are tree shaked.

**Does this PR introduce a breaking change?**

Somehow **yes**, that would makes live-binding and tree-shaking available, and also skipped IIFE wrapping in some condition. Maybe we could introduce a new `library.type` if we decided to move forward.

**What needs to be documented once your changes are merged?**

Yes, depends on the final implementation.

### CODE REVIEW

**Comment by alexander-akait** [comment]
> Requires only one chunk in EntryPoint chunksGroup, single chunk could meet common usage of library bundling.

Can you descibe this limitation better and any ideas?

> Somehow yes, that would makes live-binding and tree-shaking available, and also skipped IIFE wrapping in some condition. Maybe we could introduce a new library.type if we decided to move forward.

Technically es modules output is experiment and it is fine to make such changes, but yeah some developers can lead on the current output, maybe `modern-module` (maybe better name? :smile: ) is good idea (only  `import`, `import.meta.url`, live-binding, tree-shaking, etc), and for webpack6 we will use only it

**Comment by fi3ework** [comment]
> Requires only one chunk in EntryPoint chunksGroup, single chunk could meet common usage of library bundling.

This restriction comes from the test case regression. When there are more than one chunk in a chunkGroup (such as using `optimization.runtimeChunk`), it will cause the concatenated module to be wrapped in a closure, which makes it impossible to use only the ESM export syntax directly. The original way of using __webpack_exports__ is fine.

**Comment by alexander-akait** [comment]
@fi3ework Sound good for me, can we convert it in checkboxes/tasks to track progress (also we already solved some cases)

**Comment by fi3ework** [comment]
> @fi3ework Sound good for me, can we convert it in checkboxes/tasks to track progress (also we already solved some cases)

@alexander-akait 

As discussed above, the tree shakable output this PR trying to address is a subset of #17121 target. We're going to add a `modern-module` library type to progressively landing all the feature #17121 lists. Here are the tasks remain for this PR.

- [ ] Type re-export will still be exported in JS when there's no `import type` or `export type` hint. This will break the syntax in the new way while works fine in the old way. I will try to raise another PR to tackle this if it can be resolved is webpack side first, otherwise I will make a workaround in this PR.
    ```js
	// before
	var __webpack_exports__ = {};
	var actions_namespaceObject = {};
	__webpack_require__.r(actions_namespaceObject);
	__webpack_require__.d(__webpack_exports__, {
	  Action: () => (/* reexport */ actions_namespaceObject.Action),
	})
	var __webpack_exports__Action = __webpack_exports__.Action;
	export { __webpack_exports__Action as Action } 
      
	// after
	var actions_namespaceObject = {};
	__webpack_require__.r(actions_namespaceObject);
	export { actions_namespaceObject.Action as Action }
	```
- [ ] Change the modification to `modern-module` type as suggested above.
	- [x] documentation: IMO, we do not need to document the `modern-module` type at this time. We can open the `modern-module` type to user to get more feedback once we have confirmed that the necessary features in #17121 are met. Before that, we can keep developing the `modern-module` type internally.
- [x] IIFE wrapper: we have addressed the `it need to be isolated against other modules in the chunk.` condition which will be raised when a CJS file is included in bundling. The other two conditions as discussed above are out of context for ESM library output so far (but we still can make improve to eliminate them :-P).

That's the TODO remains AFAICR, I'll tackle them in these days. Feel free to add any things I missed. Thanks! 🙌

**Comment by fi3ework** [comment]
Updated the PR and clean the tasks remain. There are some known configurations will break the ESM output, however they won't be used in most actual uses, and I think it's acceptable.

1. When the entry has multiple modules, be like `entry: { ['./lib1.mjs', './lib2.mjs'] }`, the final export of output will use lib2's export while lib1's will be ignored as we're only using the last `inlinedModule` for now (source: https://github.com/webpack/webpack/blob/main/lib/javascript/JavascriptModulesPlugin.js#L923). As discussed above, user rarely use an entry with multiple modules, so I think we could keep ignoring this as we already do. This will break both in the original `module` type and the new `modern-module` type.
2. Using splitChunks / runtimeChunk will break the `inlinedModule` premise, but this is rarely used in library building.

Ready to be reviewed, any suggestions are kindly welcomed.

**Comment by alexander-akait** [comment]
@fi3ework Sorry for small delay, what is current status? Should be make more PRs or refactor something?

**Comment by alexander-akait** [comment]
Also we need to fix tests and rebase

**Comment by alexander-akait** [comment]
Also we we will need update our docs and show different between module and modern-module, but let's do it after it will be merged

**Comment by alexander-akait** [comment]
@fi3ework Can you update description about a new value for other users and our docs and we can merge, thank you

**Comment by alexander-akait** [comment]
> When the entry has multiple modules, be like entry: { ['./lib1.mjs', './lib2.mjs'] }, the final export of output will use lib2's export while lib1's will be ignored as we're only using the last inlinedModule for now (source: https://github.com/webpack/webpack/blob/main/lib/javascript/JavascriptModulesPlugin.js#L923). As discussed above, user rarely use an entry with multiple modules, so I think we could keep ignoring this as we already do. This will break both in the original module type and the new modern-module type.

there is an issue - https://github.com/webpack/webpack/issues/15936, so let's fix it for module and modern-module later

> Using splitChunks / runtimeChunk will break the inlinedModule premise, but this is rarely used in library building.

We have issues for this too

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
If you want help we can focus on https://github.com/webpack/webpack/issues/15936 after merge (PR and help welcome :smile: )

**Comment by alexander-akait** [comment]
Module output is still experimental so we can change this behavior in any time

**Comment by alexander-akait** [comment]
Thank you

**Comment by alexander-akait** [comment]
Any other things are in our roadmap for this?

**Comment by fi3ework** [comment]
@alexander-akait  Sorry for the delayed response, I took a short vacation a while back. Now I'll continue the work.

> Also we we will need update our docs and show different between module and modern-module, but let's do it after it will be merged
> @fi3ework Can you update description about a new value for other users and our docs and we can merge, thank you


I'd prefer to add more test cases that might break in the `modern-module`. After we've addressed known issue, we could update the docs.

By the way, I'm not sure when do we reach the point where we can open it up to users. As per https://github.com/webpack/webpack/issues/17121, there are still a lot of TODOs ("Build output supports tree-shaking" is resolved as of now). Any suggestion for how we release `modern-module` to users?


> there is an issue - https://github.com/webpack/webpack/issues/15936, so let's fix it for module and modern-module later

> If you want help we can focus on https://github.com/webpack/webpack/issues/15936 after merge (PR and help welcome 😄 )

Sure, I could give it a try. IMO, it's not commonly used in building a NPM library (any usage in production we could inspect there?). Are tasks remains on https://github.com/webpack/webpack/issues/17121 in higher priority?

> Using splitChunks / runtimeChunk will break the inlinedModule premise, but this is rarely used in library building.

It's an issue. But might this be in lower priority than tasks remain in https://github.com/webpack/webpack/issues/17121? This is not common when bundling libraries.

**Comment by alexander-akait** [comment]
> Are tasks remains on https://github.com/webpack/webpack/issues/17121 in higher priority?

Yeah, of couse, any of these tasks have higher priority

**Comment by hai-x** [comment]
@fi3ework 

I think we should align the preconditions of `bootstrap.allowInlineStartup` with those of `shouldSkipRenderDefinitions`. (not just with those of IIFE). This means we will skip the export definition of the `concatenated module` when we are certain it will be inlined into the `startup code(with/without IIFE)`. And finally these exports are instead generated during the `renderStartup` phase.

**Comment by alexander-akait** [comment]
@hai-x Did you try to fix it? If yes feel free to send a fix

**Pull request merged**
