### PR TITLE
Pass shareScope through to ContainerPlugin & ContainerReferencePlugin

### PR DESCRIPTION
**Pull request by evantd**
It looks to me like setting `shareScope` for `ModuleFederationPlugin` doesn't work without this change, because `ContainerPlugin` still tries to use `default`.

**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

No, but I didn't see any other tests for `ModuleFederationPlugin` either.

**Does this PR introduce a breaking change?**

I don't think so.

**What needs to be documented once your changes are merged?**

I believe this change makes it more closely match existing documentation.

### CODE REVIEW

**Comment by evantd** [comment]
It looks like failures are sort of common. I saw a pull request that only changed the readme, and it also had 2 failed checks. I don't think that these failures are related to my change. It doesn't look like I can retry them either, at least as far as I can tell.

**Comment by evantd** [comment]
It looks like @sokra and/or @ScriptedAlchemy would be the right people to review this.

**Comment by ScriptedAlchemy** [comment]
Good catch. Assuming both plugins under the hood still call apply(compiler) - which they should. Then I think this change looks good to me and would ensure plugins still work without having to manually apply 3-4 plugins just to use container or container reference independently

**Comment by evantd** [comment]
Yay! Yeah, I'm using an alternate `shareScope` for a work project and this change makes it work for me. I currently just apply a patch to `node_modules` in a `postinstall` script, and I'd love to stop doing that.

**Comment by ScriptedAlchemy** [comment]
@sokra @vankop

**Review by vankop — APPROVED** [review]

**Comment by evantd** [comment]
Since this is approved, should I expect it to be included in the next release?

**Comment by ScriptedAlchemy** [comment]
Can take a little time to move through the webpack org depending on what the change is. This seems small so I imagine it would be a quicker turnaround. 

Nice thing about webpack is you can insall it over npm off a git branch since there's no build - so that might be useful in the interm

**Comment by sokra** [comment]
Thanks

**Comment by evantd** [comment]
I found myself needing to check if my version was new enough, so for anybody else (or future me), this is fixed in 5.74.0.

**Pull request merged**
