### PR TITLE
chore(test): skip failure for global var in macaddress

### PR DESCRIPTION
**Pull request by BrainCrumbz**
**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

See #3173 . Running tests shows a test failed for some `addresses` variable leaking in global scope. 

**What is the new behavior?**

Variable still leaks in global scope, but problem is not flagged.

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the following... 

* Impact:
* Migration path for existing applications: 
* Github Issue(s) this is regarding:

**Other information**:

### CODE REVIEW

**Comment by TheLarkInn** [comment]
Lets wait on [this to be merged](https://github.com/webpack/webpack/pull/3191) and then we can merge this in. Hopefully tomorrow.

**Comment by sokra** [comment]
Could you use the `mocha.opts` file?

**Comment by BrainCrumbz** [comment]
Oh, didn't notice that. Sure!

**Comment by sokra** [comment]
Thanks

**Pull request merged**
