### PR TITLE
Upgrade Jest to 24.3.0

### PR DESCRIPTION
**Pull request by montogeek**
**What kind of change does this PR introduce?**

dependencies

**Did you add tests for your changes?**

existing tests

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

Nothing

### CODE REVIEW

**Comment by montogeek** [comment]
Not sure why this fails:
- It is not a memory issue, there is never an exception a "JavaScript heap out of memory" error.
- forceExit is definitely necessary, but it feels like  a hack :/

**Comment by montogeek** [comment]
Last changed work, so it is related when running a test (basic feature).

**Comment by montogeek** [comment]
Will try installing watchman on Ubuntu 16.04

**Comment by sokra** [comment]
Maybe try to figure out which jest version introduced this problem

**Comment by niieani** [comment]
Could it be the V8 bug I encountered (never terminating process + memory growth)? https://github.com/nodejs/node/issues/29001
I've included a workaround in `jest` 24.9.0 for that bug. Also, most recent node 12 also fixes the problem.

**Comment by sokra** [comment]
It indeed works with the latest jest version.

Thanks for your investment @montogeek

**Comment by montogeek** [comment]
Wow, never thought that possibility! TIL :)

**Pull request closed without merging**
