### PR TITLE
fix eval-source-map typo

### PR DESCRIPTION
**Pull request by happyhappyyay**
There was a typo and I appreciate webpack- 
     was: "This devtool is **not neither** made for production nor for readable output files."
     should be: "This devtool is **neither** made for production nor for readable output files."

**What kind of change does this PR introduce?**
     Typo

**Did you add tests for your changes?**
     No

**Does this PR introduce a breaking change?**
     No

**What needs to be documented once your changes are merged?**
    Nothing

### CODE REVIEW

**Review by snitin315 — COMMENTED** [review]
Please Accept CLA.

**Comment by happyhappyyay** [comment]
I'm not sure how to accept the CLA. I signed it and waited a day or two, but it still says pending for the CLA. Thank you for your patience.

**Comment by snitin315** [comment]
Try closing and repoening PR.

**Review by sokra — CHANGES_REQUESTED** [review]
:+1:

To fix the CI problem run `yarn jest StatsTestCases -u`. This updates the snapshots for the changed bundle sizes

**Comment by sokra** [comment]
Thanks

**Pull request merged**
