### PR TITLE
Fix typos

### LINKED ISSUE #10546: Fix Typo
# Bug report

**What is the current behavior?**
Currently there is a typo in the code name : preferedOrder in the file ./lib/stats/DefaultStatsPrintPlugin.js

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The typo is removed 

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

### PR DESCRIPTION
**Pull request by shivaylamba**
Fixed typo.

**What kind of change does this PR introduce?**
Fixes #10546 

**Did you add tests for your changes?**
NA

**Does this PR introduce a breaking change?**
NO

**What needs to be documented once your changes are merged?**
NA

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Please accept CLA

**Comment by shivaylamba** [comment]
I have already signed it @evilebottnawi

**Comment by shivaylamba** [comment]
It was already signed, not sure what took it so long to approve.

**Comment by sokra** [comment]
Thanis

**Pull request merged**
