### PR TITLE
AssignLibraryPlugin: don't include library name in the accessor when target is commonjs2 / commonjs-module

### LINKED ISSUE #11688: Exports are placed inside a namespace when libraryTarget is commonjs2
# Bug report

**What is the current behavior?**

If `output.library` is specified and `output.libraryTarget` is `commonjs2`, library exports are placed inside a namespace (`output.library`).

If `output.library` is omitted, the exports are as expected, but the paths in source maps are incorrect (paths do not include library name).

**If the current behavior is a bug, please provide the steps to reproduce.**

Reproduction repository: https://github.com/dkamyshov/webpack-5-lib-reproduction

See https://github.com/dkamyshov/webpack-5-lib-reproduction/blob/master/README.md for details.

**What is the expected behavior?**

Same as with webpack@^4 - no namespace and correct paths in source maps.

**Other relevant information:**
webpack version:  5.1.0
Node.js version: 12.8.4
Operating System: Ubuntu 20.04.1 LTS
Additional tools: yarn v1.22.5

### PR DESCRIPTION
**Pull request by dkamyshov**
Hi! Thanks for the great package.

I'm a library author and webpack@5 breaks my library because (unlike in webpack@4) the library exports are placed inside a namespace when target is `commonjs2`.

**What kind of change does this PR introduce?**

This PR fixes #11688.

**Did you add tests for your changes?**

Yes.

**Does this PR introduce a breaking change?**

No.

**What needs to be documented once your changes are merged?**

Nothing (presumably).

### CODE REVIEW

**Comment by dkamyshov** [comment]
Regarding failed (or pending) checks:

1. The jsf-clabot reports that I didn't sign the CLA while in reality I did sign it, see: https://cla.js.foundation/webpack/webpack?pullRequest=11942
2. For some reason, coverage in an unrelated file changed. This has nothing to do with my patch. How do I fix it?
3. `Travis CI - Pull Request` is still pending. It seems Travis stopped building PRs ~5 days ago: https://travis-ci.com/github/webpack/webpack/pull_requests

**Comment by evilebottnawi** [comment]
CLA fixed, do not look at travis CI

**Comment by dkamyshov** [comment]
The merge conflict is resolved.

**Comment by sokra** [comment]
see https://github.com/webpack/webpack/issues/11688#issuecomment-762331226

**Pull request closed without merging**
