### PR TITLE
add jsonp-script-alternative

### PR DESCRIPTION
**Pull request by stegano**
**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x]  Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
dynamic load(require.ensure) is not working on Android 2.1 stock browser

**What is the new behavior?**
alternate jsonp on android 2.x stock browser

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the following... 

* Impact:
* Migration path for existing applications: 
* Github Issue(s) this is regarding:

**Other information**:
jsonp is not supported on Android 2.1 stock browser
THX :)

### CODE REVIEW

**Comment by sokra** [comment]
What's the reasons for this change? Doesn't JSONP work on android browser?

**Comment by stegano** [comment]
@sokra 
Hi, I tried JSONP on Android 2.3 below version but it doesn't work,  So i need an alternative.. :(

**Comment by sokra** [comment]
Is it anywhere documented that Android 2.3 doesn't support JSONP? If this is true, I'm sure other people have this problem too.

JSONP is a very basic web concept, that's why I'm wondering that it's not supported.

**Comment by stegano** [comment]
@sokra 
I checked it again and you're right, it's my mistake. :(
Thanks for letting me know.

**Pull request closed without merging**
