### PR TITLE
fix: use runtime globals in shared plugin

### PR DESCRIPTION
**Pull request by animecyc**
**What kind of change does this PR introduce?**

- Fixes a bug that caused HMR to fail when using Module Federation (`__webpack_modules__` is not defined).
- Fixes: #12830

**Did you add tests for your changes?**

I didn't, it would be great if some direction could be given as to where a test for something like this would go. Assuming `hotCases`? 

**Does this PR introduce a breaking change?**

It doesn't introduce breaking changes.

**What needs to be documented once your changes are merged?**

This is an internals change, I don't believe this warrants a documentation change.

### CODE REVIEW

**Review by sokra — CHANGES_REQUESTED** [review]
Changes look good, but we definitely need a test case for the bug

**Comment by sokra** [comment]
and also make sure to sign the [CLA](https://cla.js.foundation/webpack/webpack?pullRequest=12831)

**Comment by sokra** [comment]
Yep, a test case in `test/hotCases` should make it. To trigger the behavior you can add a shared module in a HMR update. Change an existing module to reference the a new shared module.

To trigger both code paths you need on shared module that it loaded with `import ... from "shared1"` and another one that is loaded with `import("shared2")`.

**Comment by animecyc** [comment]
> Yep, a test case in `test/hotCases` should make it. To trigger the behavior you can add a shared module in a HMR update. Change an existing module to reference the a new shared module.
> 
> To trigger both code paths you need on shared module that it loaded with `import ... from "shared1"` and another one that is loaded with `import("shared2")`.

**Review by sokra — APPROVED** [review]

**Comment by sokra** [comment]
Thanks

**Pull request merged**
