### PR TITLE
ci: add Node.js v23

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
CI

Run tests on Node.js v23

**Did you add tests for your changes?**
NA

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
Nothing

### CODE REVIEW

**Comment by snitin315** [comment]
Looking into`integration (ubuntu-latest, 23.x, b)`

**Comment by alexander-akait** [comment]
@snitin315 Looks like regression in `Node.js`, - `fs.readFile("/", (err) => {})`, before `err.code === "EISDIR"`, now no `callback` call and `err.code === "ERR_FS_EISDIR"`

**Comment by alexander-akait** [comment]
Ref: https://github.com/nodejs/node/issues/55609

**Comment by evenstensberg** [comment]
Are we still blocked from the node regression? What does it need to fix this?

**Comment by alexander-akait** [comment]
Close in favor - https://github.com/webpack/webpack/pull/18972

**Review by Magkoooh — APPROVED** [review]

**Pull request closed without merging**
