### PR TITLE
upgraded node-libs-browser

### PR DESCRIPTION
**Pull request by orlandodemauro**
fix issues:

https://github.com/webpack/webpack/issues/2678
https://github.com/mqttjs/MQTT.js/issues/445

### CODE REVIEW

**Comment by bebraw** [comment]
You could fix the tests by adding a loader definition like at https://github.com/webpack/webpack/pull/1930 . That was actually merged to webpack 2.

**Comment by orlandodemauro** [comment]
@bebraw the test is passing locally with node 5.6

**Comment by bebraw** [comment]
Cool. Let's wait what @sokra has to say.

**Comment by orlandodemauro** [comment]
@sokra sorry to bother :) any feedback? thanks a milion

**Comment by orlandodemauro** [comment]
@bebraw @sokra hi guys any feedback? thanks

**Comment by bebraw** [comment]
@orlandodemauro It looks good to me, but it's up to @sokra to make the final call on this one. 👍

**Comment by sokra** [comment]
node-libs-browser 1.0.0 contains a breaking change, this would mean a breaking change for webpack. It's on version ^1.0.0 in webpack 2.

So we need to create a node-libs-browser 0.5.4 with only buffer upgraded...

**Comment by orlandodemauro** [comment]
@sokra thanks I created a PR in node-libs-browser

**Pull request closed without merging**
