### PR TITLE
fix: Chunks is not iterable when using source maps with ProfilingPlugin

### LINKED ISSUE #6779: Chunks is not iterable when using source maps with ProfilingPlugin
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Webpack doesn't work when we are using one of this devtools with ProfilingPlugin

- cheap-module-source-map
- cheap-source-map
- hidden-source-map
- inline-source-map
- nosources-source-map
- source-map

It throw error:

```js
TypeError: chunks is not iterable
    at compilation.hooks.afterOptimizeChunkAssets.tap (/Users/v7rulnik/projects/opensource/huy/node_modules/webpack/lib/SourceMapDevToolPlugin.js:108:26)
    at args (/Users/v7rulnik/projects/opensource/huy/node_modules/webpack/lib/debug/ProfilingPlugin.js:383:10)
    at SyncHook.eval (<anonymous>:9:1)
    at SyncHook.lazyCompileHook [as _call] (/Users/v7rulnik/projects/opensource/huy/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/v7rulnik/projects/opensource/huy/node_modules/webpack/lib/Compilation.js:947:42)
    at AsyncSeriesHook.eval [as callAsync] (<anonymous>:8:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/v7rulnik/projects/opensource/huy/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.additionalAssets.callAsync.err (/Users/v7rulnik/projects/opensource/huy/node_modules/webpack/lib/Compilation.js:943:36)
    at AsyncSeriesHook.eval [as callAsync] (<anonymous>:8:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/v7rulnik/projects/opensource/huy/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeTree.callAsync.err (/Users/v7rulnik/projects/opensource/huy/node_modules/webpack/lib/Compilation.js:939:32)
    at AsyncSeriesHook.eval [as callAsync] (<anonymous>:8:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/v7rulnik/projects/opensource/huy/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/Users/v7rulnik/projects/opensource/huy/node_modules/webpack/lib/Compilation.js:881:27)
    at hooks.make.callAsync.err (/Users/v7rulnik/projects/opensource/huy/node_modules/webpack/lib/Compiler.js:464:17)
    at _err0 (<anonymous>:13:1)
    at _addModuleChain (/Users/v7rulnik/projects/opensource/huy/node_modules/webpack/lib/Compilation.js:749:12)
    at processModuleDependencies.err (/Users/v7rulnik/projects/opensource/huy/node_modules/webpack/lib/Compilation.js:688:9)
    at process._tickCallback (internal/process/next_tick.js:150:11)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
var path = require("path");
const webpack = require('webpack')

module.exports = [
	"cheap-module-source-map",
	"cheap-source-map",
	"hidden-source-map",
	"inline-source-map",
	"nosources-source-map",
	"source-map"
].map(devtool => {
	console.log(devtool)
	return {
		mode: "development",
		entry: {
			bundle: "coffee-loader!./example.coffee"
		},
		output: {
			path: path.join(__dirname, "dist"),
			filename: `./[name]-${devtool}.js`
		},
		plugins: [
			new webpack.debug.ProfilingPlugin(),
		],
		devtool,
		optimization: {
			runtimeChunk: true
		}
	}
})
```

**What is the expected behavior?**
It should not throw error and it should generate bundle and file for profiler.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

- webpack@4.1.1
- webpack-clI@2.0.12
- node@9.4.0
- macOS@10.12.6

### PR DESCRIPTION
**Pull request by byzyk**
**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

yes, for `configCases`

**If relevant, link to documentation update:**
N/A

**Summary**

Fixes #6779

**Does this PR introduce a breaking change?**

no

**Other information**

### CODE REVIEW

**Comment by byzyk** [comment]
The problem is that in `SourceMapDevToolPlugin` when used with `ProfilingPlugin`, `chunks` are being passed instead of `context` inside `compilation.hooks.afterOptimizeChunkAssets.tap` callback for some reason. So the `context = chunks, chunks = undefined`, thus throws `not iterable`.

I tried to fix it by defaulting chunks to context when no context is specified but it feels like a dirty fix to me and something for sure is not working smoothly. Any thoughts on this?

cc @sokra @TheLarkInn

**Comment by sokra** [comment]
That looks like a bug in webpack/tapable...

**Comment by sokra** [comment]
Could you add a test?

**Comment by byzyk** [comment]
@sokra added a test case for `configCases/source-map`. Passing well with my dirty hack but I still haven't figured out why it happens.

**Comment by sokra** [comment]
Thanks for the test case.

I removed your hack and fixed the bug, which was in the implementation of the ProfilingPlugin. I was not a bug in tapable.

**Pull request merged**
