### PR TITLE
fix: do not import non javascript chunks

### PR DESCRIPTION
**Pull request by snitin315**
**What kind of change does this PR introduce?**
bug-fix.

Fixes https://github.com/webpack/webpack/issues/16040

**Did you add tests for your changes?**
Don't know how to add one.

**Does this PR introduce a breaking change?**
No.

**What needs to be documented once your changes are merged?**
Nothing.

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Looks good :+1:, can you just copy paste test from here https://github.com/hronro/webpack-chunk-issue, if you need help with test ask me

**Comment by snitin315** [comment]
I'll add one 👍🏻, I was facing issues running tests locally with node v18/v19(https://github.com/webpack/webpack/pull/16813). Working with node v17 👍🏻

**Comment by snitin315** [comment]
Added a test case.

cc @TheLarkInn @alexander-akait

**Review by TheLarkInn — APPROVED** [review]
LGTM

**Pull request merged**
