### PR TITLE
Accept `undefined` and `null` in plugins

### PR DESCRIPTION
**Pull request by silverwind**
### <samp>🤖 Generated by Copilot at 792de0e</samp>

No summary available (An error occurred while summarizing these changes: Gave up after 3 retries: Failed to read error response)

### <samp>🤖 Generated by Copilot at 792de0e</samp>

No walkthrough available (An error occurred while summarizing these changes: Gave up after 3 retries: Failed to read error response)

### CODE REVIEW

**Comment by silverwind** [comment]
Too much effort for me to get this working and the CLA is too scary, so I'll not chase this further, but if someone wants to pick it up, feel free.

**Comment by alexander-akait** [comment]
@silverwind What is the problem with CLI? It is a standard process for javascript foundation

**Comment by alexander-akait** [comment]
Just want to know, maybe we can improve it

**Comment by silverwind** [comment]
For one, I don't feel like handing out my postal address, It feels like a privacy intrusion. I prefer to contribute anonymously but that is certainly not possible here.

**Comment by alexander-akait** [comment]
@silverwind I appreciate that you want to keep your privacy.

The main problem for us is that we can only accept the code on the condition that no one claims rights to it. And an email is required in order to link your commit and that you have agreed. If we remove this, then I see no other mechanism for us to make sure that you are you agreed to use your code.

But perhaps theoretically we can implement one time agreement into commit body. Thus, you do not have to go through such a procedure, but only write the required code (maybe one time generated for a PR) in the commit body.

I do not promise that I can solve this problem, because these are legal subtleties, but I will consult and try to find out how we can improve it.

**Comment by TheLarkInn** [comment]
@silverwind we understand and appreciate your concern and I have brought this up with the OpenJS Foundation who owns our CLA process. As @alexander-akait I can't promise anything yet except that we will take a concernted effort into investigating it.

**Comment by silverwind** [comment]
Thanks. I'm happy to give an e-mail address, not so happy to give out a real name, and anything more than those two is a no-go for me.

**Comment by TheLarkInn** [comment]
@silverwind I've had a few discussions and have also formally opened a GitHub issue/agenda (https://github.com/openjs-foundation/cross-project-council/issues/1088) item for the next OpenJSF Cross Project Council session. Looks like we can find a middle ground here but takes a bit of time/process just to iron it out. Appreciate the patience and understanding.

**Comment by TheLarkInn** [comment]
@silverwind I'm adding you to our release note recongitions today as you transitively contributed to this feature landing today 🎉  congrats and thaank you so much! I'll continue to follow up with our discussion on CLA's so I hope we see your contributions in the future once we've resolved it 🙇

**Comment by silverwind** [comment]
Thanks. Yeah, once the CLA issue is resolved/simplified, I could have a look at fixing https://github.com/webpack/webpack-dev-server/issues/4630 😉.

**Pull request closed without merging**
