### PR TITLE
feat: introduce a new syntax for worklets - `*context.audioWorklet.addModule()`

### PR DESCRIPTION
**Pull request by alexander-akait**
Part of https://github.com/webpack/webpack/issues/11543, currently you can't use 
```js
myAudioContext.audioWorklet.addModule('./audio-worklet.js')
```

But now you can use:
```js
module.exports = {
	output: {
		filename: "[name].js"
	},
	target: "web",
	module: {
		rules: [
			{
				test: /\.[cm]?js$/,
				parser: {
					worker: [
						"*context.audioWorklet.addModule()",
						"*audioWorklet.addModule()",
						// *addModule() is not valid syntax
						"..."
					]
				}
			}
		]
	}
};
```

Using `*` allow to build worklet from a variable (i.e. `*context` means take `context` variable and check members after it, it **works** only on start of line, i.e. `context.foo*.addModule()` doesn't supported), i.e.

```js
const context = new AudioContext();
context.audioWorklet.addModule(new URL("./worklet.js", import.meta.url));

let audioWorklet = (new AudioContext()).audioWorklet;
audioWorklet.addModule(new URL("./worklet.js", import.meta.url));
```

Note - you can use it not only for worklets, for any custom syntax with call and member expressions

### <samp>🤖 Generated by Copilot at 20c6900</samp>

This pull request adds a new feature to the `WorkerPlugin` that allows using a special syntax for worker specifiers that match a worklet API. It also adds several test files and helpers to verify the functionality and compatibility of the feature.

### <samp>🤖 Generated by Copilot at 20c6900</samp>

*  Introduce `WorkerSpecifierTag` symbol to mark variables as worker specifiers ([link](https://github.com/webpack/webpack/pull/17212/files?diff=unified&w=0#diff-7f82993596b7ab3f7c6041783c839bb008d4929cf454d47b0ccc4df065da59fdR44-R45))
*  Handle new syntax for worker specifiers with pattern and member chain ([link](https://github.com/webpack/webpack/pull/17212/files?diff=unified&w=0#diff-7f82993596b7ab3f7c6041783c839bb008d4929cf454d47b0ccc4df065da59fdL381-R405))
*  Add test cases for new worklet syntax using pseudo-worklet API ([link](https://github.com/webpack/webpack/pull/17212/files?diff=unified&w=0#diff-a3726a140ebd88f464d0d87a12dce3f3df073ff95cb70df3b5fafabe65f769b1R1-R178), [link](https://github.com/webpack/webpack/pull/17212/files?diff=unified&w=0#diff-ac03d2cadd44cdab28074b6896403af65d20dab9cd0c7a48e72bc05ffbd24318R1-R4), [link](https://github.com/webpack/webpack/pull/17212/files?diff=unified&w=0#diff-004812fd81a24156f2807312b80c5ef36bbe1b7837630636426a7840723e5e8fR1), [link](https://github.com/webpack/webpack/pull/17212/files?diff=unified&w=0#diff-4d4eca7a4b94df99a4e8562fcdb2c0409d0506a2cf377c4eced345d7a1e78addR1))
*  Add module file for dynamic import inside worklet ([link](https://github.com/webpack/webpack/pull/17212/files?diff=unified&w=0#diff-f9a9674efd643906a2a65c422cc618319e78c2575bae61ee78d79cc297073f01R1-R3))
*  Add test configuration file with custom module scope and fake worklet implementations ([link](https://github.com/webpack/webpack/pull/17212/files?diff=unified&w=0#diff-8e3773767f496592320989a23a99a9e3d7f962a250db848293b29663c494d373R1-R33))
*  Add test filter file to check worker support ([link](https://github.com/webpack/webpack/pull/17212/files?diff=unified&w=0#diff-3bc710227632cede47c97611c92ac0fe0a1273772a92b453b6b90cfe195ebfe2R1-R5))
*  Add webpack configuration file with output and parser options ([link](https://github.com/webpack/webpack/pull/17212/files?diff=unified&w=0#diff-1d898f016024ab8de7b4084c6f4f30220fbdeec651476c8ea9d841a63fb8ae96R1-R26))
*  Add `url` property to `Worker` class in `createFakeWorker` helper ([link](https://github.com/webpack/webpack/pull/17212/files?diff=unified&w=0#diff-38feca23e5572bd7f9163ee93af22070f12cc7e844be58201a793fac6609e5e0R9))

### CODE REVIEW

**Review by TheLarkInn — APPROVED** [review]

**Comment by alexander-akait** [comment]
Fixed broken test on v12

**Comment by lyswhut** [comment]
Adding these rules breaks the handling of web workers:
```js
      {
        test: /\.tsx?$/,
        exclude: /node_modules/,
        use: {
          loader: 'ts-loader',
        },
        parser: {
          worker: [
            '*audioContext.audioWorklet.addModule()',
          ],
        },
      },
```

**Comment by alexander-akait** [comment]
@lyswhut Please use:
```
parser: {
  worker: [
    '*audioContext.audioWorklet.addModule()',
     '...'
  ],
},
```     

It means you will extend default options   :
```
const DEFAULT_SYNTAX = [
	"Worker",
	"SharedWorker",
	"navigator.serviceWorker.register()",
	"Worker from worker_threads"
];
```

**Comment by lyswhut** [comment]
> You can use `...` in any array and it will extend default options with your own

Thanks, it work!
Sorry, I thought `...` was just an example of more rules 🤣

**Comment by v0rs4** [comment]
@alexander-akait Great work! 🙏 

Quick question: my worklet is written in TS and when I'm trying to import it 

`await audioContext.audioWorklet.addModule(new URL("./worklet.ts", import.meta.url));`

I get this error

`Error: TypeScript emitted no output`

I'm  using nextjs 13, and it works for regular javascript but not for typescript

Here's my `next.config.js`

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: (config, context) => {
    if (!context.isServer) {
      console.log(config.output.filename);

      return {
        ...config,
        module: {
          ...config.module,
          rules: [
            ...config.module.rules,
            {
              test: /\.tsx?$/,
              use: {
                loader: 'ts-loader',
              },
              parser: {
                worker: [
                  "*context.audioWorklet.addModule()",
                  "*audioWorklet.addModule()",
                  "..."
                ]
              }
            }
          ]
        }
      }
    }

    return config;
  }
}

module.exports = nextConfig;
```

**Comment by v0rs4** [comment]
I have another question too:

Is it possible to import/require 3rd party libraries inside `worklet` file?

**Pull request merged**
