### PR TITLE
fix deterministicGrouping looping over group.nodes's negative indexes

### LINKED ISSUE #12487: SplitChunksPlugin crash when optimization.splitChunks.maxSize is set
**Bug Report**

**What is the current behavior?**
Webpack crashes when splitting my project in 5.17.0 when a maxSize is set. 

This behavior varies depending on the packages being splits, as well as the maxSize and minSize that are set. I'm able to consistently avoid problems by setting minSize to 0. The larger I set it, the more likely it is for a problem to occur.

I get the following stack trace when it fails:

```
SplitChunksPlugin(node:22720) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'size' of undefined
    at module.exports (C:\_code\Intranet\trunk\Web\node_modules\webpack\lib\util\deterministicGrouping.js:339:44)
    at C:\_code\Intranet\trunk\Web\node_modules\webpack\lib\optimize\SplitChunksPlugin.js:1589:23
    at Hook.eval [as call] (eval at create (C:\_code\Intranet\trunk\Web\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:39:16)
    at Hook.CALL_DELEGATE [as _call] (C:\_code\Intranet\trunk\Web\node_modules\webpack\node_modules\tapable\lib\Hook.js:14:14)
    at Compilation.seal (C:\_code\Intranet\trunk\Web\node_modules\webpack\lib\Compilation.js:2101:36)
    at C:\_code\Intranet\trunk\Web\node_modules\webpack\lib\Compiler.js:1056:20
    at C:\_code\Intranet\trunk\Web\node_modules\webpack\lib\Compilation.js:1925:4
    at _next2 (eval at create (C:\_code\Intranet\trunk\Web\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:35:1)
    at eval (eval at create (C:\_code\Intranet\trunk\Web\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:71:1)
    at C:\_code\Intranet\trunk\Web\node_modules\webpack\lib\FlagDependencyExportsPlugin.js:332:11
(node:22720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Looking at the code where it crashes, I see this:

```
let left = 1;
let leftSize = Object.create(null);
addSizeTo(leftSize, group.nodes[0].size);
while (isTooSmall(leftSize, minSize)) {
    addSizeTo(leftSize, group.nodes[left].size); //this is the crash, left has exceeded the length of the nodes list.
    left++;
}
```

I don't see how exactly this is supposed to work, as there doesn't appear to be anything stopping left from incrementing up past the length of the available nodes. This code is what made me realize setting minSize lower would workaround the issue, though, as setting it small enough simply ensures the while loop is never entered.

**If the current behavior is a bug, please provide the steps to reproduce.**
On my codebase, setting maxSize smaller and minSize larger seems to be more likely to cause the bug.

```
optimization: {
    chunks: 'all', 
    maxAsyncRequests: Infinity,
    maxInitialRequests: Infinity,
    maxSize: 100000,
    //minSize: 1,
    cacheGroups: {
        sharedcomponents: {
            test: /[\\/]_shared[\\/]src/,
            name: 'sharedcomponents',
            reuseExistingChunk: true
        },
	vendors: {
            test: /[\\/]node_modules[\\/]/,
            name: 'vendors',
	    reuseExistingChunk: true
        }
    }
}
```

**What is the expected behavior?**
Webpack should generate chunks with an appropriate maxSize if possible, and anything smaller is acceptable as well. Having a chunk smaller than the minSize shouldn't crash.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Webpack 5.17.0. Also had the same issue on 5.14.0. Haven't tested any older versions.
Node 12.13.0

### PR DESCRIPTION
**Pull request by wojtekmaj**
Please see https://github.com/webpack/webpack/issues/12487#issuecomment-792747387 for explanation.

**What kind of change does this PR introduce?**

Bugfix, fixes #12487

This may, I guess, cause build to produce files smaller than `minSize`, but that's better than crashing in such cases.

**Did you add tests for your changes?**

Nope, I don't know this repo well enough to create them. Happy to work with anyone willing to come up with some.

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

Nothing

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Can you add small test?

**Comment by wojtekmaj** [comment]
Sorry, I don't know this repo well enough to create it.

**Comment by alexander-akait** [comment]
Can you provide steps how we can reproduce it so I provide how to write test

**Comment by wojtekmaj** [comment]
See this comment: https://github.com/webpack/webpack/issues/12487#issuecomment-792747387

However, I was not able to reproduce this with 100% success rate. Sometimes the build was crashing, I checked out another commit, built with success, came back to the original commit and built was a success again. I don't know if creating a repo with 100% repro would be possible.

**Comment by sokra** [comment]
> However, I was not able to reproduce this with 100% success rate. Sometimes the build was crashing, I checked out another commit, built with success, came back to the original commit and built was a success again. I don't know if creating a repo with 100% repro would be possible.

Ok I looked at the code and it seem like you hit an edge case in the edge case mitigation logic^^

So before the group splitting logic there is some extra logic that tries to remove all problematic nodes in a way that all later processed groups are always larger that `minSize`. So if this would work, you wouldn't be able to run into this problem. But I guess it's broken. I have a guess, but this could indeed be a bit complex to reproduce...

**Comment by sokra** [comment]
Seems like there are more potential problems in this code.

Since we added multiple size types, some assumptions in the algorithm fall short. e. g. if we have a list of modules, which is over the minSize, we assumed that adding another module can't break the minSize. But this is now the case.

**Comment by sokra** [comment]
I tried to fix some of the problems. Maybe you could try this PR on your project again?

**Comment by wojtekmaj** [comment]
Hi @sokra, thanks for this and sorry to keep you waiting.

I have just tested that in my repository:
* **Crashed** with currently shipped `deterministicGrouping.js`
* **Did not crash** with my version of `deterministicGrouping.js`
* **Did not crash** with your version of `deterministicGrouping.js`

**Review by sokra — APPROVED** [review]

**Comment by sokra** [comment]
Ok I'll merge that. But only because I also have no idea how to write a test for that. It seem to be covered a bit by the Stats snapshot that seem to be fixed by that.

**Comment by sokra** [comment]
Thanks for investigating and testing

**Pull request merged**
