### PR TITLE
Added support for --quiet and --silent flags

### LINKED ISSUE #490: Support --quiet on the command-line
Currently, `webpack --quiet` ignores the files passed, while still outputting to the console:

```
Hash: 6dbc5ab44333d067d673
Version: webpack 1.4.0-beta6
Time: 11ms
```

It would be nice to have the `--quiet` option work as expected, i.e. silence all non-error messages.

### PR DESCRIPTION
**Pull request by mattsoltani**
Added two flags to work like npm. Fixes #490
```
--quiet will only output warnings and errors.
--silent will suppress all output.
```

Also alphabetized the flags when using help to give a better overview of the options.

### CODE REVIEW

**Comment by bebraw** [comment]
@mattsoltani Do you want to re-open this?

**Comment by mattsoltani** [comment]
@bebraw It didn't seem like a needed feature at the time. What are your thoughts on this?

**Comment by bebraw** [comment]
@mattsoltani Just curious due to https://github.com/webpack/webpack/issues/490 . @sokra has the final say on this.

**Comment by LegitTalon** [comment]
@mattsoltani What concludes this is an unneeded feature? Is there an alternative way to tell webpack to only print errors?

**Comment by LegitTalon** [comment]
Why is this closed please halp I can't look at another `[886] ./js/test/mock/sonoisyplzhalp.js` without going crazy :see_no_evil:

**Comment by dodekeract** [comment]
Workaround: `webpack arguments >> /dev/null`

**Pull request closed without merging**
