### PR TITLE
Feat beautifier

### PR DESCRIPTION
**Pull request by thaiat**
**Motivation**
during my first PR to this repo i struggled with the tab convention over space, and had to re push a few times. 
the command `npm run lint` should have told me what was wrong before i pushed to the repo...

**Changes**
1. Using better rules in `.eslintrc` to make it obvious that code adhere to the repo
2. Add a `.jsbeautyrc` file following code style so it is easier to reformat the code when contributing (using js-beautify or any code editor plugin built on top of it)
3. Fix a few of the most obvious lint errors and warnings

### CODE REVIEW

**Comment by hkal** [comment]
An [editorconfig](http://editorconfig.org/) exists in the repository, which addresses code style. The fact that you ran into this issue is a documentation problem, in my opinion. I'm not sure if `jsbeautify` is useful, but the `.eslintrc` changes are good :+1:

**Comment by thaiat** [comment]
@hkal, the editorconfig is not honored by every editor, that's why i think a jsbeautify does not hurt. that way you are not dependent on the editor but more on your build process or global commands

if you prefer i remove it though i don't have any objection

**Comment by sokra** [comment]
Could you add the jsbeatify script to the package.json scripts?

**Comment by thaiat** [comment]
@sokra not sure what you mean by that...

**Comment by sokra** [comment]
Something like `npm run beatify`, which should beatify the code.

**Comment by sokra** [comment]
Thanks

**Comment by sokra** [comment]
I hope I'm able to merge this with the webpack-2 branch...

**Comment by sokra** [comment]
I improved the PR a bit: https://github.com/webpack/webpack/commit/e68108a43261cf6639c509d34fbe4e03c1d62788

It now checks for beauty files on CI and npm test

**Pull request merged**
