### PR TITLE
also run node.js 6 CI in worker pool

### PR DESCRIPTION
**Pull request by sokra**
**What kind of change does this PR introduce?**
CI

**Summary**

**Does this PR introduce a breaking change?**
no

**Other information**

### CODE REVIEW

**Comment by sokra** [comment]
@niieani This seem to work and is faster. What was the reason to not do that?

**Comment by ooflorent** [comment]
@sokra There are more random errors on node 6 when using parallel tests because of resource limit on Travis/Appveyor.

**Comment by sokra** [comment]
Ah I see let me test that

**Comment by sokra** [comment]
Any plan to fix that in jest or do you want to wait until node.js is dead?

**Comment by niieani** [comment]
No idea what was the issue. It just hangs. No idea how to debug it either...
Maybe a bug in `jest`, maybe in `node`.

**Comment by niieani** [comment]
Oddly, all passed now. Maybe I was running into that in combination with something else? Maybe when there were actual errors it was hanging? I don't remember exactly, just know it was hard to debug.

**Comment by sokra** [comment]
Ironically node.js 10 is hanging and node.js 6 worked fine...

**Comment by niieani** [comment]
# 😕

**Comment by niieani** [comment]
(copied from slack)

Just spoke with @SimenB from the `jest` team, he suggested adding the `--forceExit` as a workaround. For debugging it, he also mentioned as worth trying to add https://github.com/mafintosh/why-is-node-running and see what might be causing the process to be hanging after the tests end.

**Comment by sokra** [comment]
node.js 8 is also hanging here: https://ci.appveyor.com/project/sokra/webpack/build/1.0.7520/job/p6bqee96aelymyhv

**Comment by sokra** [comment]
It seem to be a general jest problem not bound to node.js version

**Comment by sokra** [comment]
For this PR I'm going to merge it since the problem is independent of it.

**Comment by niieani** [comment]
@sokra it was hanging on that Node 8 one you cited because of an internal error though:

```
(node:1060) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'spies' of undefined
(node:1060) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

This is why I added the `asyncSuite.disabled = true`, but I'll have to investigate and fix in `jest` if possible.

**Pull request merged**
