### PR TITLE
add typings for the resolveData parameter

### PR DESCRIPTION
**Pull request by chenxsan**
**What kind of change does this PR introduce?**

1. rename `result` to `resolveData` to keep consistency, e.g., the `IgnorePlugin` tapping the `hooks.beforeResolve` uses `resolveData` for the parameter per https://github.com/webpack/webpack/blob/main/lib/IgnorePlugin.js#L42
2. Include the typing for `resolveData` which can be helpful for anyone reading the source code.

**Did you add tests for your changes?**

Internal changes, so it won't break anything as far as I see.

**Does this PR introduce a breaking change?**

Nope, just small internal changes.

**What needs to be documented once your changes are merged?**

Nothing.

### CODE REVIEW

**Review by sokra — CHANGES_REQUESTED** [review]
Why doesn't it have typings for you without that change?
For me it will just infer the types from the hook.

**Comment by chenxsan** [comment]
> Why doesn't it have typings for you without that change?
> For me it will just infer the types from the hook.

Indeed, I just noticed that VSCode can infer the typing, thanks for the heads-up!

What about the `result` -> `resolveData` change? I noticed that most of the time, `result` was used along with `err` in the form of `(err, result) => {}` callback. In the `NormalModuleReplacementPlugin` case, it's not really any processed result from a preceding step but an argument passed in by `hooks.beforeResolve.callAsync`, which sort of confused me when I was learning through the source code. Renaming it to `resolveData` would improve the semantic here. I can remove the typing related changes if you decide to accept the `result` -> `resolveData` change. Otherwise feel free to close it as this isn't a critical problem at all.

**Comment by alexander-akait** [comment]
@chenxsan Hello, do we still need it?

**Comment by chenxsan** [comment]
> @chenxsan Hello, do we still need it?

Nah, let's close it, thanks for heads-up.

**Pull request closed without merging**
