### PR TITLE
chore: Minor refactor

### PR DESCRIPTION
**Pull request by jamesgeorge007**
**What kind of change does this PR introduce?**
refactoring

**Did you add tests for your changes?**
Nope

**Does this PR introduce a breaking change?**
Nope

**What needs to be documented once your changes are merged?**
N/A

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
cc @sokra

**Comment by jamesgeorge007** [comment]
The code-snippet [here](https://github.com/webpack/webpack/pull/9559/files#diff-5407438e08f76149c8281038822a2ca9R41) could be refactored as :-
```js
if (["string", "function"].indexOf(typeof options) !== -1) { // ["string", "function"].includes(typeof options) 
  //
}
```
or even,

```js
if (["string", "function"].some(type => type === typeof options)) {
  //
}
```

But `tsc --pretty` fails for the above case.
@sokra thoughts :thinking:

**Comment by jamesgeorge007** [comment]
cc @sokra

**Comment by sokra** [comment]
> The code-snippet [here](https://github.com/webpack/webpack/pull/9559/files#diff-5407438e08f76149c8281038822a2ca9R41) could be refactored as :-

Better avoid that. This makes is less readable and probably slower.

**Comment by sokra** [comment]
Thanks

**Comment by jamesgeorge007** [comment]
@sokra I would love to collaborate with, would be awesome if you could add me to the org :clap:

**Comment by jamesgeorge007** [comment]
@sokra I would love to collaborate with, would be awesome if you could add me to the org :clap:

**Comment by jamesgeorge007** [comment]
Also, I would love to collaborate with, would you mind adding me to the org?

**Pull request merged**
