### PR TITLE
bugfix(harmony-deps) : bind the function to prevent the this keyword …

### PR DESCRIPTION
**Pull request by rgranger**
see https://github.com/webpack/webpack/issues/8794

**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

no

**Does this PR introduce a breaking change?**

no

**What needs to be documented once your changes are merged?**

nothing

### CODE REVIEW

**Comment by sokra** [comment]
Please sign the CLA, I can continue with tests and linting.

**Comment by rgranger** [comment]
I think i did already :

> You have signed the CLA for webpack/webpack

But i don't know why the label is still "not signed yet"...

**Comment by evilebottnawi** [comment]
email in commit is not the same as you accept

**Comment by rgranger** [comment]
Ok I figured it out : the email linked with commit wasn't registered in my github account. It should be fine now.

**Comment by evilebottnawi** [comment]
@rgranger please fix lint problem with prettier

**Comment by sokra** [comment]
Thanks

**Pull request merged**
