### PR TITLE
Make issue template easier to understand

### PR DESCRIPTION
**Pull request by SpaceK33z**
**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe: issue template changes

**What is the current behavior?** (You can also link to an open issue here)

With the current issue template, people often won't know what to remove exactly.

Also, the first lines are basically shouting at you TO NOT CREATE AN ISSUE IF YOU HAVE A QUESTION. This is okay, but this scares / confuses people (myself included 😱 ). Unfortunately, many people are still asking questions here.

The current PR template has about the same problem; people don't know what to remove. The checkboxes are confusing in the overview, since it makes it seem like the PR is in progress.

**What is the new behavior?**

The new template asks real questions to the user, making it easier to fill out and know where to put the answers.

It still strongly makes clear that you should not ask questions here, but does so more subtly.

All hints are between HTML comments (`<!-- -->`), which means that even if the user forgets to remove that, it isn't visible in the issue anyway.

This was heavily inspired by Yarn's [issue template](https://raw.githubusercontent.com/yarnpkg/yarn/master/.github/ISSUE_TEMPLATE.md). Hope you don't mind, @cpojer!

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by SpaceK33z** [comment]
After this is merged, I'm going to add these issue templates to our most popular loaders as well.

**Comment by cpojer** [comment]
nice to see the template spread. This is originally from Jest: https://github.com/facebook/jest :D

**Comment by TheLarkInn** [comment]
:) thanks for the inspiration

**Comment by sokra** [comment]
> All hints are between HTML comments (), which means that even if the user forgets to remove that, it isn't visible in the issue anyway.

awesome idea :+1:

**Comment by cpojer** [comment]
Personally I just got sick of all the issues where people didn't bother to delete the template, so using HTML comments seemed like a good away to keep my own sanity.

**Pull request merged**
