### PR TITLE
refactor: migrate on `acorn-import-attributes`

### PR DESCRIPTION
**Pull request by alexander-akait**
**What kind of change does this PR introduce?**

https://github.com/xtuc/acorn-import-attributes/pull/31/

**Did you add tests for your changes?**

Existing

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

Added `with` ruleset rule, like `assert`, i.e.:

```js
/** @type {import("../../../../").Configuration} */
module.exports = {
	module: {
		rules: [
			{
                                // will handle `pkg-1.json`
				assert: { type: "json" },
				loader: require.resolve("./loader-assert.js")
			},
			{
			        // will handle `pkg-2.json`
				with: { type: "json" },
				loader: require.resolve("./loader-with.js")
			}
		]
	}
};

```js
import one from "./pkg-1.json" assert { type: "json" };
import two from "./pkg-2.json" with { type: "json" };
```

### CODE REVIEW

**Comment by alexander-akait** [comment]
Need to fix https://github.com/xtuc/acorn-import-attributes/pull/31#discussion_r1542987829

**Comment by ahabhgk** [comment]
Can I take this? 😁

**Comment by alexander-akait** [comment]
@ahabhgk I am already working on it :smile: we have small problems here, need to deprecate the `assert` rule in favor `attributes`, on the other hand, it might be worth preserving both - `assert` and `attributes`, so developers can write different rules for differents imports, i.e. `import json from './foo.json' assert { type: 'json' };` and `import json from './foo.json' with { type: 'json' };`, not sure how better, what do you think?

**Comment by ahabhgk** [comment]
> https://twitter.com/NicoloRibaudo/status/1772721841670402384

My opinion is deprecate the `assert` rule in favor `attributes` (or `with`?) rule, and remove the `assert` rule in the next major, since all mainstream tools and platforms will remove it

**Comment by alexandrenicol** [comment]
@alexander-akait hello, is there any update on this?

I'm very keen on this PR, because the old version of the acorn library is being flagged as containing a [security issue](https://github.com/xtuc/acorn-import-attributes/issues/24).

Is there any thing I can do to help this move along, then feel free to tag me in please.

Cheers

**Comment by alexander-akait** [comment]
@alexandrenicol Hello, try to finish it on this week

**Pull request merged**
