### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by chenxsan**
**What kind of change does this PR introduce?**

fix typos.

**Did you add tests for your changes?**

Not necessary.

**Does this PR introduce a breaking change?**

No.

**What needs to be documented once your changes are merged?**

Nothing.

### CODE REVIEW

**Comment by chenxsan** [comment]
@sokra Thanks for remind, updated.

**Comment by snitin315** [comment]
You need to update snapshot as well.

**Comment by chenxsan** [comment]
@snitin315 Done. Thanks.

**Comment by yasar112** [comment]
Sent from Yahoo Mail for iPhone


On Cumartesi, Mayıs 2, 2020, 3:49 ÖS, Sam Chen <notifications@github.com> wrote:




@snitin315 Done. Thanks.

**Pull request merged**
