### PR TITLE
Initialize fileTimestamps and contextTimestamps in Compilation

### PR DESCRIPTION
**Pull request by mohsen1**
**What kind of change does this PR introduce?**
refactor

**Did you add tests for your changes?**
no

**If relevant, link to documentation update:**

**Summary**
`this.fileTimestamps && this.contextTimestamps` is always falsy in `Compilation`. I looked into Tapable too and those don't exist there either. I see `fileTimestamps` in `Compiler` class. Is that related?

**Does this PR introduce a breaking change?**

**Other information**

Related to https://github.com/webpack/webpack/pull/6862

### CODE REVIEW

**Comment by ooflorent** [comment]
It looks like that code was not dead 😕

**Comment by mohsen1** [comment]
I can't follow what's going on here. How Compiler and Compilation classes are related?

**Comment by ooflorent** [comment]
`Compiler` creates instances of `Compilation`:

https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L428-L438

**Comment by sokra** [comment]
This code is definitely not dead, it's pretty important.

The timestamps are set by the `Watching` or by the `CachePlugin`.

Maybe initialize them in the constructor to `undefined`

**Comment by sokra** [comment]
Thanks

**Pull request merged**
