### PR TITLE
Add types to support configuration functions

### PR DESCRIPTION
**Pull request by vitoyucepi**
Ref: #11630

Add `ConfigurationFactory` and `MulitConfigurationFactory` to support https://webpack.js.org/configuration/configuration-types/.
Add `CliConfigOptions` interface from `webpack-cli`.

This is a port based on `@types/webpack`.

I want to use it like
```ts
export default ((_, argv) => {
  if (argv && argv.mode === 'production') {
    return loadConfigs('production');
  }
  return loadConfigs('development');
}) as MultiConfigurationFactory;
```

**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

**Does this PR introduce a breaking change?**

no

**What needs to be documented once your changes are merged?**

It's required to update `CliConfigOptions` for every release.
I've extracted `CliConfigOptions` with snippet in `webpack-cli/packages/webpack-cli/lib/utils/cli-flags.js`
```js
[...core, ...flagsFromCore].forEach((flag) => {
    let name = flag.name;
    for (let dashPos = name.indexOf('-'); dashPos !== -1; dashPos = name.indexOf('-', dashPos)) {
        name = name.slice(0, dashPos) + name.slice(dashPos + 1, dashPos + 2).toUpperCase() + name.slice(dashPos + 2, name.length);
    }
    let type;
    switch (name) {
        case 'mode':
            type = 'Mode';
            break;
        default:
            if (Array.isArray(flag.type)) {
                type = flag.type.map((flagType) => flagType.name.toLowerCase()).join(' | ');
                if (flag.multiple) {
                    type = `(${type})[]`;
                }
            } else {
                type = flag.type.name.toLowerCase();
                if (flag.multiple) {
                    type += '[]';
                }
            }
    }
    if (flag.description) {
        console.log('  /**');
        console.log(`   * ${flag.description}`);
        console.log('   */');
    }
    console.log(`  ${name}?: ${type};`);
    console.log();
});
```

### CODE REVIEW

**Review by evilebottnawi — CHANGES_REQUESTED** [review]
All types are auto generated, so it is invalid approach

**Comment by vitoyucepi** [comment]
@evilebottnawi I'll need some guidance in this case.

Also storing types.d.ts as build result is little disappointing. I think it should be generated at build time.

**Comment by evilebottnawi** [comment]
This types out of scope webpack, it should be on webpack-cli side, anyway you can achieve this just adding more types in own webpack.config.js

**Comment by vitoyucepi** [comment]
@evilebottnawi but `@types/webpack` have type for function that produces configs.
The list of `CliConfigOptions` contains a small list of `webpack-cli` args and a large list of `webpack` flags imported in `webpack-cli` from `webpack` as `flagsFromCore`.
I don't really know why `flagsFromCore` have no typings in `webpack` package.

**Comment by vankop** [comment]
Thanks for your contribution. I am closing PR because it is too stale..

**Pull request closed without merging**
