### PR TITLE
Change the way MultiItemCache iterates over items in

### PR DESCRIPTION
**Pull request by dtanders**
One of the projects I'm on at work has such a large number of outputs (currently 1400 and growing) and that is causing webpack to crash during compilation. You can [see in the stack trace starting here](https://gist.github.com/dtanders/b244f9d58757b2ad57486a2981a88097#file-webpack_stack_trace-txt-L7942) that the same 6 lines repeat a little over 1200 times until the stack is exhausted.  This is because the MultiItemCache in lib/CacheFacade.js uses recursion to iterate over it's item list when you call get().  Changing that to a do/while loop prevents stack exhaustion both in the included unit test and in my testing with our project.  I'm sure it could be more elegantly written but I've taken care to prevent behavioral changes other than preventing our use case from blowing the stack.

**What kind of change does this PR introduce?**

This is a bugfix for a probably-rare case where a large number of outputs causes compilation to exhaust the interpreter stack.

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

None that I'm aware of

### CODE REVIEW

**Comment by dtanders** [comment]
Guess I'll have to redo the whole branch to make the CLA bot happy 😑

**Comment by alexander-akait** [comment]
Tests are failed

**Comment by dtanders** [comment]
Yeah, there are a bunch of failing tests on my local either way:
My branch:
```
yarn run cover:all 
Test Suites: 11 failed, 76 passed, 87 total
Tests:       14 failed, 109 skipped, 66058 passed, 66181 total
Snapshots:   333 passed, 333 total
Time:        1638.963 s, estimated 1658 s
```
main:
```
yarn run cover:all
Test Suites: 7 failed, 79 passed, 86 total
Tests:       35 failed, 111 skipped, 69316 passed, 69462 total
Snapshots:   402 passed, 402 total
Time:        1782.687 s
```
No idea why the total test number is more than 3k lower.  I had assumed the test suite was just partially broken until I looked at some other PRs and found they all pass, so I'm not real sure what to do, especially since all I get out of the Azure pipelines are some Node-internal stack traces.

**Comment by alexander-akait** [comment]
> FAIL test/PersistentCaching.test.js
>  ● Test suite failed to run

>    Jest worker encountered 4 child process exceptions, exceeding retry limit

>      at ChildProcessWorker.initialize (node_modules/jest-worker/build/workers/ChildProcessWorker.js:185:21)

Try to run this test locally

**Comment by dtanders** [comment]
> > FAIL test/PersistentCaching.test.js
> Try to run this test locally

Thank you! That was good guidance and I got it to pass locally.  My implementation got even uglier, but such is life without tail call optimization, I suppose.  All of the Node-internal out of memory errors appear to be resolved, locally, at least.

```Test Suites: 14 failed, 73 passed, 87 total
Tests:       33 failed, 111 skipped, 69263 passed, 69407 total
Snapshots:   1 obsolete, 402 passed, 402 total
Time:        1994.409 s```

**Comment by dtanders** [comment]
I'm going to close this PR and make a new one with one commit that should (🤞) pass the CLA check just to make this less messy/confusing.

**Pull request closed without merging**
