### PR TITLE
fix quadratic evaluation performance of async modules

### PR DESCRIPTION
**Pull request by sokra**
improve runtime code for async modules

**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

**Comment by jsg2021** [comment]
Could this have introduced an edge case that does not resolve?

On 7.73.0 I have a bundle when I import it I see the default key is a pending promise, and it does not appear to resolve. 

webpack-5 73 0


but on 5.72.1 it resolves:
webpack-5 72 1

**Comment by vankop** [comment]
please create small reproducible repo

**Comment by jsg2021** [comment]
> please create small reproducible repo
Here you go:
https://github.com/jsg2021/webpak-hanging-bundle-example

**Comment by alecmev** [comment]
@jsg2021 Have you found the cause of this hang? I'm experiencing something similar, but having a hard time narrowing it down. I just know that the problem appeared between `5.72.1` and `5.73.0`.

**Comment by jsg2021** [comment]
nope. I somehow worked around it.

**Comment by alecmev** [comment]
@jsg2021 Dang... Thanks for the quick reply!

@sokra @vankop Can you take a look at the repro above, please?

**Comment by alexander-akait** [comment]
Let's investigate https://github.com/webpack/webpack/issues/16097

**Pull request merged**
