### PR TITLE
feat(Chunk.js): :sparkles:  size fn: Modify options to default parameter

### PR DESCRIPTION
**Pull request by huruji**
**What kind of change does this PR introduce?**

feature

**Did you add tests for your changes?**
don't need tests

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
no

Just modify `options` to default parameter to avoid error when use `chunk.size()` , like this:

image

image

this make writing plugins more convenience

### CODE REVIEW

**Comment by TheLarkInn** [comment]
Hey @huruji I don't mind this change personally but against our next branch we have some new type annotations that would probably error with this addition. Are you looking for this to land in v5 or just master?

**Comment by huruji** [comment]
Oh, just master. I write a plugin which is neeed `chunk.size()` function, without this addition, this function must need a param, like `chunk.size({})` and in my opinion, this seems a bit unnecessary.  If this addtion maybe cause errors, I don't mind close this PR. @TheLarkInn

**Comment by huruji** [comment]
image

I have signed @sokra

**Comment by sokra** [comment]
Thanks

**Pull request merged**
