### PR TITLE
perf: Remove Error.captureStackTrace from all WebpackErrors

### PR DESCRIPTION
**Pull request by markjm**
Closes ##13532

**What kind of change does this PR introduce?**
perf fix for errors

**Did you add tests for your changes?**
current error tests passing

**Does this PR introduce a breaking change?**
dont think so

**What needs to be documented once your changes are merged?**
no>

### CODE REVIEW

**Comment by markjm** [comment]
I ran UTs locally, but not sure if I ran all different integration tests. Seems possible that some stack messages may _slightly_ change, but lets see with this test pass

**Comment by markjm** [comment]
Seems one watching test failed. Wondering if its flaky because other node versions both below and above this one are fine

**Comment by markjm** [comment]
@sokra fyi - patching in this change gave us the 3second per recompile improvement I mentioned in the issue

**Comment by sokra** [comment]
Thanks

**Pull request merged**
