### PR TITLE
fix the illegal syntax in a module for test

### PR DESCRIPTION
**Pull request by e-cloud**
**Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes )

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bugfix for tests

**What is the current behavior?** (You can also link to an open issue here)
https://github.com/webpack/webpack/issues/1792
The test case for harmony-export-precedence has illegal syntax.

**What is the new behavior?**
no syntax error

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by sokra** [comment]
Why is this illegal?

**Comment by e-cloud** [comment]
you can review that issue

**Comment by sokra** [comment]
Ah ok, so it makes sense to display an warning or a Syntax error in this case?

**Comment by e-cloud** [comment]
The error will be reported by acorn(the latest version).(There is another PR update the deps later)

The point is should we add testcase to detect the error.

**Comment by TheLarkInn** [comment]
Looks good. Test failing on AppVeyor is timeout exceeding. Created #3198 for it.

**Pull request merged**
