### PR TITLE
update yarn lockfile

### PR DESCRIPTION
**Pull request by sokra**
**What kind of change does this PR introduce?**
CI

**Did you add tests for your changes?**
N/A

**If relevant, link to documentation update:**
N/A

**Summary**

**Does this PR introduce a breaking change?**
no

### CODE REVIEW

**Comment by TheLarkInn** [comment]
This for watchpack? Regardless looks good to me.

**Comment by sokra** [comment]
The problem is that this breaks the build. We need to identify the dependency that causes this.

**Comment by TheLarkInn** [comment]
It's not watchpack? Oh 👌

**Comment by sokra** [comment]
watchpack was one problem

**Comment by TheLarkInn** [comment]
Can use `yarn upgrade-interactive` to view individual packages and bulk.

**Comment by sokra** [comment]
It seem to be working now...
Just waiting for the CI to finish...
It takes ages...

**Pull request merged**
