### PR TITLE
Stream JSON output (--json)

### PR DESCRIPTION
**Pull request by simonflk**
This fixes webpack/webpack#4629

**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

No. I will have a look and see if I can find where to add appropriate tests.

**If relevant, link to documentation update:**

**Summary**

This fixes an issue in webpack/webpack#4629 where I reported that I was unable to write out profile JSON.

**Does this PR introduce a breaking change?**

I don't believe so, no.

**Other information**

### CODE REVIEW

**Comment by timse** [comment]
`json-streamify` looks like it does actually stream, but it comes at the cost of "lexing" and traversing a potentially huge json. not sure if thats good.

**Comment by sokra** [comment]
We can try `JSON.stringify` and if it throws use the safe json-stringify impl.

**Comment by Heeseong** [comment]
I applied the change to webpack 1.13.0

But I got this error :(

node version v4.4.7
npm version 2.15.8

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

RangeError: Invalid string length
    at join (native)
    at Object.stringify (native)
    at Stream.<anonymous> (C:\XXXXXX\webpack\node_modules\JSONStream\index.js:196:23)
    at Stream.stream.write (C:\XXXXXX\webpack\node_modules\JSONStream\node_modules\through\index.js:26:11)
    at compilerCallback (C:\XXXXXX\webpack\node_modules\webpack\bin\webpack.js:175:14)
    at Compiler.<anonymous> (C:\XXXXXX\webpack\node_modules\webpack\lib\Compiler.js:194:14)
    at Compiler.emitRecords (C:\XXXXXX\webpack\node_modules\webpack\lib\Compiler.js:282:37)
    at Compiler.<anonymous> (C:\XXXXXX\webpack\node_modules\webpack\lib\Compiler.js:187:11)
    at C:\XXXXXX\webpack\patches\webpack\lib\Compiler.js:73:20
    at Compiler.applyPluginsAsync (C:\XXXXXX\webpack\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:69)
    at Compiler.afterEmit (C:\XXXXXX\webpack\patches\webpack\lib\Compiler.js:70:14)
    at Compiler.<anonymous> (C:\XXXXXX\webpack\patches\webpack\lib\Compiler.js:65:27)
    at C:\XXXXXX\webpack\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at replenish (C:\XXXXXX\webpack\node_modules\webpack\node_modules\async\lib\async.js:306:28)
    at C:\XXXXXX\webpack\node_modules\webpack\node_modules\async\lib\async.js:326:29
    at C:\XXXXXX\webpack\node_modules\webpack\node_modules\async\lib\async.js:44:16
    at C:\XXXXXX\webpack\node_modules\webpack\node_modules\async\lib\async.js:1209:30
    at C:\XXXXXX\webpack\node_modules\less\node_modules\graceful-fs\graceful-fs.js:43:10
    at C:\XXXXXX\webpack\node_modules\webpack\node_modules\enhanced-resolve\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by sokra** [comment]
https://twitter.com/bmeurer/status/889450001709096962

**Pull request closed without merging**
