### PR TITLE
fix: should avoid through variables in inlined module

### PR DESCRIPTION
**Pull request by fi3ework**
**What kind of change does this PR introduce?**

**What does it fix:**

- Fix https://github.com/webpack/webpack/issues/18843 and scope level collision caused by rename. Will finish this PR tomorrow.
- Count in nested scope variable to avoid collision with the possible renamed names.

**Changes overview:**

- Reuse the renaming logic from `lib/optimize/ConcatenatedModule.js` in `lib/javascript/JavascriptModulesPlugin.js`
- Extract reusable functions to `lib/util/concatenate.js` from `lib/optimize/ConcatenatedModule.js` and remove the duplicated in `lib/javascript/JavascriptModulesPlugin.js`
- Adding `Synmbol` as a js globals to`RESERVED_NAMES`.

**Did you add tests for your changes?**

Yes.

**Does this PR introduce a breaking change?**

No, but there's an API `findNewName` is removed from `lib/javascript/JavascriptModulesPlugin.js`, do we need to preserve that? I'm not clear about are the methods of plugins are treated as the stable stuff. If so, we could simply proxy the refactored method.

**What needs to be documented once your changes are merged?**

No.

### CODE REVIEW

**Comment by fi3ework** [comment]
@alexander-akait I'll add the related test and clean code tonight, after that, we're good to merge.

**Review by snitin315 — APPROVED** [review]
LGTM, thanks!

**Comment by alexander-akait** [comment]
@fi3ework Is it ready to merge?

**Comment by fi3ework** [comment]
@alexander-akait Yes, it's ready for review.

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
