### PR TITLE
Fixed issue with wrong type information for watchOptions.ignored

### PR DESCRIPTION
**Pull request by JonWallsten**
**What kind of change does this PR introduce?**

Bugfix for https://github.com/webpack/webpack/issues/11903

**Did you add tests for your changes?**

No

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

Nothing

### CODE REVIEW

**Review by evilebottnawi — COMMENTED** [review]
types are auto generated, you need fix inside typescript JSDocs

**Comment by JonWallsten** [comment]
> types are auto generated, you need fix inside typescript JSDocs

Ah, sorry! That makes sense. I'll fix it.

**Comment by JonWallsten** [comment]
@evilebottnawi: Is it the schema file that needs to be changed? 
`WebpackOptions.json`

**Comment by evilebottnawi** [comment]
Yep, if we support it

**Comment by JonWallsten** [comment]
> Yep, if we supported it

I can't find any other place where it takes the information from. Do you have any other ideas?

**Comment by evilebottnawi** [comment]
Already fine in schema https://github.com/webpack/webpack/blob/master/schemas/WebpackOptions.json#L3616

**Comment by JonWallsten** [comment]
> Already fine in schema https://github.com/webpack/webpack/blob/master/schemas/WebpackOptions.json#L3616

I think it should be changed to:
```
"ignored": {
  "description": "Ignore some files from watching (glob pattern or regexp).",
  "anyOf": [
    {
      "type": "array",
      "items": {
        "description": "A glob pattern for files that should be ignored from watching.",
        "oneOf": [
          {
            "type": "string",
            "minLength": 1
          },
          {
            "instanceof": "RegExp",
            "tsType": "RegExp"
          }
        ]
      }
    },
    {
      "instanceof": "RegExp",
      "tsType": "RegExp"
    },
    {
      "description": "A single glob pattern for files that should be ignored from watching.",
      "type": "string",
      "minLength": 1
    }
  ]
},
```

**Comment by JonWallsten** [comment]
Seems like it worked:
image

**Comment by sokra** [comment]
An array of RegExp is not supported (yet). The types are correct.

**Comment by JonWallsten** [comment]
> An array of RegExp is not supported (yet). The types are correct.

I see. My implementation with both strings, and RegExp seems to work just fine though. Will double check.

**Pull request closed without merging**
