### PR TITLE
npm: fixed dependency for npm@3.0.0

### PR DESCRIPTION
**Pull request by solcik**
Hello,

here is pullrequest to fix dependencies for npm@3.0.0.

https://github.com/npm/npm/releases/tag/v3.0.0

### CODE REVIEW

**Comment by popomore** [comment]
+1

**Comment by popomore** [comment]
#1221

**Comment by SimenB** [comment]
No real reason to have a range with a direct dependency

**Comment by IngwiePhoenix** [comment]
If you mean „range for version“, then it makes sense since npm@3 will cherrypick the right version between multiple dependant modules. Its part of it’s flattening process.

**Comment by SimenB** [comment]
Fair point. It should be done for every dep then, not just this one

**Comment by sokra** [comment]
How does this change affect npm@2 users?

**Comment by IngwiePhoenix** [comment]
On So. Juli 12 2015 22:04:07 Tobias Koppers wrote:
> How does this change affect npm@2 users?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/webpack/webpack/pull/1197#issuecomment-120758304>.
> 

It doesn’t. Stuff will be as it was before for npm@2. But it will have a pretty impact on npm@3.

**Comment by sokra** [comment]
Thanks

**Pull request merged**
