### PR TITLE
fix:Can't find options with ident

### PR DESCRIPTION
**Pull request by melan0802**
fix issue: https://github.com/webpack/webpack/issues/8952

**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

yes

**Does this PR introduce a breaking change?**

no

**What needs to be documented once your changes are merged?**

N/A

### CODE REVIEW

**Comment by melan0802** [comment]
help please, try to check detail of the codecov failed check, but get no response from codecov.io

**Comment by melan0802** [comment]
Help please, codecov saying integration test coverage decrease by 0.01% but I didn't del any integration test. Could anyone check it for helping?

**Comment by evilebottnawi** [comment]
@melan0802 all ok, don't pay attention to it

**Comment by melan0802** [comment]
> @melan0802 all ok, don't pay attention to it

OK, thanks

**Comment by sokra** [comment]
fixed in `next` branch

**Pull request closed without merging**
