### PR TITLE
Correct ExternalModule's global option (#6933)

### PR DESCRIPTION
**Pull request by marcusdarmstrong**
**What kind of change does this PR introduce?**

Quick fix for #6933.

**Did you add tests for your changes?**

No, as there weren't any covering this code to begin with.

**If relevant, link to documentation update:**

**Summary**

Currently ExternalModules that have a type of 'global' produce invalid code, as described in #6933. This affects things like the DllPlugin.

**Does this PR introduce a breaking change?**

No.

**Other information**

### CODE REVIEW

**Comment by TheLarkInn** [comment]
@marcusdarmstrong Let me know if you need further help with any of the comments we've provided. No time pressure, just making sure instructions are clear!

**Comment by marcusdarmstrong** [comment]
@TheLarkInn haven’t had a chance to look yet, but I don’t expect difficulty. We’ve been running with this hacked in via the prototype so it’s been lower priority to get it upstreamed, but still on my to-do list.

**Comment by marcusdarmstrong** [comment]
Thanks for writing tests for me!

**Comment by sokra** [comment]
Thanks

**Pull request merged**
