### PR TITLE
fix: fix FileSystemInfo#createSnapshot with symbol link

### LINKED ISSUE #12246: FileSystemInfo can not createSnapshot with symbol link
# Bug report

**What is the current behavior?**
I install deps with [npminstall](https://github.com/cnpm/npminstall)(it can install faster), but the file tree in `node_modules` is special bacause npminstall install pkgs with symbol link to download and write less files.

The file tree looks like this
```
app
├── index.js
└── node_modules
    ├── _a@1.0@a(real dir)
    |   ├── index.js
    |   └── node_modules
    |       └── b(symbol link to app/node_modules/_b@1.0@b)
    ├── _b@1.0@b(real dir)
    |   ├── index.js
    |   └── node_modules
    |       └── a(symbol link to app/node_modules/_a@1.0@a)
    ├── a(symbol link to app/node_modules/_a@1.0@a)
    └── b(symbol link to app/node_modules/_b@1.0@b)
```

Because of a,b is reference by each other, `contextTimestampQueue` and `contextHashQueue` in `FileSystemInfo` will never reach the end.

**If the current behavior is a bug, please provide the steps to reproduce.**

The minimal reproduction repo is [here](https://github.com/killagu/npminstall_webpack).
The reproduce step is 
```shell
git clone git@github.com:killagu/npminstall_webpack.git
cd npminstall_webpack
npm i -g cnpm
# must use cnpm install
cnpm i
npm run build
```

Build snapshow will fail.

**What is the expected behavior?**
- Use `fs.lstat` to get file info, and use target path to process.
- Skip files if has been processed

**Other relevant information:**

webpack version:  5.11.0
Node.js version: 12.16.3
Operating System: macOS Big Sur 11.0.1 (20B29) 

If it is ok, I'm happy to make a pr to fix it.

### PR DESCRIPTION
**Pull request by killagu**
Resolve #12246

Use fs.lstat instead of fs.stat to get file meta.
If file is symbol link use fs.realpath to get real path,
and use real path to do recursive call.

Refs:
- https://github.com/webpack/webpack/issues/12246

**What kind of change does this PR introduce?**
Bugfix

**Did you add tests for your changes?**
Yes

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
No

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]
/cc @sokra

**Comment by killagu** [comment]
ping @alexander-akait @sokra. Would you mind to review the pr again? This pr's all checks have passed.

**Comment by alexander-akait** [comment]
@killagu Can you accept CLA do rebase? Sorry for delay

**Comment by killagu** [comment]
@alexander-akait Conflicts have been fixed.

**Comment by rifler** [comment]
let's merge it?

**Comment by rifler** [comment]
can we merge it?

**Comment by paztis** [comment]
What is the status for this PR ?
I've disable the symlinks to allow correct module resolution in linked modules. but because of this the watchers are not correctly working on Webpack 5, while they were working on Webpack 4.

This PR is very important to merge to resolve this. Something is blocking here ?

**Comment by Puritanic** [comment]
Hey, @alexander-akait any updates on ETA for merging this PR? Thank you.

**Comment by alexander-akait** [comment]
Here fix right fix https://github.com/webpack/webpack/pull/14019

**Comment by alexander-akait** [comment]
Fixed by https://github.com/webpack/webpack/pull/14019

**Pull request closed without merging**
