### PR TITLE
Add repro test case

### PR DESCRIPTION
**Pull request by sokra**
**What kind of change does this PR introduce?**
test case

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

**Comment by sokra** [comment]
@ooflorent I found this branch. A test case doesn't hurt.

**Comment by ooflorent** [comment]
Ahah. I tried to squash this bug but wasn't able to find how/where it should be done. I didn't submit a PR because it would break the master…

**Comment by sokra** [comment]
hmm I see...

**Comment by sokra** [comment]
The test case is not correct. For backward-compat reasons `* as m` returns `module.exports` in non-mjs files.

**Pull request closed without merging**
