### PR TITLE
Use Jest with jest-runner-mocha

### PR DESCRIPTION
**Pull request by rogeliog**
**What kind of change does this PR introduce?**

This is just a proposal, and I completely understand if you don't want to move forward with this, or if it does not align with the direction of the project.

Jest 21 comes with support for custom runners, and I've been working on [`jest-runner-mocha`](https://github.com/rogeliog/jest-runner-mocha/) to enable a Mocha code base to run on Jest.

screen shot 2017-09-07 at 11 19 35 am

with `--coverage`
screen shot 2017-09-25 at 1 24 34 pm

### Watch mode
watch

**Did you add tests for your changes?**

**If relevant, link to documentation update:**

**Summary**

After reading #4499 it seems that migrating it to use Jest would be quite a task... 

This solution:
- Allows the codebase to start using Jest as a test runner, while still use Mocha as a test framework
- Once Jest is being used as a test runner, we could add multiple `--projects` and slowly migrate the tests to use Jest as a test framework `jest --projects legacy-mocha jest`
- Requires minimal code changes

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by sokra** [comment]
```
TypeError: Generator is already running
    at next (native)
    at step (C:\projects\webpack\node_modules\jest-cli\build\cli\index.js:46:2233)
    at C:\projects\webpack\node_modules\jest-cli\build\cli\index.js:46:2393
```

on node 6, windows

**Comment by rogeliog** [comment]
Hi 👋 @sokra!

Thanks for finding the Node 6, Windows issue. I've addressed that and CI is passing. Are there any other changes you need me to make? 😄 Cheers!

**Comment by TheLarkInn** [comment]
Hey @sokra, I'm going to move this out of v4 and into v4.x or future as this is probably not a blocker for v4 release timeline.

**Comment by niieani** [comment]
@TheLarkInn we can probably close this one now, since we're using native `jest`.

**Comment by TheLarkInn** [comment]
I'll close this for now, and if @rogeliog see's any need to reopen, we shall do so.

**Pull request closed without merging**
