### PR TITLE
Read 'browser' main field when target is 'electron-renderer'

### LINKED ISSUE #6811: Target `electron-renderer` should have `browser` in `resolve.mainFields`
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When using `target: 'electron-renderer'`, it doesn't use the browser version of dependencies with a `browser` field in their package.json.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

A renderer process in Electron is just a browser, so it makes sense for it to get browser versions of dependencies, like the `web` target. So when `electron-renderer` is specified as `target`, it `mainFields: ["browser", "module", "main"]` should be set.

https://webpack.js.org/configuration/resolve/#resolve-mainfields

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Webpack 4.1.1

### PR DESCRIPTION
**Pull request by ooflorent**
**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

yes

**If relevant, link to documentation update:**

n/a

**Summary**

Fixes #6811

**Does this PR introduce a breaking change?**

no

### CODE REVIEW

**Comment by byzyk** [comment]
@ooflorent was going to submit similar PR 😄

I guess the same check has to be added [here](https://github.com/webpack/webpack/blob/877a6866ce3659b29fc1de198eebb04af60410ae/lib/WebpackOptionsDefaulter.js#L62) as well, right?

**Comment by sindresorhus** [comment]
This could also use a test: https://github.com/webpack/webpack/tree/master/test/configCases/target

**Comment by ooflorent** [comment]
Thanks for your feedback. I've also added an integration test.

**Comment by ooflorent** [comment]
@ev1stensberg Regarding the early `return`, I think it is less readable. If others want this change, sure, I'll do it!

**Comment by ev1stensberg** [comment]
@ooflorent no big deal, small picks 👍

**Comment by sokra** [comment]
Thanks

**Comment by gaodeng** [comment]
this PR cause issue 
 https://github.com/webpack/webpack/issues/7953

**Pull request merged**
