### PR TITLE
feat(uglify): move uglify to external plugin from webpack-contrib

### PR DESCRIPTION
**Pull request by TheLarkInn**
**What kind of change does this PR introduce?**
Refactoring

**Did you add tests for your changes?**
N/A

**If relevant, link to documentation update:**

**Summary**
This PR removes uglifyjs as a direct dependency and removes the internal uglifyjsplugin reference and points it to [uglifyjs-webpack-plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin)

This allows a bit more freedom to work, change, (or remove later) the uglifyjs-webpack-plugin in a much faster pace (in the case something downstream is breaking). 

**Does this PR introduce a breaking change?**
No

**Other information**
N/A

### CODE REVIEW

**Comment by sokra** [comment]
webpack-sources dependency in uglifyjs plugin need to be updated

**Comment by TheLarkInn** [comment]
Thanks I'll grab and leave this open and update.

**Comment by michael-ciniawsky** [comment]
Will this supersede #5010 ? `UgilfyJSPlugin` is still coupled to core here to some point, I additionally removed `optimize-minimize` in #5010, which might b a bit harsh tbh, but the reason is that neither `this.minimize` (Loader API [deprecated]) nor `UgilfyJSPlugin` should have special meaning anymore as I understood :)

**Comment by TheLarkInn** [comment]
I'll get to this today

**Comment by sokra** [comment]
Thanks

**Pull request merged**
