### PR TITLE
devServer: setting clientLogLevel to none to actually mute all annoying browser console logs

### PR DESCRIPTION
**Pull request by Microsmsm**
**What kind of change does this PR introduce?**

Fixing this **annoying** bug

`clientLogLevel` to `none` keeps logging annoying messages to browser

https://github.com/gaearon/react-hot-loader/issues/79
https://github.com/webpack/webpack/issues/415
https://github.com/webpack/webpack/issues/1872
https://github.com/webpack/webpack/issues/422
https://github.com/webpack/webpack/issues/476
https://github.com/webpack/webpack/issues/4115
https://github.com/webpack/webpack/pull/4960
https://github.com/webpack/webpack-dev-server/pull/579
https://github.com/webpack/webpack-dev-server/pull/1096
https://github.com/webpack/webpack-dev-server/pull/926
https://github.com/webpack/webpack-dev-server/pull/925
https://github.com/webpack/webpack/pull/1323
https://github.com/webpack/webpack-dev-server/pull/925

**Did you add tests for your changes?**
Yes,
 9890 passing (7m)
 125 pending
 2 failing
I think I need better hardware to pass all tests

**If relevant, link to documentation update:**

N/A but we may add what "none" should do now exactly

**Summary**

We like our console to be clean
These messages are really annoying when frequently reloading app in the browser
image
Setting `clientLogLevel` to none... now creates no noise 😁

Now the problem should be fixed 🎉 

**Does this PR introduce a breaking change?**
No, it's done with the minimal code change

**Other information**
N/A

### CODE REVIEW

**Comment by Microsmsm** [comment]
@sokra these logs were for reviewing testing purposes, I just removed them

**Comment by Microsmsm** [comment]
@Sokra I tried to make the minimal change to code in this PR. 
I believe the long-time fix would be by reconsidering when we set clientLogLevel and when we call module but that will need a lot of refactoring for the codebase
So this is a hot fix for the references mentioned here:
gaearon/react-hot-loader#79
#415
#1872
#422
#476
#4115
#4960
webpack/webpack-dev-server#579
webpack/webpack-dev-server#1096
webpack/webpack-dev-server#926
webpack/webpack-dev-server#925
#1323
webpack/webpack-dev-server#925

**Comment by sokra** [comment]
This change is not needed. You can use:

``` js
if(module.hot) {
  require("webpack/hot/log").setLogLevel("error");
}
```

to configure the log level in you application code.

**Comment by zenVentzi** [comment]
@sokra 's solution is not working for me but the hacky function below did the job well.
```

(function(global) {
    const console_log = global.console.log;
    global.console.log = function() {
      if (
        !(
          arguments.length == 1 &&
          typeof arguments[0] === 'string' &&
          arguments[0].match(/^\[(HMR|WDS)\]/)
        )
      ) {
        console_log.apply(global.console, arguments);
      }
    };
  })(window);
```

**Comment by zenVentzi** [comment]
"webpack": "^4.15.1",
Doesn't work with that version. What is the minimal version I need to have installed for the   `require("webpack/hot/log").setLogLevel("error");
`

to work?

Currently I am using quite a hacky version below:

```

  (function(global) {
    const console_log = global.console.log;
    global.console.log = function() {
      if (
        !(
          arguments.length == 1 &&
          typeof arguments[0] === 'string' &&
          arguments[0].match(/^\[(HMR|WDS)\]/)
        )
      ) {
        console_log.apply(global.console, arguments);
      }
    };
  })(window);
```

**Comment by geiszla** [comment]
I found that somehow this doesn't work:

```js
import { setLogLevel } from 'webpack/hot/log';
```
but this does:
```js
import { setLogLevel } from '../node_modules/webpack/hot/log';
```
This is because `webpack/hot/log-apply-result.js` uses the relative path when importing the `log()` function, and when imported as `webpack/hot/log`, Webpack handles them as a different imports with different contexts.

If you are using `webpack-dev-server`, you also need to set the `clientLogLevel` option to `warning`, `error` or `none` to work, because it will update the log level using messages over websocket. I haven't tried with `webpack-dev-middleware`, but as it doesn't support the `clientLogLevel` option, I believe the relative path should work without any modification of the server.

This is still a workaround, and I'd be happy to see a proper option implemented for changing the log level.

**Comment by IAMtheIAM** [comment]
Hey guys, none of these suggestions worked for me, except the CLI option does!!

``` 
webpack --client-log-level warning
// or 
webpack --client-log-level error
```

It defaults to `info` which is where all the [HMR] and [WDS] spam comes from.

**Pull request closed without merging**
