### PR TITLE
update coveralls reporter

### PR DESCRIPTION
**Pull request by fscherwi**
```
package: update `coveralls` v2.11.2...v3.0.2
```

**What kind of change does this PR introduce?**
- [x] Update coverage reporters

**Did you add tests for your changes?**

- [x] No

**Does this PR introduce a breaking change?**
 
- [x] No

**What needs to be documented once your changes are merged?**

- [x] None

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@montogeek ? :)

**Comment by montogeek** [comment]
Read the url, I linked #8134

**Comment by michael-ciniawsky** [comment]
The URL you linked links to this PR and isn't a duplicate? I'm not following...

**Comment by montogeek** [comment]
Got the wrong link, sorry.

**Comment by sokra** [comment]
Thanks

**Pull request merged**
