### PR TITLE
add windows to the azure pipeline

### PR DESCRIPTION
**Pull request by sokra**
**What kind of change does this PR introduce?**
CI

**Did you add tests for your changes?**
N/A

**Does this PR introduce a breaking change?**
N/A

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

**Comment by montogeek** [comment]
It is not possible to see the build?

**Comment by sokra** [comment]
Blocked by facebook/jest#6965 because of a memory leak

**Comment by sokra** [comment]
Here is the build: https://dev.azure.com/webpack-org/webpack/_build/results?buildId=24&view=logs

**Comment by montogeek** [comment]
I can see that page, but it is not possible from https://github.com/webpack/webpack/runs/16950372 links.

**Comment by sokra** [comment]
You can click on the `View more details on Azure Pipelines` link on this page

**Comment by montogeek** [comment]
It returns this page
image.

Just wanted to see how it looks like. Thanks for the link.

**Comment by sokra** [comment]
hmm... The project is public:

image

**Comment by sokra** [comment]
hmm weird that one even need to authenticate to view the page.

**Comment by DavidStaheli** [comment]
Hi webpack friends.  I'm from the Azure Pipelines team.  I'm so sorry for the trouble with this.  A bug crept in causing those URLs to require sign in.  We should have it hot-fixed in production tomorrow.  From that point on, builds will produce URLs that allow anonymous access.  Sorry again for the trouble.

**Comment by TheLarkInn** [comment]
Thanks @DavidStaheli!!!

**Comment by sokra** [comment]
Hi @DavidStaheli thanks for joining in.

Here a few updates regarding the windows azure status:

It seem like some of the problems on windows are caused by a memory leak in the test suite. I already filed a PR regarding this, which seem to fixes the problem locally for me (facebook/jest#6965). I haven't tried it on azure. I wanted to wait until the PR is merged and released. This probably also changes the performance on other platforms.

As workaround I added `--maxWorkers=2` like in appveyor and travis, this seem to work. It also speeds up the builds a bit...

**Comment by sokra** [comment]
@DavidStaheli Travis and appveyor do have "caches" usable by the builds (https://docs.travis-ci.com/user/caching/). Does something similar exists for azure? We currently use these caches to persist the yarn cache (for dependencies) and the jest transformation cache (for the source transformation for code coverage).

**Comment by sendilkumarn** [comment]
@sokra thats quite a stat 👍🎉 Thanks for writing this down

**Comment by DavidStaheli** [comment]
Unfortunately Azure Pipelines doesn't yet support caching between builds.  😞  We're working on that and other ways to make builds faster.  Please let me and @vtbassmatt know if you ever need more than the 10 parallel jobs, or if we can help with anything else.

**Pull request merged**
