### PR TITLE
Add nonce capability

### PR DESCRIPTION
**Pull request by lunasofia**
**Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
         - [x] Ran manual tests to check functionality
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://github.com/webpack/webpack/issues/455
Currently, webpack does provide a way to add nonces to scripts. Given that the future of CSP could be a more nonce-based approach, having support for nonces is increasingly important. 
https://research.google.com/pubs/pub45542.html

**What is the new behavior?**
When user specifies **webpack_nonce**, a nonce is added to all loaded scripts. Because nonces are generally different on each page load, the nonce is specified in the entry file, not in the config file, similarly to a public path not known ahead of time.

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by TheLarkInn** [comment]
Thank you for this contribution, could you perhaps include some tests and explains what the output of this feature does?

**Comment by lunasofia** [comment]
Thanks for your fast response!

I can definitely add more explanation of the purpose and output of the
feature.

I agree that a test would be great - I was actually having trouble figuring
out what the best way to add a test would be, since I don't really
understand the framework that's in place. Is there any documentation you
could point me to?

**Comment by TheLarkInn** [comment]
https://github.com/webpack/webpack/tree/master/test/cases
Is where most of our tests are broken into.

https://github.com/webpack/webpack/commit/6daa860f4702fa399fa97120227e69466d6b8cd6
Is a config based test, where properties on the config should determine an output in the bundled results. That is one of my last commits with tests.

**Comment by lunasofia** [comment]
I'm working on writing tests, and I'm pretty sure I need to write a browser test. I'd like to test that, when script tags are added to the dom, they're added with a 'nonce' attribute and the correct nonce. However, I'm not sure how to actually runt the browser tests.

**Comment by samertm** [comment]
Friendly ping about the status of this now that the PR has tests! I'm interested in using this feature :)

**Comment by TheLarkInn** [comment]
Branch needs to be updated also. Resolve conflicts.

**Comment by lunasofia** [comment]
https://github.com/webpack/webpack/pull/3210

My git state here got really messed up, so I've made a new pull request. Should be all clean and up-to-date now.

**Comment by suiz0** [comment]
I just run into a issue where I have set the value but is lost when loading chunks from react-dom.development weird enough is that is actually work in production so I'm wondering if this is an issue with webpack-dev-server

Any thoughts?

Regards

**Pull request closed without merging**
