### PR TITLE
Feature/add yarn packaging

### PR DESCRIPTION
**Pull request by TheLarkInn**
**Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features) 
  - In this case, the CI changes passing are the tests themselves
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Feature

**What is the current behavior?** (You can also link to an open issue here)
Currently we are using npm for installing dependencies.

**What is the new behavior?**
This adds yarn.lock, and incorporates the yarn package manager into the CI pipelines.

**Does this PR introduce a breaking change?**
- [x] No

If this PR contains a breaking change, please describe the following... 

* Impact: Developers. It is now recommended that installation of webpack locally happen through the following steps: 

1. `npm install yarn -g`
2. `yarn install`
3. `yarn link && yarn link webpack`

* Migration path for existing applications: N/A 
* Github Issue(s) this is regarding: N/A

### CODE REVIEW

**Comment by TheLarkInn** [comment]
Helps satisfies the local clone, checkout, installation, and CI runs portions for https://github.com/yarnpkg/yarn/issues/392

**Comment by TheLarkInn** [comment]
@SpaceK33z @bebraw @jhnns @sokra Code Review Please ❤️ 🐓 

From time comparisons. It appears to be running much faster on installs (locally for sure), and on travis as well.

**Comment by bebraw** [comment]
LGTM.

**Comment by GGAlanSmithee** [comment]
> Impact: Developers. It is now recommended that installation of webpack locally happen through the following steps

Sorry for the stupid question, but just to be sure, this recommendation only concerns developers which are working on webpack, not those using it, right? Thanks!

**Comment by SpaceK33z** [comment]
Nice work @TheLarkInn.

@GGAlanSmithee, yeah it only concerns developers working on webpack.

**Comment by jhnns** [comment]
Nice 👍

**Comment by sokra** [comment]
Yarn.lock?

We should continue testing with npm...

**Comment by jhnns** [comment]
I think that doesn't really matter. npm's installation algorithm is non-deterministic anyway. We cannot be 100% sure that all webpack installations will work if our CI test passed. If I understood it correctly, the yarn installation would be a subset of all possible npm installations – is that correct?

**Pull request merged**
