### PR TITLE
fix: add extra merge duplicates call after split chunks

### PR DESCRIPTION
**Pull request by SkReD**
Fix: https://github.com/webpack/webpack/issues/18749

**What kind of change does this PR introduce?**

Bugfix

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

I think nothing

### CODE REVIEW

**Comment by SkReD** [comment]
> It is a wrong fix and also bad for perf, we need to search another solution

Could you explain why it is wrong? Perf downside i see but dont understand significance of it - how much of total build time is taken by merge duplicates plugin work.

**Comment by alexander-akait** [comment]
> how much of total build time is taken by merge duplicates plugin work.

Based on how many chunks you have, it will be very bad for big projects

**Comment by alexander-akait** [comment]
@SkReD I think we can run merge chunks after split chunks, yes in some cases it might be a bit worse for performance because duplicates will be processed too but i don't think that's really a common case

**Comment by SkReD** [comment]
> @SkReD I think we can run merge chunks after split chunks, yes in some cases it might be a bit worse for performance because duplicates will be processed too but i don't think that's really a common case

@alexander-akait if problem solved that way and there is less drawbacks then i am ok with that

**Pull request merged**
