### PR TITLE
fix: use LZW to compress css head meta

### PR DESCRIPTION
**Pull request by ahabhgk**
**What kind of change does this PR introduce?**

use LZW to compress css head meta

And introducing `output.cssHeadDataCompression` to control it, it is enabled by default in production

**Did you add tests for your changes?**

updated snapshot

**Does this PR introduce a breaking change?**

no

**What needs to be documented once your changes are merged?**

`output.cssHeadDataCompression`

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
What about to enable it only for production mode? technically head can be used for debugging, anyway looks good

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Thank you

**Comment by alexander-akait** [comment]
@ahabhgk With the improvement of CSS support I found serious problems with this algorithm, using `"` in export can potentially cause a broken string token in css, same for `[`, `(`, `{` groups...

**Comment by ahabhgk** [comment]
I reproduced, will try to submit a fix

**Pull request merged**
