### PR TITLE
Do not install yarn on Travis

### PR DESCRIPTION
**Pull request by ooflorent**
**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

no

**If relevant, link to documentation update:**

n/a

**Summary**

Yarn is already installed on Travis and does not need to added. Moreover it occasionally fails to install and produces build failures.

**Does this PR introduce a breaking change?**

no

### CODE REVIEW

**Comment by sokra** [comment]
Instead of open/close, you can selectively restart builds on the travis page...

**Comment by ooflorent** [comment]
@sokra the restart button is not displayed. I don't know why.

**Comment by sokra** [comment]
Are you logged in on the travis page with github?

**Comment by ooflorent** [comment]
@sokra you were right. That was the issue.

**Comment by sokra** [comment]
Thanks

**Pull request merged**
