### PR TITLE
Added advanced allow-custom-args flag to allow custom args

### PR DESCRIPTION
**Pull request by robscotts4rb**
**What kind of change does this PR introduce?**
A new cli flag for users to opt in to passing custom command line arguments to their webpack config

**Did you add tests for your changes?**
Yes

**Summary**

Mainly issue #2254. We could write a custom build script but to me that defeats the ease of using webpack. We could also pass in the arguments using the new `env` object, but that would mean defining our config values twice in our production environment.

With this change you still get the benefits to new users listed in https://github.com/webpack/webpack/issues/2254#issuecomment-219219418 but allow users to opt in to the passing of custom arguments and the downsides they may introduce.

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by sokra** [comment]
This is broken on CI. Tests missing.

**Comment by robscotts4rb** [comment]
@sokra fixed the breaking change and added tests for testing strict and non strict arguments

**Comment by robscotts4rb** [comment]
ping @sokra any feelings on when/if this will be merged?

**Comment by sokra** [comment]
Currently I have a bad feeling for this. Passing arguments to configration should happen via `--env`. For custom arguments you can write your own CLI.

**Comment by robscotts4rb** [comment]
Writing a custom CLI just to pass custom args is a large overhead for most people. With this pull request, you get friendliness for newer users who want to be warned if they pass something unknown in but allow users to opt in to a more flexible version.

If I take our application as an example, we are using [nconf](https://www.npmjs.com/package/nconf) which allows you to pass command line arguments. Currently with webpack 1 we are using `nconf` in `webpack.config.js` to pass custom things (like if we are performing a production build).

Without the ability to pass custom args we would need to write a custom CLI to parse all webpack args correctly, and set any others to be passed as `env` arguments and keep this up to date for every webpack version. 
The route to accessing this information is also subtly different (with the custom CLI approach) depending on which file you have open (e.g. in Webpack: `nconf.get('env.something')`, in Node: `nconf.get('something')`).

This is a real barrier to entry migrating from Webpack 1 to Webpack 2. I can't see any downsides to the approach suggested in this pull request.

**Comment by sokra** [comment]
Closing this as you can write a custom CLI for your use case. With this flag users will abuse it.

**Pull request closed without merging**
