### PR TITLE
HarmonyImportSpecifierDependency: let import-var-suffix use dot notation instead of square bracket if possible

### PR DESCRIPTION
**Pull request by vanhoavn**
**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

No, but modified an existing stats test.

**If relevant, link to documentation update:**

N/A

**Summary**

This's to fix a problem when using typescript with es6 target and google's closure compiler.
https://github.com/google/closure-compiler/issues/2182

**Does this PR introduce a breaking change?**

No

**Other information**

### CODE REVIEW

**Comment by sokra** [comment]
This looks like a hack. I don't think this should be changed in webpack.

**Comment by vanhoavn** [comment]
Maybe but it cost nothing for this hack in webpack?

**Comment by sokra** [comment]
I don't like hacks. 😞 

And it has a cost...

**Comment by sokra** [comment]
This should be fixed in the CC.

**Pull request closed without merging**
