### PR TITLE
Ignore generated JS files examples/

### PR DESCRIPTION
**Pull request by ooflorent**
**What kind of change does this PR introduce?**

bug

**Did you add tests for your changes?**

no

**If relevant, link to documentation update:**

n/a

**Summary**

When running test cases `examples/*/js` directories are not always removed.

**Does this PR introduce a breaking change?**

no

### CODE REVIEW

**Comment by sokra** [comment]
I merge this temporary. examples write to dist.

**Comment by ooflorent** [comment]
Many tests still write to `js`. While using `--bail` and encountering an error, the files are not cleaned up.

**Comment by sokra** [comment]
see https://github.com/webpack/webpack/pull/6277

**Comment by ooflorent** [comment]
That was fast 😆

**Pull request merged**
