### PR TITLE
Related assets

### PR DESCRIPTION
**Pull request by sokra**
* add related info to asset info
* display assets in stats in a list instead of a table
* group related assets below the parent asset

**What kind of change does this PR introduce?**
feature

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
yes, stats output and format changed

**What needs to be documented once your changes are merged?**
* `stats.relatedAssets` allow to show related assets (they are hidden by default)

### CODE REVIEW

**Comment by evilebottnawi** [comment]
What about `emitAsset` for `loaderContext`? Can we implement `assetInfo` for this too? But I think we should do it in separate PR

**Comment by sokra** [comment]
https://github.com/webpack/webpack/blob/42aabc735160f248dcdc6442aaeb4b803e257146/lib/NormalModule.js#L458

Already supported

**Comment by wojtekmaj** [comment]
> display assets in stats in a list instead of a table

Can I get the old behavior somehow via config? I find the new output a little too hard to read.

**Comment by evilebottnawi** [comment]
@wojtekmaj it is still beta, please put your opinion here https://github.com/webpack/webpack/issues/10534

**Pull request merged**
