### PR TITLE
fix(css parser): handle nested atRule

### PR DESCRIPTION
**Pull request by noreiller**
**Issue:** 
When using the CSS `experiments` and using `@media` or `@supports` in CSS code, the nested class names are not replaced with their unique identifier.

**Changes:** 
This PR will handle `@media` and `@supports` atRule identifiers and enable the replacements of the nested rules names with the unique ids.

**CSS input code:**
```css
.main {
	font-size: var(--large);
	color: darkblue;
}
@media (min-width: 1024px) {
	.main {
		color: green;
	}
}
@supports (display: grid) {
	.main {
		display: grid
	}
}
```

**The compiled CSS code with the issue:**
You can see that **only** the top-level class name is replaced.
```css
.app-491-D {
	font-size: var(--large);
	color: darkblue;
}
@media (min-width: 1024px) {
	.main {
		color: green;
	}
}
@supports (display: grid) {
	.main {
		display: grid
	}
}
```

**The compiled CSS code thanks to the fix:**
You can see that **all** the class names are replaced.
```css
.app-491-D {
	font-size: var(--large);
	color: darkblue;
}
@media (min-width: 1024px) {
	.app-491-D {
		color: green;
	}
}
@supports (display: grid) {
	.app-491-D {
		display: grid
	}
}
```

### CODE REVIEW

**Comment by noreiller** [comment]
@vankop @sokra Do you think this PR could be merged?

**Review by alexander-akait — COMMENTED** [review]
Let's add test for `@media` inside `@supports` and versa vice, also I think we should handle them in `@layer` and `@namespace` (legacy) at-rules

**Comment by noreiller** [comment]
> Let's add test for `@media` inside `@supports` and versa vice

I added more test cases as you asked.

> also I think we should handle them in `@layer` and `@namespace` (legacy) at-rules

I did not implemented anything with `@namespace` because [it's not supported right now](https://github.com/webpack/webpack/blob/main/lib/css/CssParser.js#L346).

I started to implement the support of `@layer` but I encountered issues with `@import` which does not implement [conditional rules](https://developer.mozilla.org/en-US/docs/Web/CSS/@import#importing_css_rules_conditionally).
It is necessary to fix this so [importing CSS rules into a cascade layer](https://developer.mozilla.org/en-US/docs/Web/CSS/@import#importing_css_rules_into_a_cascade_layer) would be done the same way.
So, in my opinion, it would be better to handle `@import` fixes and `@layer` support this in another PR.

**Comment by alexander-akait** [comment]
@noreiller, yep we can separate this PR on parts and here only fix handling `@media` and `@supports`

Looks good :+1:

**Comment by noreiller** [comment]
> Looks good +1

@vankop Is there any blocker or another step for the merge?

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Sorry for long delay, really sorry, we will shipped this in near future, when we should finish this https://github.com/webpack/webpack/pull/15892

**Comment by noreiller** [comment]
> Sorry for long delay, really sorry, we will shipped this in near future, when we should finish this #15892

Hello, thanks for your message. Both PRs are ready as I updated the code after @sokra 's review.

**Comment by alexander-akait** [comment]
Yeah, I have some questions about layers, so let's merge it firstly

**Review by TheLarkInn — APPROVED** [review]
LGTM - Under Experiments :-)

**Pull request merged**
