### PR TITLE
chore: add bugs field in package.json

### PR DESCRIPTION
**Pull request by amareshsm**
**What kind of change does this PR introduce?**
Added bugs field in package.json file

**Did you add tests for your changes?**
   Not needed

**Does this PR introduce a breaking change?**
  NO

**What needs to be documented once your changes are merged?**
    N/A

### CODE REVIEW

**Comment by amareshsm** [comment]
Bump. Please approve workflows to run.

**Review by alexander-akait — APPROVED** [review]

**Comment by amareshsm** [comment]
Bumping for merge

**Comment by amareshsm** [comment]
Bump

**Comment by sokra** [comment]
Thanks

**Pull request merged**
