### PR TITLE
fix(schema/absolutePaths): make absolute paths case insensitive

### LINKED ISSUE #4530: 2.3.0 breaks path resolution on Windows
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Webpack fails with error on any path, e.g.:
configuration.context: The provided value “d:\\projects\\project\\src” is not an absolute path!

**If the current behavior is a bug, please provide the steps to reproduce.**
Windows 10
Git Bash
Node v6.9.1
npm v4.0.0

Create a webpack project and specify a context path, e.g. `context: path.resolve(__dirname, 'src')`

run webpack with the specified config.

**What is the expected behavior?**
Webpack uses the path as specified.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Windows 10
Git Bash
Node v6.9.1
npm v4.0.0

### PR DESCRIPTION
**Pull request by michael-ciniawsky**
**What kind of change does this PR introduce?**

- [x] Bugfix

**Did you add tests for your changes?**

No there seems to be no test case  in `Validation.test.js`

**Summary**

My motivation is to give people the opportunity to experience webpack on Windows aswell 😛 :D 

#4530, #4549, #4552

**Does this PR introduce a breaking change?**

No

**Other information**

Closes #4530, #4549, #4552

### CODE REVIEW

**Comment by TheLarkInn** [comment]
Nice catch thank you

**Comment by sokra** [comment]
I probably reject this, because it was intended to only accept Uppercase drive letters. We had an issue which was cause by lowercase drive letters. `C:\x.js` is not the same module as `c:\x.js`.

**Comment by michael-ciniawsky** [comment]
@sokra Just fine close at will, thought it was urgent so I pick the solution from the issue and send PR, no needs on supporting this from my side 😛

**Comment by zhe-he** [comment]
I hope to merge as soon as possible. 
Why not use `/i` instead of `a-z` ?

**Comment by michael-ciniawsky** [comment]
@zhe-he Why is `/i`  the better solution, I can update of course 😛

**Comment by zhe-he** [comment]
@michael-ciniawsky 
I wrote a demo   http://jsbin.com/kumojomije/edit?html,js,console,output
Found that their performance is almost the same.
So, maybe... uh...   just a little word that can be reduced by a little bit of it.  /smile

**Comment by httpdigest** [comment]
Why not just use Node's [path.isAbsolute](https://github.com/nodejs/node/blob/master/lib/path.js#L459-L478)? Another issue with the regexp check in Webpack is that it does not work with forward slashes, which are also valid in Windows.

**Comment by MortenHoustonLudvigsen** [comment]
I just updated webpack from 2.2.1 to 2.3.1 and it stopped working with the following error:
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.context: The provided value "c:\\data\\..." is not an absolute path!
 - configuration.output.path: The provided value "c:\\data\\..." is not an absolute path!
```
Patching webpack with this PR solved the issue, so I would really like to see this PR included.

**Comment by sokra** [comment]
Thanks

**Pull request merged**
