### PR TITLE
Refactor module dependency to es6

### PR DESCRIPTION
**Pull request by timse**
**What kind of change does this PR introduce?**

refactor

**Did you add tests for your changes?**

current tests should pass

**If relevant, link to documentation update:**

N/A

**Summary**

upgrade ModuleDependency to es6

**Does this PR introduce a breaking change?**

No

**Other Information**

we are getting closer :)
this PR relies on the follwing PRs to be merged:

- [x] #3782
- [x] #3787
- [x] #3807
- [x] #3808
- [x] #3809
- [x] #3810
- [x] #3811

### CODE REVIEW

**Comment by timse** [comment]
trigger rebuild for appveyor

**Comment by TheLarkInn** [comment]
Alright. Mind rebasing the other PR's and squashing?

**Comment by timse** [comment]
done :)!

**Comment by TheLarkInn** [comment]
Awesome work. Getting there. So close!!!!

**Pull request merged**
