### PR TITLE
Block without associated chunks may contain dependencies

### PR DESCRIPTION
**Pull request by Laiff**
While I play with webpack 2 async chunk loading, I was found this strange behaviour. 
This fix are very naive, but work fine.

### CODE REVIEW

**Comment by sokra** [comment]
Do you have a test case where this happens?

**Comment by Laiff** [comment]
@sokra The project is quite complex and I was not able to locate the bug, perhaps as time will be able to do it. if this really needed

**Comment by Laiff** [comment]
@sokra what do you need to aprove this request?

**Comment by TheLarkInn** [comment]
I'm not sure if this is still relevant or not. Please close the PR if so.

**Comment by sokra** [comment]
This was fixed

**Pull request closed without merging**
