### PR TITLE
Support Trusted Types in EvalSourceMapDevToolPlugin

### PR DESCRIPTION
**Pull request by tosmolka**
This PR adds support for Trusted Types to eval devtool plugins, see https://github.com/webpack/webpack/issues/14075. Change should be backwards compatible and without perf impact when output.trustedTypes option is not set. 

**What kind of change does this PR introduce?**

feature

**Did you add tests for your changes?**

yes

**Does this PR introduce a breaking change?**

no

**What needs to be documented once your changes are merged?**

I think current documentation is sufficient.

### CODE REVIEW

**Comment by alexander-akait** [comment]
Can you accept CLA?

**Comment by tosmolka** [comment]
I am Corporate contributor, waiting on CLA Manager for Microsoft to review.

**Comment by alexander-akait** [comment]
Feel free to ping me when it was ready

**Comment by tosmolka** [comment]
@alexander-akait , @sokra , friendly ping, can we get this reviewed pls? Do you have any concerns with the proposed implementation? Thanks. 

cc @koto

**Review by sokra — APPROVED** [review]

**Comment by sokra** [comment]
Thanks, sorry for the delay

**Comment by Jack-Works** [comment]
Cool thanks, so it will be included in the next webpack release right?

**Comment by alexander-akait** [comment]
Yes

**Pull request merged**
