### PR TITLE
Move CLI to webpack-cli repository

### PR DESCRIPTION
**Pull request by ev1stensberg**
Moves the CLI content to webpack/webpack-cli. Awaiting for publish of `webpack-cli` to install the cli

### CODE REVIEW

**Comment by sokra** [comment]
removing `bin/convert-argv.js` breaks the webpack-dev-server CLI. Is this handled by webpack-cli too?

**Comment by ev1stensberg** [comment]
Yepps

**Comment by sokra** [comment]
How will this be handled?

**Comment by ev1stensberg** [comment]
I checked the devServer internals earlier today/yesterday and we aren't making changes that break dev-Server. If we decide to move `config-yargs` we'll send PR's to dev-server accordingly

**Comment by ev1stensberg** [comment]
As for the failing test cases, we'll have to move them to the CLI repo.

TODO: 

- [ ] Move tests

- [ ] Update Dependency

- [ ] Remove Shebang at `webpack-cli`

**Comment by okonet** [comment]
Can we create a PR to webpack-dev-server instead of reverting this?

**Comment by ev1stensberg** [comment]
Nothing to revert, there's another file path that needs change; 'config-yags'. Can submit a PR later

**Comment by ev1stensberg** [comment]
Picking this up at friday.

**Comment by ev1stensberg** [comment]
@sokra This is ready. Test failing due:

 https://github.com/facebook/jscodeshift/issues/197#event-1099223035
https://github.com/facebook/jscodeshift/pull/198

We're planning to revamp the `binTestCases` to something like: 

https://github.com/yarnpkg/yarn/tree/master/end_to_end_tests

Anything that needs to be changed?

**Comment by ev1stensberg** [comment]
@sokra

**Pull request closed without merging**
