### PR TITLE
refactor: rm `UglifyJSPlugin` && `optimize-minimize`

### PR DESCRIPTION
**Pull request by michael-ciniawsky**
**What kind of change does this PR introduce?**

Breaking Change (:label: Major)

**Type**

- [x] Refactor

**Did you add tests for your changes?**

Yes

**If relevant, link to documentation update:**

Not yet

**Summary**

- Removes `optimize-minimize` (CLI)
- Removes `UgilfyJSPlugin` `(./lib/optimize/UglifyJsPlugin)`

**Does this PR introduce a breaking change?**

Yes

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@sokra I might need help with the remaining 3 failing tests 😛. Is the `UglifyJsPlugin.test.js` file still needed in case `UglifyJSPlugin` itself is removed from core?

**Comment by sokra** [comment]
just remove them

**Comment by michael-ciniawsky** [comment]
AppVeyor fails due to `yarn.lock` being 'outdated', I left it out on propose until now, since it's often causing nasty merge-conflicts. How to handle it at best, should I nevertheless update and commit it?

**Comment by sokra** [comment]
superseeded

**Comment by michael-ciniawsky** [comment]
Yup 😉

**Pull request closed without merging**
