### PR TITLE
refactor(es6): upgrade UglifyJSPlugin to ES6

### PR DESCRIPTION
**Pull request by aem**
**What kind of change does this PR introduce?**
Refactor (ES5 => ES6)

**Did you add tests for your changes?**
N/A, refactor. Existing test suite passes

**If relevant, link to documentation update:**
N/A

**Summary**
Refactor the UglifyJSPlugin to an ES6 class. 

**Does this PR introduce a breaking change?**
Nope

### CODE REVIEW

**Comment by aem** [comment]
as a general rule with these refactors, are we converting concatenated strings to template literals or no? i haven't been but am happy to add that to this PR if we'd prefer those for readability

**Comment by TheLarkInn** [comment]
I think whenever there is some sort of interpolation that can happen, lets use the template literals. However in the case of `\n` I would stick to using quotes. (We can follow up on this more).

**Comment by TheLarkInn** [comment]
AppVeyor is currently down per https://twitter.com/appveyor/status/816518305770971137. Going to merge this.

Looks great.

**Comment by TheLarkInn** [comment]
Thank you for the contribution.

**Pull request merged**
