### PR TITLE
Remove mildly humorous, yet unneeded, comments in contributor.md

### PR DESCRIPTION
**Pull request by TheLarkInn**
**Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Other information**:
This is just a README change so no migrations or anything needed. 

Although I don't mind this comment, some people might take this as snarky and discouraging.

### CODE REVIEW

**Comment by sokra** [comment]
@jhnns

**Comment by TheLarkInn** [comment]
Am I missing an inside joke? 😂

**Comment by TheLarkInn** [comment]
😂I remember now.

**Comment by jhnns** [comment]
It was not intended to be humorous ^^

**Pull request closed without merging**
