### PR TITLE
improve: output.libraryTarget extensibility

### PR DESCRIPTION
**Pull request by gebilaoxiong**
[issues:2701](https://github.com/webpack/webpack/issues/2701)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by gebilaoxiong** [comment]
Submitted for a long time, are there any questions?

**Comment by TheLarkInn** [comment]
Is this just targeting webpack v1? I'm wondering if we'd want this in webpack v2 also. And also does this allow people to write custom libraryTargets and templates for them?

**Comment by gebilaoxiong** [comment]
@TheLarkInn From webpack2 also need to modify the code to see, why code with so many switch inside, it reduced the scalability of the code

**Comment by gebilaoxiong** [comment]
Please, this is just a look code optimization, can deal with as soon as possible

**Pull request closed without merging**
