### PR TITLE
feat: add readonly flag for filesystem cache

### PR DESCRIPTION
**Pull request by SkReD**
This PR introducing `cache.readonly` flag, which will disable modifying stored caches files and allow to work with them in parallel compilations.

https://github.com/webpack/webpack/issues/13581

**What kind of change does this PR introduce?**

feature

**Did you add tests for your changes?**

No. I will add if you think they are required here.

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

`cache.readonly` flag should be documented in https://webpack.js.org/configuration/other-options/#cache section

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Please add test

**Comment by SkReD** [comment]
> Please add test

added test for that cache is not overwritten when `readonly = true`. Probably check for that old cache is reused while in readonly is needed too, but i dont find the way to figure this out from `_modulesCache` instance or any other. Maybe check by compilation time but it feels as fragile condition.

**Review by vankop — COMMENTED** [review]
Not sure that this is the best solution. Maybe better prevent "storing" https://github.com/webpack/webpack/blob/master/lib/cache/PackFileCacheStrategy.js#L1068 
https://github.com/webpack/webpack/blob/master/lib/cache/PackFileCacheStrategy.js#L1094

**Comment by SkReD** [comment]
> Not sure that this is the best solution. Maybe better prevent "storing" https://github.com/webpack/webpack/blob/master/lib/cache/PackFileCacheStrategy.js#L1068
> https://github.com/webpack/webpack/blob/master/lib/cache/PackFileCacheStrategy.js#L1094

Yeah, i think you right. Will update pr as soon as get some free time

**Comment by vankop** [comment]
moved to https://github.com/webpack/webpack/pull/15470

**Pull request closed without merging**
