### PR TITLE
Bump the loader-utils version to 2.0.3

### PR DESCRIPTION
**Pull request by akhilgkrishnan**
**What kind of change does this PR introduce?**

Dependency CVE fix. Then current loader-utils version causing some security issue. This PR is for updating the loader-utils version to 2.0.3

**Did you add tests for your changes?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

### CODE REVIEW

**Comment by alexander-akait** [comment]
It is used in tests

**Comment by ryanmunger** [comment]
Any updates on when this will be merged in?

**Comment by akhilgkrishnan** [comment]
> It is used in tests

Ohh I see

**Comment by akhilgkrishnan** [comment]
@alexander-akait Can you review this PR once again

**Comment by TheLarkInn** [comment]
Thanks for this @akhilgkrishnan

**Comment by WofWca** [comment]
> It is used in tests

So the code generated by Webpack is not affected?

**Comment by alexander-akait** [comment]
@WofWca yes

**Pull request merged**
