### PR TITLE
use propertyAccess to generate .catch code

### PR DESCRIPTION
**Pull request by aleen42**
**What kind of change does this PR introduce?**

bugfix for breaking code under ES3 when access `.catch` of promises, which is related to #13972

### CODE REVIEW

**Comment by ellenmartin22** [comment]
> 
> 
> @aleen42 Thanks for your update.
> 
> I labeled the Pull Request so reviewers will review it again.
> 
> @sokra Please review the new changes.

**Comment by aleen42** [comment]
Any progress?

**Comment by aleen42** [comment]
> @sokra I have used `yarn run test:basic -u` to update snapshots, but it seems that the checking process is still failed. BTW, because I can't request `raw.githubusercontent.com` without proxy, and it means that there is some unexpected error when fetching https://raw.githubusercontent.com/webpack/webpack/main/CODE_OF_CONDUCT.md.

@alexander-akait I tried, but it failed.

**Comment by alexander-akait** [comment]
Just update snpahosts

**Comment by aleen42** [comment]
> Just update snapshots

I have run the command `npm run test:update-snapshots`, and it does update a wrong snapshot:

```diff
Snapshot name: `StatsTestCases should print correct stats for real-content-hash 1`

- Snapshot  - 4
+ Received  + 4

@@ -1,16 +1,16 @@
  a-normal:
    assets by path *.js 3.23 KiB
-     asset 72965507c7b4c0b4fc29-729655.js 2.75 KiB [emitted] [immutable] [minimized] (name: runtime)
+     asset d540efec41d30bcd0b3b-d540ef.js 2.75 KiB [emitted] [immutable] [minimized] (name: runtime)
      asset a6d438a0676f93383d79-a6d438.js 262 bytes [emitted] [immutable] [minimized] (name: lazy)
      asset cbb9c74e42f00ada40f7-cbb9c7.js 212 bytes [emitted] [immutable] [minimized] (name: index)
      asset 666f2b8847021ccc7608-666f2b.js 21 bytes [emitted] [immutable] [minimized] (name: a, b)
    assets by chunk 20.4 KiB (auxiliary name: lazy)
      asset 89a353e9c515885abd8e.png 14.6 KiB [emitted] [immutable] [from: file.png] (auxiliary name: lazy)
      asset 7382fad5b015914e0811.jpg?query 5.89 KiB [cached] [immutable] [from: file.jpg?query] (auxiliary name: lazy)
    asset 7382fad5b015914e0811.jpg 5.89 KiB [emitted] [immutable] [from: file.jpg] (auxiliary name: index)
-   Entrypoint index 2.96 KiB (5.89 KiB) = 72965507c7b4c0b4fc29-729655.js 2.75 KiB cbb9c74e42f00ada40f7-cbb9c7.js 212 bytes 1 auxiliary asset
+   Entrypoint index 2.96 KiB (5.89 KiB) = d540efec41d30bcd0b3b-d540ef.js 2.75 KiB cbb9c74e42f00ada40f7-cbb9c7.js 212 bytes 1 auxiliary asset
    Entrypoint a 21 bytes = 666f2b8847021ccc7608-666f2b.js
    Entrypoint b 21 bytes = 666f2b8847021ccc7608-666f2b.js
    runtime modules 7.29 KiB 9 modules
    orphan modules 23 bytes [orphan] 1 module
    cacheable modules 514 bytes (javascript) 26.3 KiB (asset)
@@ -25,19 +25,19 @@
        ./a/file.jpg?query 42 bytes (javascript) 5.89 KiB (asset) [built] [code generated]
    a-normal (webpack x.x.x) compiled successfully in X ms

  b-normal:
    assets by path *.js 3.23 KiB
-     asset 72965507c7b4c0b4fc29-729655.js 2.75 KiB [emitted] [immutable] [minimized] (name: runtime)
+     asset 5e08234081c9df0a6af7-5e0823.js 2.75 KiB [emitted] [immutable] [minimized] (name: runtime)
      asset a6d438a0676f93383d79-a6d438.js 262 bytes [emitted] [immutable] [minimized] (name: lazy)
      asset cbb9c74e42f00ada40f7-cbb9c7.js 212 bytes [emitted] [immutable] [minimized] (name: index)
      asset 666f2b8847021ccc7608-666f2b.js 21 bytes [emitted] [immutable] [minimized] (name: a, b)
    assets by chunk 20.4 KiB (auxiliary name: lazy)
      asset 89a353e9c515885abd8e.png 14.6 KiB [emitted] [immutable] [from: file.png] (auxiliary name: lazy)
      asset 7382fad5b015914e0811.jpg?query 5.89 KiB [cached] [immutable] [from: file.jpg?query] (auxiliary name: lazy)
    asset 7382fad5b015914e0811.jpg 5.89 KiB [emitted] [immutable] [from: file.jpg] (auxiliary name: index)
-   Entrypoint index 2.96 KiB (5.89 KiB) = 72965507c7b4c0b4fc29-729655.js 2.75 KiB cbb9c74e42f00ada40f7-cbb9c7.js 212 bytes 1 auxiliary asset
+   Entrypoint index 2.96 KiB (5.89 KiB) = 5e08234081c9df0a6af7-5e0823.js 2.75 KiB cbb9c74e42f00ada40f7-cbb9c7.js 212 bytes 1 auxiliary asset
    Entrypoint a 21 bytes = 666f2b8847021ccc7608-666f2b.js
    Entrypoint b 21 bytes = 666f2b8847021ccc7608-666f2b.js
    runtime modules 7.29 KiB 9 modules
    orphan modules 19 bytes [orphan] 1 module
    cacheable modules 469 bytes (javascript) 26.3 KiB (asset)
```

**Comment by aleen42** [comment]
@alexander-akait @sokra I have updated the snapshot, and should I care about the problem of code coverage?

**Review by sokra — APPROVED** [review]

**Comment by sokra** [comment]
Thanks

**Pull request merged**
