### PR TITLE
Refactor chunk graph

### PR DESCRIPTION
**Pull request by sokra**
**What kind of change does this PR introduce?**
big refactoring

**Did you add tests for your changes?**
yes

**If relevant, link to documentation update:**
TODO

**Summary**
Chunks are now always in ChunkGroups
ChunkGroups have parents and children, Chunks no longer have this
AsyncDependenciesBlocks point to a ChunkGroup instead of a list of chunks
Entrypoint is now a ChunkGroup (extends from it)
move stuff graph modification methods into GraphHelpers
Change chunk id recording to source-based
Chunks have parents, siblings and children in Stats
rename AutomaticCommonsChunksPlugin to SplitChunksPlugin
add request property to origin (ChunkGroup)
remove moveToParent from AggressiveMergingPlugin
fix issues with AggressiveSplittingPlugin
remove CommonsChunkPlugin
add optimization.runtimeChunk (RuntimeChunkPlugin)
fix a filename bug for initial chunks
remove extract-text-webpack-plugin from test suite
add DebugHash to help debugging hash issues
fix issues with entry modules in different chunk as runtime
redo optimization.splitChunks options
Compilation.entrypoints is now a Map
Compilation.chunkGroups has been added
remove some unittests
update examples
update tests with CommonsChunkPlugin

**Does this PR introduce a breaking change?**
yes

**Other information**

### CODE REVIEW

**Comment by ooflorent** [comment]
I wanted to benchmark this PR so I ran it on a _medium_ (yes, it is biased) project: ~500 modules, 13 async chunks, 1 entry. For the purpose of this benchmark I disabled linting and minification and enable loader cache. For each tested release, I ran the build to warm up the cache and then did 10 compilation. The below results are the median builds (source map are omitted from the output).

### Configs and outputs

**webpack@3.10.0**

```js
const path = require("path")
const webpack = require("webpack")
module.exports = {
  devtool: "source-map",
  entry: {
    client: ["./client/client.js"],
  },
  output: {
    path: path.resolve(__dirname, "build/client"),
    filename: "[name].[chunkhash:8].js",
    chunkFilename: "[name].[chunkhash:8].js",
  },
  optimization: {
    minimize: false,
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: "babel-loader",
        options: {
          cacheDirectory: true,
        },
      },
    ],
  },
  plugins: [
    new webpack.EnvironmentPlugin({
      NODE_ENV: "production",
    }),
    new webpack.optimize.ModuleConcatenationPlugin(),
    new webpack.optimize.CommonsChunkPlugin({
      name: "vendor",
      minChunks(module) {
        return module.context && module.context.includes("node_modules")
      },
    }),
  ]
}
```

```
Time: 11718ms
                 Asset     Size  Chunks                    Chunk Names
    fr.a00b425f.js.map  87.6 kB       0  [emitted]         fr
        fr.a00b425f.js  64.8 kB       0  [emitted]         fr
         2.13f67cf0.js   184 kB       2  [emitted]
         3.83bb8fad.js  59.9 kB       3  [emitted]
         4.c9c7396d.js   159 kB       4  [emitted]
         5.db441e78.js   103 kB       5  [emitted]
         6.dd7ae03b.js   101 kB       6  [emitted]
         7.d45be4c3.js  95.9 kB       7  [emitted]
         8.e14daaaa.js  37.2 kB       8  [emitted]
         9.d422e43a.js  15.6 kB       9  [emitted]
        10.edaa0c6b.js  4.92 kB      10  [emitted]
        11.6fc20a85.js  10.3 kB      11  [emitted]
        12.dbf2bb15.js  4.94 kB      12  [emitted]
        13.351025f1.js     5 kB      13  [emitted]
    client.43db4c13.js  78.6 kB      14  [emitted]         client
    vendor.7dddd34e.js   895 kB      15  [emitted]  [big]  vendor
        en.5a744a87.js  67.7 kB       1  [emitted]         en
```

**webpack@4.0.0-alpha.4**

```js
const path = require("path")
const webpack = require("webpack")
module.exports = {
  mode: "production",
  devtool: "source-map",
  entry: {
    client: ["./client/client.js"],
  },
  output: {
    path: path.resolve(__dirname, "build/client"),
    filename: "[name].[chunkhash:8].js",
    chunkFilename: "[name].[chunkhash:8].js",
  },
  optimization: {
    minimize: false,
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: "babel-loader",
        options: {
          cacheDirectory: true,
        },
      },
    ],
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      name: "vendor",
      minChunks(module) {
        return module.context && module.context.includes("node_modules")
      },
    }),
  ]
}
```

```
Time: 6702ms
                 Asset      Size  Chunks                    Chunk Names
        fr.139baf05.js  63.8 KiB       0  [emitted]         fr
         2.833db2c3.js  4.86 KiB       2  [emitted]
         3.902389ab.js   179 KiB       3  [emitted]
         4.a500006e.js  58.6 KiB       4  [emitted]
         5.9fff8a74.js   155 KiB       5  [emitted]
         6.6159b50a.js  15.5 KiB       6  [emitted]
         7.19df1f42.js   101 KiB       7  [emitted]
         8.0e3a4d5c.js  98.9 KiB       8  [emitted]
         9.a025e9a8.js  4.93 KiB       9  [emitted]
        10.64f8adcb.js  10.1 KiB      10  [emitted]
        11.438bc08a.js  36.4 KiB      11  [emitted]
        12.1c61e294.js  4.94 KiB      12  [emitted]
        13.4ec09eeb.js  93.6 KiB      13  [emitted]
    client.8f118fe1.js  77.6 KiB      14  [emitted]         client
    vendor.1acefb47.js   874 KiB      15  [emitted]  [big]  vendor
        en.34fc4a48.js  66.6 KiB       1  [emitted]         en
```

**webpack#b28435eb3249348c02040c56ad3741fcee8530e9**

```js
const path = require("path")
const webpack = require("webpack")
module.exports = {
  mode: "production",
  devtool: "source-map",
  entry: {
    client: ["./client/client.js"],
  },
  output: {
    path: path.resolve(__dirname, "build/client"),
    filename: "[name].[chunkhash:8].js",
    chunkFilename: "[name].[chunkhash:8].js",
  },
  optimization: {
    minimize: false,
    runtimeChunk: true,
    splitChunks: {
      chunks: "all",
    },
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: "babel-loader",
        options: {
          cacheDirectory: true,
        },
      },
    ],
  },
}
```

```
Time: 6459ms
                         Asset      Size  Chunks                    Chunk Names
             en~fr.d41d6398.js  57.6 KiB       0  [emitted]         en~fr
                 2.e4f01819.js  40.3 KiB       2  [emitted]
                 3.368d90ba.js  46.7 KiB       3  [emitted]
                fr.4843eb35.js  6.15 KiB       4  [emitted]         fr
                en.62ca3908.js  8.98 KiB       5  [emitted]         en
                 6.ce94e965.js  4.86 KiB       6  [emitted]
                 7.d5b0763d.js   139 KiB       7  [emitted]
                 8.590975f5.js  18.4 KiB       8  [emitted]
                 9.2ec81088.js   108 KiB       9  [emitted]
                10.cf1ecf9a.js  15.5 KiB      10  [emitted]
                11.3ee69bd6.js  54.1 KiB      11  [emitted]
                12.d72bc141.js  52.3 KiB      12  [emitted]
                13.202da64b.js  4.93 KiB      13  [emitted]
                14.6bfe698d.js  10.1 KiB      14  [emitted]
                15.5cf9fa0c.js  36.2 KiB      15  [emitted]
                16.6b850af7.js  4.94 KiB      16  [emitted]
                17.770b75d6.js  46.9 KiB      17  [emitted]
    client-runtime.8a377460.js  7.88 KiB      18  [emitted]         client-runtime
    vendors~client.8b1c1eb8.js   860 KiB      19  [emitted]  [big]  vendors~client
            client.44ae8fdc.js  77.8 KiB      20  [emitted]         client
                 1.6029bcfd.js  46.5 KiB       1  [emitted]
```

### Results

| Version | Time |
| --- | --- |
| 3.10.0 | 11718ms |
| 4.0.0-alpha4 | 6702ms |
| #6341 | 6459ms |

Please also note the webpack 4 is doing much more than 3.10.

**Comment by theKashey** [comment]
So, I do have 3 async chucks, all using some big library, unused by the app entry.
CommonChunks plugin will aggregate it, as long it is common for >2 chunks. Bad.
Without common chunk it will be embedded to each chuck, thus duplicated tree times. Bad/
As I understand - the new approach will solve this task, by autosplitting in more than one chunk, and requiring more that one common chunk.

So - in @ooflorent example webpack produced 4 more chunks, but vendors~client is still just huge.

**Comment by ooflorent** [comment]
@theKashey actually the vendor chunk is not that huge; I would even say it is _small_. The above numbers are from non-minified files. With gzip compression the vendor chunk is ~120kB. There 4 packages in it: react, react-dom, apollo and styled-components. All chunks uses these packages (except react-dom which is required by the entry point).

**Comment by ooflorent** [comment]
By the way, my post wasn’t here to show if this plugin could bring relevant size optimization but to see if the refactoring was impacting build times. I was expecting file size not to change and I must admit that I’m happy with the improvement.

**Comment by theKashey** [comment]
I was actually quite hard to understand how 300 files change the game rules. The gist you provided did clarify (almost) all the things. Thank you @TheLarkin. 
Actually this change promising to be so good that I expected to saw “the magic” happening just here, just now.

**Comment by ooflorent** [comment]
👍

**Comment by pi0** [comment]
😍 🍷

**Comment by clarkdo** [comment]
🎉🎉🎉

**Pull request merged**
