### PR TITLE
Feature: Make ExtendedAPIPlugin expose chunkname.

### PR DESCRIPTION
**Pull request by Waidd**
**What kind of change does this PR introduce?**
Feature

**Did you add tests for your changes?**
No. There are currently no tests for this plugin and I'm not comfortable enough with this project to write them from scratch. I could use some help on this point.

**Summary**
Make ExtendedAPIPlugin expose `chunkname`, same way as `hash`.

**Does this PR introduce a breaking change?**
Should not.

### CODE REVIEW

**Comment by richardngn** [comment]
👍

**Comment by sokra** [comment]
Take a look at the `tests` folder. There is a readme telling you how to write tests.

Add a testcase into `test/configCases`.

see also https://github.com/webpack/webpack/tree/028c51301733836abbedc88be7483af2623f5943/test/configCases/parsing/extended-api

**Comment by Waidd** [comment]
@sokra Thanks for your review, I might have missed config cases tests. I updated my pull request.

**Comment by sokra** [comment]
Thanks

**Pull request merged**
