### PR TITLE
Handle cryptic error message being thrown

### LINKED ISSUE #9295: cryptic error message on misconfigured config file
# Bug report

**What is the current behavior?**

If the webpack.config.js exports an array with non continuous integer indices. A cryptic error message gets shown.

Example (paths truncated):
```
./node_modules/webpack-cli/bin/cli.js:281
				throw err;
				^

TypeError: Cannot read property 'hooks' of undefined
    at new MultiCompiler (./node_modules/webpack/lib/MultiCompiler.js:37:13)
    at webpack (./node_modules/webpack/lib/webpack.js:35:14)
    at processOptions (./node_modules/webpack-cli/bin/cli.js:272:16)
    at ./node_modules/webpack-cli/bin/cli.js:388:3
    at Object.parse (./node_modules/yargs/yargs.js:567:18)
    at ./node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (./node_modules/webpack-cli/bin/cli.js:390:3)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (./node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (./node_modules/@symfony/webpack-encore/bin/encore.js:63:12)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
error Command failed with exit code 1.
```

This is the line causing the error: https://github.com/webpack/webpack/blob/9eb078b6f691e65bcc3b096fbbebc2e19604da43/lib/MultiCompiler.js#L37

The array gets loaded via https://github.com/webpack/webpack-cli/blob/d7cdab9e5f5e166daff17d0cdeaf24f65a3be947/bin/utils/convert-argv.js#L116

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a webpack projects with `module.exports = [ test1,, test2 ];`.
Notice the empty array entry because of the double comma.

While it was my mistake to have the extra comma in there, it took me a few hours to find it and the error message was not helpful.

**What is the expected behavior?**

Webpack should handle webpack.config.js files with exported arrays that have non continuous integer indices.

I guess it could be fixed at either of the two code locations, either make the MultiCompiler not assume continuous array indices anymore or sanitise the input and show proper error messages.

**Other relevant information:**
webpack version:  webpack@4.34.0
Node.js version: v12.4.0
Operating System: 
	ProductName:	Mac OS X
	ProductVersion:	10.13.6
	BuildVersion:	17G65

Additional tools: webpack-cli@3.3.4, webpack-encore@0.27.0

### PR DESCRIPTION
**Pull request by jamesgeorge007**
misconfigured config file

Fixes #9295 

**What kind of change does this PR introduce?**
refactoring

**Did you add tests for your changes?**
N/A

**Does this PR introduce a breaking change?**
Nope

**What needs to be documented once your changes are merged?**
Nil

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
@sokra I'm not that familiar with the code-base. Can you throw light on how it should be regarding writing the test case :thinking:

**Comment by sokra** [comment]
Run `yarn setup` first.

Then you should be able to run the Validation tests with `yarn jest Validation --watch -u`. The `-u` updates the snapshots automatically.

Copy one of the tests in the file and create a invalid config like in the issue. Running the test will update the snapshot to the expected error message.

**Comment by jamesgeorge007** [comment]
@sokra Still I'm not able to connect the dots as per the context :confused: Running the above-mentioned scripts creates a couple of untracked files which seem to be irrelevant. It would be great if you could be specific on how to curate the test case for this change :clap:

**Comment by sokra** [comment]
see https://github.com/webpack/webpack/pull/9306/commits/226e8ce8fd9fee33e8d8b37dd4d7d9c24483b4f9

**Comment by jamesgeorge007** [comment]
So are we all set to go ahead?

**Comment by sokra** [comment]
Yep, thanks

**Pull request merged**
