### PR TITLE
feat: add watching property to compiler

### LINKED ISSUE #11481: Get current Watching's instance from compiler object
## Feature request
Access instance of current [`Watching`](https://webpack.js.org/api/node/#watching) from [`Compiler`](https://webpack.js.org/api/node/#compiler-instance) object itself.

**What is the expected behavior?**
```
const compiler = webpack({...})
const watching = compiler.watch(...);
const watchingFromCompiler = compiler.watching;
// expect(watching === watchingFromCompiler).toBe(true)
```

**What is motivation or use case for adding/changing the behavior?**
I am developing Interactive mode for `watch` for `webpack-cli` using Plugin API.
I want to implement a feature to stop current compiling round (where `watching.invalidate()` would help) as well as a feature to start new watching (where `watching.close` would help).

**How should this be implemented in your opinion?**
Whenever `compiler.watch` is called, update `compiler.watching`with current watching.

**Are you willing to work on this yourself?**
yes (need pointers on where to implement it)

### PR DESCRIPTION
**Pull request by rishabh3112**
Resolves #11481 

**What kind of change does this PR introduce?**
feature

**Did you add tests for your changes?**
No

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
New `compiler.watching` property.

### CODE REVIEW

**Comment by rishabh3112** [comment]
If required, I will work on it further after a couple of days.

**Review by sokra — CHANGES_REQUESTED** [review]
Also make sure to clear the watching property again when the watching is closed:

here: https://github.com/webpack/webpack/blob/master/lib/Watching.js#L315

**Review by sokra — CHANGES_REQUESTED** [review]
And also initialize this.watching to undefined in the constructor

**Comment by rishabh3112** [comment]
friendly ping @sokra

**Review by sokra — APPROVED** [review]

**Comment by sokra** [comment]
Thanks

**Pull request merged**
