### PR TITLE
fix: Fixed apply event callback and optimizing callback event type

### PR DESCRIPTION
**Pull request by nuintun**
**What kind of change does this PR introduce?**
 
bugfix: hot event optimizing

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

No

Refs: https://github.com/webpack/webpack/pull/15655

### CODE REVIEW

**Comment by alexander-akait** [comment]
Sorry for delay

**Comment by nuintun** [comment]
@alexander-akait 

> I think we have wrong callback type now

What is the correct callback type now ?

https://webpack.js.org/api/hot-module-replacement/#apply

image

It's still use old callback type in the docs.

**Comment by alexander-akait** [comment]
I see, not sure why typescript doesn't catch this in our files, looking at this, but yeah, your fix is valid

**Review by alexander-akait — APPROVED** [review]

**Review by TheLarkInn — APPROVED** [review]

**Comment by TheLarkInn** [comment]
@nuintun congratulations on your first contribution to webpack 🎉

**Pull request merged**
