### PR TITLE
Fix error on empty array config

### PR DESCRIPTION
**Pull request by sharang-d**
Fixes https://github.com/webpack/webpack/issues/1455

### CODE REVIEW

**Comment by sharang-d** [comment]
This seems to solve the problem described in https://github.com/webpack/webpack/issues/1455.
I tired writing a test for it under `test/configCases/simple/empty-array-config` by copying `test/configCases/simple/empty-config` and changing the content of webpack.config.js to `module.exports = [];` but something seems to be going wrong. 
I thus have two questions.. 
1. Does this fix require a test?
2. If yes then what should I check for in it? Also some pointers to similar existing tests/asserts will help.

Thanks in advance. @sokra

**Comment by sharang-d** [comment]
cc: @bebraw

**Comment by sokra** [comment]
@ksonnad does this fix your issue?

**Comment by ksonnad** [comment]
Yep.

**Comment by sharang-d** [comment]
@sokra What needs to be done here?

**Comment by sokra** [comment]
Nothing, thanks

**Pull request merged**
