### PR TITLE
Remove overrides/overridables option for ModuleFederationPlugin

### PR DESCRIPTION
**Pull request by okmttdhr**
@sokra @ScriptedAlchemy 

It looks like that `ModuleFederationPlugin` has options, `overrides` and `overridables`.
https://github.com/webpack/webpack/blob/master/types.d.ts#L3840-L3848
https://github.com/webpack/webpack/blob/master/lib/container/ModuleFederationPlugin.js#L79
https://github.com/webpack/webpack/blob/master/lib/container/ModuleFederationPlugin.js#L94

But shouldn't these options be removed for `ModuleFederationPlugin` (=high level API)?

We don't need these options anymore because we have the `shared` option already.
https://github.com/webpack/webpack/issues/10352#issuecomment-584822116

(This PR keeps low level API (like `ContainerPlugin`/`ContainerReferencePlugin`) have `overrides`/`overridables` internally)

**What kind of change does this PR introduce?**

refactoring

**Did you add tests for your changes?**

Existing & No need
(I don't see any tests for `ModuleFederationPlugin` with `overrides`/`overridables` option. So this PR should increase test coverage)

**Does this PR introduce a breaking change?**

Maybe yes, but I suppose we have never used `overrides`/`overridables` anywhere for `ModuleFederationPlugin`.

**What needs to be documented once your changes are merged?**

No need
https://webpack.js.org/concepts/module-federation/#building-blocks

### CODE REVIEW

**Comment by sokra** [comment]
These options were intended for finer control over shared modules. Like make some modules only overidable instead of shared because these container is always used within a shell which always provides these modules.

**Comment by okmttdhr** [comment]
@sokra 
Let me ask you one thing.

> These options were intended for finer control over shared modules

The good thing about this is that we can explicitly represent how the module will be used by specifying overrides and overridables?

Using shared, is there any effect on security, compilation results, etc.?
If any, I'd love to learn about it!

**Comment by sokra** [comment]
Security: you should trust imported containers as they could execute any code.

It has influence on the compilation result. More chunks are created and the entrypoint to a shared module is less optimized.

**Comment by ScriptedAlchemy** [comment]
Use the two independently if you want to separated overrides from overridables . Module Federation plugin should stay as is

**Comment by okmttdhr** [comment]
Thank you for your answer.
Closing this PR

**Pull request closed without merging**
