### PR TITLE
Use MD4 for hashing

### PR DESCRIPTION
**Pull request by ooflorent**
**What kind of change does this PR introduce?**

build related change

**Did you add tests for your changes?**

yes

**If relevant, link to documentation update:**

n/a

**Summary**

`md4` is faster than `md5`. Since webpack doesn't need secure hashes, `md4` could be used to improve the build performance.

**Does this PR introduce a breaking change?**

no

### CODE REVIEW

**Comment by montogeek** [comment]
How much is improved?

**Comment by ooflorent** [comment]
`md4` is about 20% faster than `md5`. On large builds it could lead to a 2-3% overall improvement.

**Comment by probablyup** [comment]
If you're switching hash functions, murmur2 is well-loved for a good balance between speed and uniqueness on non-cryptographic use cases. I tried looking around and couldn't find any direct comparison benchmarks though.

Here's a JS implementation example: https://github.com/emotion-js/emotion/blob/master/packages/emotion-utils/src/hash.js

**Comment by sokra** [comment]
Thanks

**Comment by Hoten** [comment]
Great idea!

**Pull request merged**
