### PR TITLE
fix: use streams for Tracer in ProfilingPlugin

### PR DESCRIPTION
**Pull request by DanielRuf**
**What kind of change does this PR introduce?**

Bugfix

**Did you add tests for your changes?**

No

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

Not sure

Fixes https://github.com/webpack/webpack/issues/7450

### CODE REVIEW

**Comment by samccone** [comment]
We are not using streams here since a *lot* of logs are written and the overhead of streaming these results is significant and slows webpack down a lot.

**Comment by DanielRuf** [comment]
Ok but it seems this setting + fs.writeStream and webpacks compilation are problematic (and in sum does not make so much sense to me, it always finishes after 140 entries and does not keep the files open).

What would be the right solution then? Set the `keepOpen` of fs.createWriteStream?

**Comment by samccone** [comment]
I agree that there is some bug where the final output is not correctly flushing :) I am looking into it right now :D 

Thanks so much for the initial investigation, let's see where we end up.

**Comment by DanielRuf** [comment]
Meant `autoclose`, mixed it with other things probably.

**Pull request closed without merging**
