### PR TITLE
[WIP] Fix sync loading Module Federation

### PR DESCRIPTION
**Pull request by crodriguez-plitzi**
**What kind of change does this PR introduce?**

refactoring to allow MF to be loaded synced

**Did you add tests for your changes?**

not yet

**Does this PR introduce a breaking change?**

the impact should be low, but will be good to update all plugins that are using MF at the same time than the host

**What needs to be documented once your changes are merged?**

* remotes will be managed as promises in order to allow initial loads and avoid the bootstrap hack way that was breaking that we can manage the package as NPM library

### CODE REVIEW

**Comment by crodriguez-plitzi** [comment]
@ScriptedAlchemy what do you think about these changes,

**Comment by crodriguez-plitzi** [comment]
@sokra or @alexander-akait could you suggest me what unit tests i will need to do for this change to get this approved ?

thx

**Comment by ScriptedAlchemy** [comment]
Can you provide a config example of how this would be used? 

Would this impact any existing configuration of module federation? 

@sokra  any thoughts on this implementation?

**Comment by ScriptedAlchemy** [comment]
@crodriguez-plitzi  please sign CLA as bot is requesting

**Comment by crodriguez-plitzi** [comment]
closed due problems in 1 or 2 commits and CLA, the new MR with CLA fixed is 
https://github.com/webpack/webpack/pull/15271

**Pull request closed without merging**
