### PR TITLE
`electron-main` and `electron-renderer` targets

### PR DESCRIPTION
**Pull request by chentsulin**
Not sure if everything done right. please check, thanks!

### CODE REVIEW

**Comment by sokra** [comment]
Here is a list of modules available in both environments: http://electron.atom.io/docs/v0.33.0/#modules-for-the-main-process

So best if we externalize all modules in the `electron` target and a smaller list in `electron-main` and `electron-renderer`.

Both can use `NodeTemplatePlugin`. This uses `require` to load code-splitting chunks.

So everything is identical except a different list of external modules. Maybe you can solve this without code duplication.

**Comment by chentsulin** [comment]
I try this in my [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate)

if I change from

`new JsonpTemplatePlugin(options.output),`

to

`new NodeTemplatePlugin(options.output, true),`

in my `webpack-target-electron-renderer`. It will get a

`Uncaught ReferenceError: hotDownloadManifest is not defined` error

Any ideas?

**Comment by sokra** [comment]
Thanks

**Comment by chentsulin** [comment]
@sokra will this commit be included in the next 1.x release or it's will only be a feature in 2.0?

**Pull request merged**
