### PR TITLE
fix(JavascriptModulesPlugin): don't emit empty chunks

### PR DESCRIPTION
**Pull request by zhoulinxiang**
**What kind of change does this PR introduce?**

- [ ] Bugfix
Try to fix [#7300](https://github.com/webpack/webpack/issues/7300), similar to [#8124](https://github.com/webpack/webpack/pull/8124), but that is out of date.

**Did you add tests for your changes?**
[#7386](https://github.com/webpack/webpack/pull/7386)
[#7601](https://github.com/webpack/webpack/pull/7601)

**Does this PR introduce a breaking change?**

- [ ] No

**What needs to be documented once your changes are merged?**

- [ ] None

### CODE REVIEW

**Comment by hiroppy** [comment]
@zhoulinxiang Thank you for helping, please sign. https://github.com/webpack/webpack/pull/9040#issuecomment-482800748

**Comment by zhoulinxiang** [comment]
@hiroppy  Signed, thank you.

**Comment by evilebottnawi** [comment]
All ok, thanks!

**Comment by zhoulinxiang** [comment]
@evilebottnawi 
Any questions? Can it be merged?

**Comment by evilebottnawi** [comment]
All ok, wait @sokra for review/merge

**Comment by sokra** [comment]
added in `next` branch

**Pull request closed without merging**
