### PR TITLE
brackets are unnecessary here

### PR DESCRIPTION
**Pull request by zwhitchcox**
javascript will just append resource to the existing array, if it is not an array

### CODE REVIEW

**Comment by TheLarkInn** [comment]
Please update branch, as well as add a friendly sanity test to ensure this! :-D

**Comment by zwhitchcox** [comment]
Hey @TheLarkinn.....met you at l nation.is this is so weird...just gonna close this, as we're switching to webpack 2 anyway, and this change doesn't really matter

**Comment by TheLarkInn** [comment]
:-D!!! Oh Awesome! Hahaha nice to meet you in the Github world now. I'm trying to go through PR's since they haven't had as much love in the past (everythings piling up lol). But feel free to drop by github.com/webpack/webpack.js.org if you wanna do some docs :smirk: haha.

**Comment by zwhitchcox** [comment]
Sure! I would like to do that provided I can understand how it works, as that was one of the pain points for me in the current version...literally went through every line of code to try to figure out how it works XD I did learn a ton though!

**Pull request closed without merging**
