### PR TITLE
add experimental WebAssembly support

### PR DESCRIPTION
**Pull request by sokra**
**What kind of change does this PR introduce?**
feature

**Did you add tests for your changes?**
yes

**If relevant, link to documentation update:**
TODO

**Summary**
add `Module.type`
add wasm, json, js/auto and js/esm types
allow to set type by rules
set default type by extension
allow Main/ChunkTemplate to generate multiple assets
add more parsers for different types
parser plugins should now add by module type

**Does this PR introduce a breaking change?**
yes

**Other information**

### CODE REVIEW

**Comment by rhmoller** [comment]
Hi,

I have been experimenting with this branch. It seems to build fine but webpack-dev-server is unable to run it. The .module.wasm gets served as application/octet-stream instead of application/wasm.

First the mime module does not know the .wasm extension and secondly the middleware.js appends "; charset=UTF-8" to all content types which it should not do for wasm.

See https://github.com/rhmoller/webpack-webassembly-tester

**Comment by TheLarkInn** [comment]
Thanks for this. I'm going to have @shellscape dig into this specifically for WDS/WDM

**Comment by shellscape** [comment]
Once this is merged we'll have to setup a test in WDS that fails and I can work backwards from there. I don't have any web assembly experience so I'm not sure how to setup that up at the moment.

**Comment by TheLarkInn** [comment]
@rhmoller, do you have interest in assisting @shellscape with setting this up? It would be very beneficial to have the support for WDS aw soon as possible even if it merges only to the webpack/webpack#next branch.

**Comment by rhmoller** [comment]
Sure, I would love to help moving this forward.
I guess it will start with an extra test for the .wasm extension around here
https://github.com/webpack/webpack-dev-middleware/blob/master/test/Server.test.js#L57-L62

**Comment by rhmoller** [comment]
I have a created an issue for the dev-server issue here. I will add details and work on a pull request there.

https://github.com/webpack/webpack-dev-middleware/issues/229

**Pull request merged**
