### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by iamcz**
**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe: typo correction

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the following... 
- Impact:
- Migration path for existing applications: 
- Github Issue(s) this is regarding:

**Other information**:

### CODE REVIEW

**Comment by sokra** [comment]
The function name is called `e` + the comment `nsure`...

**Comment by sokra** [comment]
The file is generated. You need to change the generation code. Somewhere in `lib/dependencies/RequireEnsureDependency` or similar

**Comment by iamcz** [comment]
thanks @sokra i'll take another look

**Comment by sokra** [comment]
done

**Pull request closed without merging**
