### PR TITLE
ES6 refactoring in DependenciesBlock and Module

### PR DESCRIPTION
**Pull request by smelukov**
**What kind of change does this PR introduce?**

Refactoring of Webpack Core

**Did you add tests for your changes?**

Yes

**Summary**

More ES6 code in Webpack Core (`DependenciesBlock` and `Module`)

Inspired #4099

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by smelukov** [comment]
о_О I did not add/change any code logic, but @webpack-bot tells me `It looks like this Pull Request doesn't include enough test cases.`
How can it be?

**Comment by michael-ciniawsky** [comment]
@smelukov This message is based on Code Coverage :) (`-0.05%`)

**Comment by smelukov** [comment]
@michael-ciniawsky I understand :)
But I don't understand `why`.
The methods and its logic still the same.

**Comment by sokra** [comment]
The Code Coverage for the code you refactored was low before, so if you touch it codecov reports also low coverage for your PR. For the ES6 refactoring PRs that's fine for me. But thanks for adding test cases 😄. Bot seem to have a positive effect 🎉.

**Comment by sokra** [comment]
Thanks

**Pull request merged**
