### PR TITLE
fix #16561

### LINKED ISSUE #16561: path-prefix for define/require for amd library type
## Feature request

**What is the expected behavior?**
call define from specify object

**What is motivation or use case for adding/changing the behavior?**
complex app may has many libraries and sometimes use window object to mapping libraries for example `window['requirejs']` or `window['jQuery3']`

**How should this be implemented in your opinion?**
like option for amd plugin `globalObject`
if option specifed before define/require put `${globalObject}.`

**Are you willing to work on this yourself?**
yes

### PR DESCRIPTION
**Pull request by long76**
**What kind of change does this PR introduce?**
see #16561

**Did you add tests for your changes?**
no

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**
add `globalObject` option to page with amd library plugin

### CODE REVIEW

**Comment by long76** [comment]
please fix last 2 lint error i worked with ide github

**Review by alexander-akait — COMMENTED** [review]
Please add tests

**Comment by long76** [comment]
> Please add tests

ok i need some time

**Comment by long76** [comment]
> Please add tests

done, param name changed to `amdContainer`

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
@TheLarkInn Makse sense to look at this too, don't see somethinb bad here

**Comment by alexander-akait** [comment]
@TheLarkInn Unmerged due `3 failing checks`, but there are no problems with other tests

**Comment by long76** [comment]
> @TheLarkInn Unmerged due `3 failing checks`, but there are no problems with other tests

I can try add more tests for increasing coverage

**Comment by long76** [comment]
@alexander-akait please approve to run second part workflow tests

**Comment by alexander-akait** [comment]
@long76 Sorry, some conflicts, can you rebase and we will merge, sorry for that and thank you

**Comment by long76** [comment]
> @long76 Sorry, some conflicts, can you rebase and we will merge, sorry for that and thank you

all right) done wait checking

**Pull request merged**
