### PR TITLE
Check for (g/s)etter support, not Object.defineProperty

### PR DESCRIPTION
**Pull request by SimenB**
As discussed in #2085

### CODE REVIEW

**Comment by sokra** [comment]
You need to put the function into the `module.exports = function() {` block. Only these block is emitted into the runtime.

**Comment by SimenB** [comment]
Yeah, I noticed! Running the tests locally now :smile:

**Comment by SimenB** [comment]
Done.

BTW, the examples-tests fails for me. Any idea why?

image

**Comment by sokra** [comment]
npm is weird and installs `webpack` inside `webpack/node_modules`. delete it.

**Comment by sokra** [comment]
Instead clone the webpack repo into a `node_modules` folder, or `npm link` webpack into itself (https://github.com/webpack/webpack/blob/master/.travis.yml#L15-L16).

**Comment by SimenB** [comment]
Ah, fancy!

**Comment by wkwiatek** [comment]
Is it going to be merged into v2 branch as well?

**Comment by sokra** [comment]
Thanks

**Comment by sokra** [comment]
> Is it going to be merged into v2 branch as well?

Nope. v2 depends on Object.defineProperty anyway for the ES6 stuff. v2 doesn't support IE8!

**Comment by SimenB** [comment]
@sokra Could you publish this?

**Comment by SimenB** [comment]
@sokra ping :smile:

**Pull request merged**
