### PR TITLE
Shared config

### PR DESCRIPTION
**Pull request by mdreizin**
Hello @sokra, @jhnns, all contributors,

I'd like to bring up [the following issue](https://github.com/webpack/webpack/issues/641).

I have created this issue, because it is too difficult to work with webpack configs when you have more than one config.

In large projects you can have different stacks and every time we need to write the same configs again and again. Currently If your projects use the same `loaders`, `resolve`, `plugins` and other common stuff you need to do `copy`-`paste` or just use `require` to load config and modify it:

```js
var baseConfig = require('./webpack.config.js');

baseConfig.plugins.push(...);

module.exports = baseConfig;
```

By this reason I have created a library called [webpack-config](https://github.com/mdreizin/webpack-config) to have ability to share common configs between projects.

It works for me, but it would be nice to have this feature out of the box. It had some limitations and I revised it and made a new version that could become the core of webpack. This implementation is much smaller than original one, more powerful and hasn't any external dependencies.

Lets me share some high-level examples how to use it.

Just you need is define `extend` property in your config:

* as `array`:

```js
module.exports = {
	extend: [
		"./test/configOptions/extend/webpack.1-0.config.js",
		"./test/configOptions/extend/webpack.2-1.config.js"
	]
};
```

* as `string`:

```js
module.exports = {
	extend: "./test/configOptions/extend/webpack.1-0.config.js"
};
```

* as `object`:

```js
module.exports = {
	extend: {
		"./test/configOptions/extend/webpack.1-0.config.js": function(config) {
			// You can modify `config` here
			return config;
		},
		// includes `config` as is
		"./test/configOptions/extend/webpack.2-1.config.js": true
	}
};
```

When all configuration config files have been processed, they will be merged into a single configuration object.

I'm waiting for your feedback.

### CODE REVIEW

**Comment by mdreizin** [comment]
When #1493 will be implemented it could be moved to external dependency to keep webpack code clean.

**Comment by mdreizin** [comment]
Currently this PR is not actual due to reimplementation of [webpack-config](https://github.com/mdreizin/webpack-config). It is more powerful and `extend` accepts macros `extend(./webpack.[env].config.js')`.

**Comment by IngwiePhoenix** [comment]
Awesome. Sadly closed, but this should've gotten into it. Hopefuly WP2 does something here.
I want to use shared configs to build two variants of my code; one `.min`-y version, and a normal, developer-friendly version. o.o

**Comment by mdreizin** [comment]
@IngwiePhoenix for now you can use https://github.com/mdreizin/webpack-config

**Comment by IngwiePhoenix** [comment]
I’ll probably be doing that. Thanks for pointing that out :)

**Comment by jhnns** [comment]
@mdreizin Thanks for creating webpack-config. Looks good to me :+1:

**Pull request closed without merging**
