### PR TITLE
add per chunk index and index2

### PR DESCRIPTION
**Pull request by sokra**
refactor index generation

**What kind of change does this PR introduce?**
feature, bugfix for MCEP

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@sokra can you provide link on issue?

**Comment by sokra** [comment]
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/115

**Comment by sokra** [comment]
see also https://github.com/webpack-contrib/mini-css-extract-plugin/pull/130

**Comment by sokra** [comment]
After this PR MCEP can use the per chunk group index to get the module order:

https://github.com/webpack-contrib/mini-css-extract-plugin/blob/eff04a83ff7cdcbc88b282b42977bea05e782ba0/src/index.js#L383

There could still be cases where order can be done correctly (i. e. when extracting modules into a common chunk). It could make sense to emit a warning in these cases (but that probably annoy users since it doesn't matter in most cases).

**Comment by sokra** [comment]
cc @bawjensen

**Comment by evilebottnawi** [comment]
@sokra i.e no additional work in MCEP?

**Comment by kamilbrk** [comment]
Is there any reason why stats object is now different due to this PR? And, what's even more confusing, only when running webpack-serve, but not with standard one time build?

I'm using [StatsWriterPlugin](https://github.com/FormidableLabs/webpack-stats-plugin) to generate a JSON file with entry points:
`new StatsWriterPlugin({ fields: ['entrypoints'] })`

This is what I get out of stats file with following versions:
- `yarn add -D webpack@4.12.2` & `npm run build:dev`
- `yarn add -D webpack@4.12.2` & `npm run start` (with webpack-serve@1.0.3)
- `yarn add -D webpack@4.13.0` & `npm run build:dev`
```json
{
  "entrypoints": {
    "bundle": {
      "chunks": [
        "vendors~bundle", "bundle"
      ],
      "assets": [
        "chunks/vendors~bundle.js", "bundle.js"
      ],
      "children": {},
      "childAssets": {}
    }
  }
}
```

And this is what I get now with this PR included, but only with webpack-serve:
- `yarn add -D webpack@4.13.0` & `npm run start` (with webpack-serve@1.0.3)
```json
{
  "entrypoints": {
    "bundle": {
      "chunks": [
        63, 64, 65, 66, 70,
        "vendors~bundle", "bundle"
      ],
      "assets": [
        "chunks/63.js", "chunks/64.js", "chunks/65.js", "chunks/66.js", "chunks/70.js",
        "chunks/vendors~bundle.js", "bundle.js"
      ],
      "children": {},
      "childAssets": {}
    }
  }
}
```

Chunks 63, 64, 65, 66 and 70 are lazy loaded on demand with dynamic `import()`s during runtime. To my understanding they should not be on that list and, until 4.13.0, they never were.

**Pull request merged**
