### PR TITLE
fix: add missing not null check for Compilation

### PR DESCRIPTION
**Pull request by clarkdo**
In `Compilation.js`, codes are using `options` all include not null check except this part, so I added this check in case of `TypeError`.

**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

Nothing

### CODE REVIEW

**Comment by ooflorent** [comment]
What is the use-case here? I don't understand how one would run into this.

**Comment by clarkdo** [comment]
If `options` won't be empty, can we remove check iat https://github.com/webpack/webpack/blob/master/lib/Compilation.js#L408-L410 ?

**Comment by sokra** [comment]
Yeah we should change it a little bit.

* Changes on the `next` branch, as it's a breaking change
* Make `options` a constructor argument of Compiler
* `options` is required
* Remove these checks for `options`

**Comment by vankop** [comment]
Thanks for your contribution. I am closing PR because it is too stale..

**Pull request closed without merging**
