### PR TITLE
fix hot/poll, hot/condition, hot/only-dev-server infinity recursion

### PR DESCRIPTION
**Pull request by axules**
Issue: https://github.com/webpack/webpack/issues/13876

**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
No

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
Nothing

### CODE REVIEW

**Review by sokra — APPROVED** [review]

**Comment by sokra** [comment]
Could you sign the CLA here: https://cla.js.foundation/webpack/webpack?pullRequest=13877

**Review by anthonyp-usafacts — APPROVED** [review]

**Comment by tehraven** [comment]
@sokra are we good on this one?

**Comment by jiyinyiyong** [comment]
Thx for fixing this, I also ran into this problem while upgrading https://github.com/webpack/webpack/discussions/13839.

I searched the code and also noticed that `if (!updatedModules)` was used at multiple places:

https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/hot/signal.js#L12
https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/hot/only-dev-server.js#L16

is that caused by upstream functions? do all these functions need an update?

**Comment by axules** [comment]
@jiyinyiyong I'm sure that empty array in result of `check` is better and we don't need to change it on higher level. If it is array it should be array always.
So, I think it should be fixed in all places when it is used. I can update this PR with required changes
@sokra

**Comment by sokra** [comment]
Thanks

**Pull request merged**
