### PR TITLE
chore: deps update

### PR DESCRIPTION
**Pull request by alexander-akait**
update deps regarding to semver

Okay, we have problems with:

- eslint-plugin-jsdoc (one of a transitive package added the exports to package.json field in patch version and eslint-plugin-jsdoc can't get jsdocs tokens inside file)
- eslint-plugin-prettier (they added engines in the patch release)
- lint-staged changed own deps and one of the deps requires node v14
- ajv + terser - now we have the `$id` in some schemas, previously terser remove them (we need to fix it in webpack/tooling)

### <samp>🤖 Generated by Copilot at 49e15a7</samp>

This pull request refactors and improves the schemas for various webpack plugins, using the `definitions` keyword to define common types and the `properties` keyword to specify object properties. This makes the schemas more concise, readable, consistent and maintainable.

### <samp>🤖 Generated by Copilot at 49e15a7</samp>

*  Refactor schemas for plugin options to use `definitions` and `properties` keywords for better readability and validation ([link](https://github.com/webpack/webpack/pull/16919/files?diff=unified&w=0#diff-8826bf3c861f8076f252a8551a5adfc06c6b0889c3d1850abc9fede8a81833b0L6-L5), [link](https://github.com/webpack/webpack/pull/16919/files?diff=unified&w=0#diff-338913b67e6c36c138cda82529240d111d7d4a3a81c2b8e01a888eac2756a8dcL6-L5), [link](https://github.com/webpack/webpack/pull/16919/files?diff=unified&w=0#diff-282dc93ff97190c91bba8f92251507ac4f7d10c5693eecc141c941e04961b8cbL6-L5))
*  Extract `SharedItem` schema to avoid duplication and reference it in `SharePlugin` options schema ([link](https://github.com/webpack/webpack/pull/16919/files?diff=unified&w=0#diff-a9f08ce102400ae856f182ee1081886b4379694cfb5731b0e2bb273c210f0870L6-L5))

### CODE REVIEW

**Comment by snitin315** [comment]
Oh I also tried it, I think we need update snapshots too.

**Comment by alexander-akait** [comment]
@snitin315 Yea, there is some other problems, let's ship this first, and then will ship your PRs with minor/major updates

**Comment by alexander-akait** [comment]
Because I need this for jest

**Comment by alexander-akait** [comment]
Copilot can look into minified code, that is great :smile:

**Comment by alexander-akait** [comment]
Okay, we have problems with:
- `eslint-plugin-jsdoc` (one of a transitive package added the `exports` to `package.json` field in patch version and `eslint-plugin-jsdoc` can't get jsdocs tokens inside file)
- `eslint-plugin-prettier` (they added `engines` in the patch release)
- `lint-staged` changed their deps and one of the deps requires new nodes
- `ajv` - they now added `$id` to refenreces in schemas (we need to fix it in `webpack/tooling`)

**Review by TheLarkInn — APPROVED** [review]
🚢 it

**Pull request merged**
