### PR TITLE
adding public path to importscripts

### LINKED ISSUE #7529: Dynamic import not working on target: 'webworker' with custom output.publicPath
# Bug report

**What is the current behavior?**
When I use a dynamic import and I've setup `target: 'webworker'` on my webpack config, and I setup a custom `output.publicPath`, that path is not being set in that require, so file is not found when executing the code.

**If the current behavior is a bug, please provide the steps to reproduce.**
* Create any proyect using webpack
* Setup `target: 'webworker'` on your webpack config's main level
* Setup your `output.publicPath` to a custom directory (different than root)
* On your `index.js` import a file on the following way `import(/* webpackChunkName: "my-module" */ 'my-module');` 
* Build/launch your app and open network inspector
* Look for a 404 error, looking for any bundle, and verify it's trying to be imported from `localhost:xxxx/chunkname-without-path.ext`

**What is the expected behavior?**
It's expected to inject the output path before the chunkname, so it's properly found.

I think that `mainTemplate.outputOptions.chunkFilename` in https://github.com/webpack/webpack/blob/510b68a828d4fa07dd889638c25f251cf1d84cc0/lib/webworker/WebWorkerMainTemplatePlugin.js#L39 comes without `path`

**Other relevant information:**
webpack version:  4.8.3
Node.js version: 8.9.1
Operating System: ElementaryOS 0.4.1 Loki (64 bits)
Additional tools:

### PR DESCRIPTION
**Pull request by prateekbh**
Fixes #7529 

**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

I will, if the approach looks fine to the reviewers.
Just dont wanna do any extra work as this is my first PR to webpack

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**
Nothing, this is what users expect

### CODE REVIEW

**Comment by prateekbh** [comment]
Re: Did you add tests for your changes?

Lol! How come i didn't break any 🤔???
Were there no tests surrounding this?

**Comment by ooflorent** [comment]
Public path may be empty. That would explain why the tests didn’t report a failure.

**Comment by prateekbh** [comment]
I request someone to review my approach if I am not doing any blunder here, then I'll add tests for the same.

**Comment by sokra** [comment]
And there are no tests for that target yet. It would be great if you add some.

Look at `test/configCases/web/prefetch-preload` on how to test publicPath things.

To get the ConfigTestCases working at all for webworkers to need to add `importScripts` to the globalContext in the tests:

https://github.com/webpack/webpack/blob/cf793c4a42982118464f892796dd04b64c3b6132/test/ConfigTestCases.test.js#L171-L184

**Comment by prateekbh** [comment]
@sokra i am having a bit difficulty in finding how to write this test... some help will be needed

I am trying to create a worker with a script but `worker` is not defined in jest

**Comment by prateekbh** [comment]
ping for help

**Comment by developit** [comment]
@prateekbh I'd suggest [jsdom-worker](https://github.com/developit/jsdom-worker) to mock Worker.

**Pull request closed without merging**
