### PR TITLE
fix webpack config in chunkhash example

### PR DESCRIPTION
**Pull request by loveky**
**What kind of change does this PR introduce?**

fix webpack config in chunkhash example

**Did you add tests for your changes?**

No, no need to add test

**If relevant, link to documentation update:**

**Summary**

**Does this PR introduce a breaking change?**

No

**Other information**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@loveky Please accept CLA. Thanks!

**Comment by loveky** [comment]
@evilebottnawi  I have already accepted it. May a sync problem?

timline 20180509175629

**Comment by montogeek** [comment]
@loveky Could you please try again https://cla.js.foundation/webpack/webpack?pullRequest=7249 ?

**Comment by montogeek** [comment]
Fixed :)

**Pull request closed without merging**
