### PR TITLE
Initialize hash conditionally

### PR DESCRIPTION
**Pull request by lvivski**
Hello,

We're working on a relatively big app:
~ 2M LOC
~ 10k assets
~ 10k hashes to compute

`RealContentHashPlugin` was taking substantial time to seal the compilation. After profiling the code, I've found that `createHash` was adding most of the time to the processing.

I wasn't able to reproduce it in synthetic tests. My current assumption is that high memory pressure and GC are involved. I can investigate it later but would like the fix to be checked in.

We use `webpack-subresource-integrity` plugin, half of the hashes come form it and are recalculated through the hook. Since `hash` is only needed when there wasn't one generated by an external plugin, it's safe to move its creation into the same conditional block, where it's used. 

This minor change improved `RealContentHashPlugin` processing time by **5x**:

_Note: timing is provided by `ProfilingPlugin`_

Setup:
_OS:_ Ubuntu 18.04.1
_CPU:_ Intel Xeon Platinum 8272CL @ 2.60Ghz
_MEM:_ 64GB
_Node.js:_ 14.20.0
_Hashing Algorithm:_ `xxhash64`

Before:
Run 1: `RealContentHashPlugin(sealing) - 34% (559s)`
Run 2: `RealContentHashPlugin(sealing) - 31% (741s)`
Run 3: `RealContentHashPlugin(sealing) - 33% (587s)`

After:
Run 1: `RealContentHashPlugin(sealing) - 7% (93s)`
Run 2: `RealContentHashPlugin(sealing) - 7% (95s)`

**What kind of change does this PR introduce?**

Refactoring. No logic changes.

**Did you add tests for your changes?**

No additional tests required

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

N/A

### CODE REVIEW

**Comment by alexander-akait** [comment]
@lvivski Thank you, can you accept CLA?

**Comment by lvivski** [comment]
@alexander-akait sure, just accepted it, sorry for the delay.

**Review by alexander-akait — APPROVED** [review]

**Review by rishabh3112 — APPROVED** [review]

**Review by evenstensberg — APPROVED** [review]

**Comment by lvivski** [comment]
@alexander-akait is there anything I can do to help with reviewing/merging this PR?

**Comment by TheLarkInn** [comment]
@alexander-akait I'm going to merge this after reviewing. Can you or @sokra perform a publish please.

**Review by TheLarkInn — APPROVED** [review]

**Comment by TheLarkInn** [comment]
Thank you @lvivski for the contribution 🙏🙇‍♂️🙇‍♂️

**Comment by vsumner** [comment]
@TheLarkInn @alexander-akait @sokra - Any chance this could make a release soon?

**Comment by TheLarkInn** [comment]
@vsumner apologize for the delay. We are batching these contributions and are hoping to publish a new minor version soon. (Targeting this week and review from core team).

**Pull request merged**
