### PR TITLE
Added `assert/strict` built-in

### PR DESCRIPTION
**Pull request by piranna**
**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

### CODE REVIEW

**Comment by alexander-akait** [comment]
@TheLarkInn I think we can merge it, just small fix for Node env

**Review by alexander-akait — APPROVED** [review]

**Comment by piranna** [comment]
> @TheLarkInn I think we can merge it, just small fix for Node env

Thank you @alexander-akait, I don't know if there's any other built-in that we should add, I have just added this that's my personal case. I've seen that we are already currently checking for `node:` prefix, that's the recommended way, probably we should recommend it ourselves in the docs too.

**Review by snitin315 — APPROVED** [review]

**Comment by TheLarkInn** [comment]
Thank you for the PR 💟

**Comment by piranna** [comment]
You are welcome :-)

**Pull request merged**
