### PR TITLE
feat(app): Add badges to REAMDE.md

### PR DESCRIPTION
**Pull request by thaiat**
Add badges to the README

it will look like that:

readme

### CODE REVIEW

**Comment by SimenB** [comment]
There are lots of badges in the readme, just not at the top

**Comment by thaiat** [comment]
@SimenB  i just saw it. 
Does it not make sense to put the badges at the beginning ?

**Comment by SimenB** [comment]
I agree, it was more of a FYI

**Comment by thaiat** [comment]
@SimenB @sokra 
i have cleaned the redondant badges, and use token url at the end of the file for consistency

the README now looks like that:

markdown_preview

**Comment by sokra** [comment]
That's too much...

Could you separate it into categories?

user-related: npm
collaboration-related: gitter, CI, coverage
donation-related: tips, donate
dependencies: dependencies

The user-related can be at the top. The remaining into the sections.

**Comment by thaiat** [comment]
@sokra, i think it is valuable to see all the badges at the top of the README, otherwise most people don't see them (who reads the doc ???)
I tried to separate the badges per categories
how about that ?

markdown_preview

**Comment by sokra** [comment]
Thanks

**Pull request merged**
