### PR TITLE
feat: add validation to remotes

### PR DESCRIPTION
**Pull request by tanhauhau**
#13287

**What kind of change does this PR introduce?**

added pattern validation to the remotes object schema

**Did you add tests for your changes?**

not sure how to add test

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

### CODE REVIEW

**Review by sokra — CHANGES_REQUESTED** [review]
This pattern is not in general true, it only applies to the `script` external/remote type.

best add some kind of validation to `lib/util/extractUrlAndGlobal.js`

**Comment by tanhauhau** [comment]
got it! not sure my error message is descriptive enough

**Review by sokra — APPROVED** [review]

**Comment by sokra** [comment]
Thanks

**Comment by sokra** [comment]
> not sure my error message is descriptive enough

probably not. Feel free to improve it in a follow-up PR.

**Pull request merged**
