### PR TITLE
ci: node.js v20

### PR DESCRIPTION
**Pull request by alexander-akait**
Test on node v20, only for github actions, because we already have a lot of CI...

### <samp>🤖 Generated by Copilot at 30759ec</samp>

This change adds `20.x` to the node-version matrix in `.github/workflows/test.yml` to run the test suite with the latest Node.js version on various platforms. This helps ensure webpack's compatibility with the newest Node.js features and APIs.

### <samp>🤖 Generated by Copilot at 30759ec</samp>

* Add Node.js 20.x to the node-version matrix to test webpack compatibility on different OSes ([link](https://github.com/webpack/webpack/pull/17019/files?diff=unified&w=0#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88L93-R93))

### CODE REVIEW

**Comment by alexander-akait** [comment]
@snitin315 We need to add node.js v20 to webpack-cli and webpack-dev-server too, it is very important places

**Comment by snitin315** [comment]
@alexander-akait Yes, I'll add it.

**Review by TheLarkInn — APPROVED** [review]

**Review by snitin315 — APPROVED** [review]

**Comment by TheLarkInn** [comment]
Feel free to merge i blocked by flake or coverage.

**Comment by alexander-akait** [comment]
@TheLarkInn let's do it after release to avoid block some PRs with new CI setup

**Pull request merged**
