### PR TITLE
refactor: use global constant for __webpack_require__ instead of string literal

### PR DESCRIPTION
**Pull request by burhanuday**
part of https://github.com/webpack/webpack/issues/16897

fixes #17134

### <samp>🤖 Generated by Copilot at 2b4d15a</samp>

This pull request refactors the code generation for the webpack runtime and various plugins to use constants from the `RuntimeGlobals` module instead of hard-coded names for the webpack require function and other runtime variables. This improves the consistency, readability, maintainability, and configurability of the code. It affects many files in the `lib` directory, such as `lib/CompatibilityPlugin.js`, `lib/Compilation.js`, `lib/Template.js`, and others.

### <samp>🤖 Generated by Copilot at 2b4d15a</samp>

*  Refactor the name of the webpack require function to use a constant from RuntimeGlobals module ([link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-4503ec469779b28b7570b16bff111949383eeb0226b7ce34b43f2cf33e538ffaR8), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-4503ec469779b28b7570b16bff111949383eeb0226b7ce34b43f2cf33e538ffaL82-R83), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-4503ec469779b28b7570b16bff111949383eeb0226b7ce34b43f2cf33e538ffaL101-R102), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-9206962f55a69b69a39e73a803e2be04b10d454f270e35b482f3f70a74f472a6L5027-R5027), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-9206962f55a69b69a39e73a803e2be04b10d454f270e35b482f3f70a74f472a6L5033-R5033), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-7381096418ac5ce93b8514a7bf323d891937e3fdabda8628d8bbc0ce46f6db10L643-R643), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-7381096418ac5ce93b8514a7bf323d891937e3fdabda8628d8bbc0ce46f6db10L802-R802), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-7381096418ac5ce93b8514a7bf323d891937e3fdabda8628d8bbc0ce46f6db10L853-R853), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-c05f2b491edc9901962d3f4fa25fdc53373333263dee06dbce8f660a7bb4f5e1L92-R92), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-9e32e8f1399229467a54c5b9f1348d89c6d3d9c18bee23e2d4ab5e059066f921L309-R310), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-07626cfb7da83ee25692aef62aec9dc6a32d6f0511b00e6b342121c5a87b5c75L432-R432), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-07626cfb7da83ee25692aef62aec9dc6a32d6f0511b00e6b342121c5a87b5c75L628-R628), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-07626cfb7da83ee25692aef62aec9dc6a32d6f0511b00e6b342121c5a87b5c75L654-R654), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-07626cfb7da83ee25692aef62aec9dc6a32d6f0511b00e6b342121c5a87b5c75L669-R669), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-07626cfb7da83ee25692aef62aec9dc6a32d6f0511b00e6b342121c5a87b5c75L776-R776), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-f2dd4b12664998536d314e3c184494a1c3ed3f281a7b93c3912c1798671f9716L408-R409), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-5f94a213a0814e907773d1901a40e0025f72913c41f666b447fbab512224a060L139-R139), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-3292602d5deb4190c3d9c49c39a617fb9ea3955324fd9ba277afc2cbe1c7192cL120-R120), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-d95823e2e61cd46a7983f0b01e1bd2f96e1b449d8eaea4cfe1ed3baa50de367dL22-R22), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-d95823e2e61cd46a7983f0b01e1bd2f96e1b449d8eaea4cfe1ed3baa50de367dL40-R40), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-d95823e2e61cd46a7983f0b01e1bd2f96e1b449d8eaea4cfe1ed3baa50de367dL72-R72), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-d95823e2e61cd46a7983f0b01e1bd2f96e1b449d8eaea4cfe1ed3baa50de367dL83-R82), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-6eddb15b462eb972dfec997299b4e8ad1dbbe9a40d834fe39cc5abb39f72e2b8L76-R76), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-6eddb15b462eb972dfec997299b4e8ad1dbbe9a40d834fe39cc5abb39f72e2b8L112-R112), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-62ba3e4e288da6c16395430b152f1efc9115c2b2efa8182986f0a49f7a6ab7cdL76-R76), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-62ba3e4e288da6c16395430b152f1efc9115c2b2efa8182986f0a49f7a6ab7cdL111-R111), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-460b5482ccc19c9130838c0a2afd79445cf5a0ad8a903e152acffb2b0a3595f6L114-R114), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-104576f6400c7b8f7f4f6e4f3b6309454b34698f25c64700d3b5905eba0dbc4aL96-R96), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-104576f6400c7b8f7f4f6e4f3b6309454b34698f25c64700d3b5905eba0dbc4aL103-R103), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-8b692880179fa5bf3eec8ff9a1055ed22b5dd6fc264cb9f162069531e30a2f20L58-R58), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-45e55e464e6caf036f2eb9066f04c5091f58df10b9247e4a3e623b0def38b82cL25-R26), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-c5d4f993897e06b2577f256473c37db962d87ba30de1d3d2c631d6eb68d7c95cL126-R126), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-c5d4f993897e06b2577f256473c37db962d87ba30de1d3d2c631d6eb68d7c95cL134-R134), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-cf94a953c7dcf19d00514b7cf5e7566b153ab8aa21c2002318fb5a38ff24b861L159-R159), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-30ab5813509bfcbb82b3f51a1d6901b198ca3e82c0e19d23f5c25b4117f00decL87-R88), [link](https://github.com/webpack/webpack/pull/17228/files?diff=unified&w=0#diff-6ae954ef2355023398c28142a911267d41db863bd6483c4534ad2ed6bebbc9a0L123-R123))

### CODE REVIEW

**Comment by alexander-akait** [comment]
Please run `yarn fix`

**Comment by burhanuday** [comment]
Done

**Review by alexander-akait — COMMENTED** [review]
Also I think will be great to check our code on all possible strings from https://github.com/webpack/webpack/blob/main/lib/RuntimeGlobals.js, because I think we have more such cases, but let's do it on other PRs, for example - `__webpack_exports__`, but I think we have more

**Comment by burhanuday** [comment]
I'll open a separate PR to replace all the pending vars

**Review by alexander-akait — APPROVED** [review]

**Review by TheLarkInn — APPROVED** [review]

**Pull request merged**
