### PR TITLE
add lint step to avoid non-npm dependencies in graph

### PR DESCRIPTION
**Pull request by sokra**
**What kind of change does this PR introduce?**
linting

**Did you add tests for your changes?**
N/A

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

**Comment by sokra** [comment]
@xtuc

**Comment by xtuc** [comment]
Nice! I was about to do it, I was wondering if we could publish it as an npm package, I'm sure other projects would like it?

**Comment by danez** [comment]
It would be nice if this would be added to yarn directly as something like
```
yarn --registry-whitelist "registry.yarnpkg.com","registry.npmjs.org"
```

**Comment by xtuc** [comment]
I agree with @danez, but as I said on Babel's Slack, in our case It should more be:
```
yarn --protocol-whitelist "https,http"
```

**Pull request merged**
