### PR TITLE
refactor(Chunk): upgrade to ES6

### PR DESCRIPTION
**Pull request by willmendesneto**
**What kind of change does this PR introduce?**

ES5 => ES6 refactor

**Did you add tests for your changes?**

refactor, all existing tests pass

**If relevant, link to documentation update:**

N/A

**Summary**

Helping in part of the ES6 refactor

**Does this PR introduce a breaking change?**

Nope

### CODE REVIEW

**Comment by TheLarkInn** [comment]
This is awesome. Would you be willing to add a test or so for this? @alistairjcbrown can help out if you need it.

**Comment by willmendesneto** [comment]
Good catch @TheLarkInn , I didn't realise that we don't have any test for this file exactly. I will take a look on this and update this PR.

**Comment by willmendesneto** [comment]
@TheLarkInn, I added some tests for `Chunk` class, but I don't have all context about the scenarios and standards that we are using in webpack repository. 

I found different styles inside the test files and there's nothing talking about it on `test/README.md`. I don't know if you guys are aware of it or what you are doing to improve this, so I don't know if makes sense create an issue to handle this or if we have some work in progress.

**Comment by TheLarkInn** [comment]
That would be awesome. This looks great thank you so much.

@willmendesneto would you mind creating an issue and tag me in it. I think updating that test/README doc would be an awesome idea.

**Pull request merged**
