### PR TITLE
fix: umd for Node.js

### PR DESCRIPTION
**Pull request by alexander-akait**
**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

I will add if we will approve this

**Does this PR introduce a breaking change?**

No, because we use `()`, so `globalThis`, `typeof self !== undefined ? self : exports` and other cases will work

**What needs to be documented once your changes are merged?**

No

### CODE REVIEW

**Comment by vankop** [comment]
so we can provide `false` as root, if global === undefined?

**Comment by alexander-akait** [comment]
It was idea from rollup, but maybe I am wrong here

**Comment by vankop** [comment]
now `globalObject` can be an expression and we handle this in webpack

**Comment by alexander-akait** [comment]
Yep, let's close, now workaround is using `globalThis` in options, in future I think we will need it only for very legacy things, so it probably doesn't make sense to waste time on this

**Pull request closed without merging**
