### PR TITLE
chore(docs): fancy npm/yarn install styling

### PR DESCRIPTION
**Pull request by pi0**
**What kind of change does this PR introduce?**

docs

**Did you add tests for your changes?**

Screenshots 📷 

**Summary**

This PR makes npm/yarn install commands in README feeling more **commandy**. 

**Before**

image

**After**

image

Anyway this just something optional, no worries if prefer to reject it :))

### CODE REVIEW

**Comment by sokra** [comment]
Why is there a `_` after the `>`?

**Comment by bfred-it** [comment]
Not a very common style and it could confuse newbies. `$` is the only easily-recognizable leading character, and even that one can be confusing.

**Comment by pi0** [comment]
@sokra That `>_` is like windows cmd indicators. We can try some like this too:

```bash
> npm install webpack
```

But `$` won't render as a highlighted character.

```bash
$ npm install webpack
```

Again, this is just about preference and safe to reject. Better visual style (To quickly find out this is a command snippet) *vs* better copy-paste experience :)

**Comment by sokra** [comment]
I guess we just leave it as it is.

**Comment by sokra** [comment]
Thanks for the PR anyway.

**Pull request closed without merging**
