### PR TITLE
webpack bundled for non-node environment (deno.land)

### PR DESCRIPTION
**Pull request by janesser**
webpack is tighly bound to node.js, despite the fact that there are different environments, i.e. deno.land or "the browser".

There was a preliminary exchange of basic thoughts with @sokra.
https://twitter.com/wSokra/status/1249387043588837378

**What kind of change does this PR introduce?**
Attempt to bundle webpack as an esm/es6-module for use wherever node.js isn't available, like deno.land. For now seems like rollupjs does the job.

**Did you add tests for your changes?**
TODO
see "yarn build && yarn deno:test", which returns some feedback.

**Does this PR introduce a breaking change?**
No, webpack code remains untouched.

TODO see why linters act up.

**What needs to be documented once your changes are merged?**

bundle should be made available at a certain URL that would be nice to have on the README.md.

### CODE REVIEW

**Comment by montogeek** [comment]
🤔

**Comment by janesser** [comment]
updated initial comment, exposing motivation and approach.

**Comment by janesser** [comment]
> Ideally you should use webpack for building webpack

@montogeek sounds like an evident first try. i wonder if somebody has already tried.
didn't find anything in that direction.

Nor couldn't find any trace of webpack producing anything deno.land capable.

Opposed to that i managed to make some js-libs be esm-bundled with rollup.

**Comment by janesser** [comment]
integrated some of deno-node-adapters, but still forcing webpack into es6-modules is not straight forward.

`(!) Circular dependencies
lib\AbstractMethodError.js -> lib\WebpackError.js -> lib\util\makeSerializable.js -> lib\util\serialization.js -> lib\serialization\FileMiddleware.js -> li
b\util\createHash.js -> lib\util\Hash.js -> lib\AbstractMethodError.js
lib\AbstractMethodError.js -> lib\WebpackError.js -> lib\util\makeSerializable.js -> lib\util\serialization.js -> lib\serialization\FileMiddleware.js -> li
b\util\createHash.js -> lib\util\Hash.js ->  C:\Users\jan\Documents\projs\webpack\lib\AbstractMethodError.js?commonjs-proxy -> lib\AbstractMethodError.js  
lib\util\makeSerializable.js -> lib\util\serialization.js -> lib\util\internalSerializables.js -> lib\AsyncDependenciesBlock.js -> lib\DependenciesBlock.js
 -> lib\util\makeSerializable.js
...and 129 more`

In current status quo makeSerializable isn't coming up in the resulting bundle. No clue why.

Should be looking for visualization next.

**Comment by janesser** [comment]
https://github.com/rollup/rollup/wiki/Cycles
Makes clear that cycles are very often deduced from modelling and thus natural companions.

Still when deno tries to read the bundle dist/webpack.esm.js some forward declarations won't resolve.

**Comment by janesser** [comment]
I would be open for guidance about this one.

Questions to cover:
- can webpack do what does rollup does in this draft?
- is webpack meant to do anything none nodejs related?
that has widerange impact on all webpack adopters.
- is the present node and browser support in an extensible plugin way?
how would this look like?

(i would propose to delay considerations about all formalities like codecov and eslint)

**Comment by janesser** [comment]
Story is open for anybody interested.

**Comment by evilebottnawi** [comment]
@janesser sorry for delay, a lot of work, you are still interests? I can help

**Pull request closed without merging**
