### PR TITLE
feat(test) use min reporter to show only failing tests (reduce noise)

### PR DESCRIPTION
**Pull request by jdalton**
- [X] Feature

While looking at the travis-ci results I noticed there was a ton of noise (lots of data on passing tests). This PR uses the min reporter to only show failing tests.

### CODE REVIEW

**Comment by jdalton** [comment]
Note: travis-ci is having hangs on their osx runs which is causing webpack runs to hang. Might be worth temp disabling them until their issue resolves. See https://www.traviscistatus.com/incidents/b4xk2bybjc9d.

**Comment by TheLarkInn** [comment]
@jdalton I'd be fine disabling them for the time being. Would you mind updating the travis.yml file?

**Comment by jdalton** [comment]
Updated :D

**Comment by TheLarkInn** [comment]
Oh Travis... 

@jdalton would you mind checking this out and making sure it's not a flake for Travis.

**Comment by jdalton** [comment]
Patched. It seems while `_mocha` is required for collecting coverage it doesn't support the `--harmony` flag *(`mocha` does support the harmony flag but will punt coverage)*.

**Comment by TheLarkInn** [comment]
TIL: 40 things this PR 🤓. Going to make sure AppVeyor isn't a memory flake again and if so I'll merge nice job.

**Comment by TheLarkInn** [comment]
Looks good thanks!

**Pull request merged**
