### PR TITLE
Refactoring Template.js rewrote forEach and 4 unnecessary iteration

### PR DESCRIPTION
**Pull request by Tom910**
What kind of change does this PR introduce?
Refactoring

Did you add tests for your changes?
N/A

Summary
Rewrote frequently used forEach and 4 unnecessary iteration for modules

Does this PR introduce a breaking change?
No

### CODE REVIEW

**Comment by wtgtybhertgeghgtwtg** [comment]
Why is this changing four loops in one PR?  There's no way to determine which have significant impact this way.

**Comment by Tom910** [comment]
@wtgtybhertgeghgtwtg I think often used unnecessary iteration must be removed

**Comment by Tom910** [comment]
@sokra - I am here not only rewrote forEach. And I cleaned unnecessary iterations. In proof, improved performance, I attach the test -
```
Refactoring code x 31,311 ops/sec ±1.33% (84 runs sampled)
Old code x 1,121 ops/sec ±0.78% (86 runs sampled)
```
https://gist.github.com/Tom910/037e188cdc07ad122d15bce4596761df
At 28 times faster than the old code

**Comment by sokra** [comment]
So the total saving by refactoring this piece of code is 1ms for 5000 modules. If a compilation with 5000 modules takes 30s in sum it improves the performance by 0.003%... This is not worth it.

**Pull request closed without merging**
