### PR TITLE
Hashed chunk ids

### LINKED ISSUE #8355: Hashed chunk ids
## Feature request

**What is the expected behavior?**

Hashed chunk ids

**What is motivation or use case for adding/changing the behavior?**

After [this PR](https://github.com/webpack/webpack/issues/8268) we have got better long-term caching "out of the box", but we have many chunks and they have numeric ids and these ids changes very often and it still affects long-term caching.

Named chunk ids is too large

**How should this be implemented in your opinion?**

Clone `HashedModuleIdsPlugin` with the same login and adopt it for chunks. It looks like an easy solution...

**Are you willing to work on this yourself?**
yes

### PR DESCRIPTION
**Pull request by smelukov**
**What kind of change does this PR introduce?**

Added `chunkIds: "hashed"` and enabled it for prod-mode for better long-term-caching

**Did you add tests for your changes?**

yes

**Does this PR introduce a breaking change?**

no

**What needs to be documented once your changes are merged?**

about `chunkIds: "hashed"`

closes #8355

### CODE REVIEW

**Comment by smelukov** [comment]
> ReferenceError: installedChunks is not defined

Seems something wrong with CI on the next-branch
I didn't touch the bundle bootstrap code

**Comment by smelukov** [comment]
I'll fix CI soon

**Comment by smelukov** [comment]
Any comments here?

**Comment by sokra** [comment]
Looks good, but I want to add deterministic chunk ids too in this PR. Just didn't find the time yet.

**Comment by smelukov** [comment]
@sokra I’ll try to do it by my self

**Comment by sokra** [comment]
fixed by other PR

**Pull request closed without merging**
