### PR TITLE
Add support for md4 in Node >=18.

### PR DESCRIPTION
**Pull request by iclanton**
### <samp>🤖 Generated by Copilot at 6f6ae98</samp>

This pull request adds WebAssembly-based md4 hashing for Node.js 18 or higher, and implements a BatchedHash class that improves the performance of hashing large data. It also refactors the createHash function and removes unused code from the createHash.js module. The changes involve adding new modules `lib/util/hash/BatchedHash.js`, `lib/util/hash/md4.js`, and `lib/util/hash/wasm-hash.js`, and modifying `lib/util/createHash.js`.

### <samp>🤖 Generated by Copilot at 6f6ae98</samp>

*  Remove Hash class and HashConstructor type exports from `createHash.js` module ([link](https://github.com/webpack/webpack/pull/17628/files?diff=unified&w=0#diff-367809774077aa963dfccd23717f9ab3eebe493f40f242ae5168ef5c4d8613e3L32-L34))
*  Add variables to lazily require crypto, md4, and BatchedHash modules in `createHash.js` module ([link](https://github.com/webpack/webpack/pull/17628/files?diff=unified&w=0#diff-367809774077aa963dfccd23717f9ab3eebe493f40f242ae5168ef5c4d8613e3R118-R127))
*  Modify createHash function to handle md4 and native-md4 algorithms differently depending on Node.js version and use BatchedHash class for md4 WebAssembly hash in `createHash.js` module ([link](https://github.com/webpack/webpack/pull/17628/files?diff=unified&w=0#diff-367809774077aa963dfccd23717f9ab3eebe493f40f242ae5168ef5c4d8613e3L130-R174))
*  Add BatchedHash class that extends Hash class and batches data chunks for underlying hash implementation in `BatchedHash.js` module ([link](https://github.com/webpack/webpack/pull/17628/files?diff=unified&w=0#diff-aad38dbb7cc27cdeb40c0f35dae63c5dc9b10452884affaac73440d304c81da4R1-R71))
*  Add md4 function that creates WasmHash instance using md4 WebAssembly module and md4 instances pool in `md4.js` module ([link](https://github.com/webpack/webpack/pull/17628/files?diff=unified&w=0#diff-0427381e1c19460471f1da161cf0e10bd8c34988b9d9beb300aad6f4d391561eR1-R25))
*  Add WasmHash class that implements hash interface using WebAssembly module, memory buffer, chunk size, and digest size in `wasm-hash.js` module ([link](https://github.com/webpack/webpack/pull/17628/files?diff=unified&w=0#diff-7003f82fbd668f2a1a74eacc2b63955157c5c6a63eec9e651359e6d980545689R1-R174))
*  Add create function that creates WasmHash instance using WebAssembly module, instances pool, chunk size, and digest size in `wasm-hash.js` module ([link](https://github.com/webpack/webpack/pull/17628/files?diff=unified&w=0#diff-7003f82fbd668f2a1a74eacc2b63955157c5c6a63eec9e651359e6d980545689R1-R174))
*  Export MAX_SHORT_STRING constant from `wasm-hash.js` module and use it in BatchedHash class ([link](https://github.com/webpack/webpack/pull/17628/files?diff=unified&w=0#diff-aad38dbb7cc27cdeb40c0f35dae63c5dc9b10452884affaac73440d304c81da4R1-R71), [link](https://github.com/webpack/webpack/pull/17628/files?diff=unified&w=0#diff-7003f82fbd668f2a1a74eacc2b63955157c5c6a63eec9e651359e6d980545689R1-R174))

### CODE REVIEW

**Review by dmichon-msft — APPROVED** [review]

**Review by snitin315 — COMMENTED** [review]
Why not upgrade the webpack version to v5?

**Comment by iclanton** [comment]
@snitin315 - There are a number of breaking changes between Webpack 4 and 5, making upgrading large and complex projects time-consuming.

Webpack 4 currently has many more weekly downloads on npmjs.org than Webpack 5 does, but Webpack 4 only works with Node 16 and earlier because of the issue being addressed in this PR. Node 16 is EOL on 2023-09-11 (next Monday).

**Comment by snitin315** [comment]
@iclanton Shouldn't webpack upgrade be considered as the migration effort for your app to Node v18? You can anyway use `NODE_OPTIONS=--openssl-legacy-provider` when using webpack v4 with Node.js v17+, and put a TODO to upgrade webpack v5 later. CMIMW, here we are using this function just to create a hash in filenames, so there's no such security threat.

**Comment by TheLarkInn** [comment]
@alexander-akait @snitin315 and myself discussed this further. Because Node 16 EOL is in 2 weeks, we do not want our ~12 million webpack 4 consumers to be stuck with what will be flagged as a security vulnerability not updating Node. It would be ideal not to block them here.

**Comment by chadlwilson** [comment]
Thanks so much for this @iclanton . I see you've been doing some work around the ecosystem to help with this. Is `terser-webpack-plugin` on your radar? I opened https://github.com/webpack-contrib/terser-webpack-plugin/issues/578 to see if the maintainers are interested in addressing a similar issue there.

**Comment by Shubhanshu88** [comment]
@chadlwilson I guess this PR by iclanton : https://github.com/webpack/webpack/pull/17659 is for the terser-webpack-plugin bump

**Comment by chadlwilson** [comment]
I totally missed that, thanks @Shubhanshu88 - I feel stupid now!

**Pull request merged**
