### PR TITLE
the duplicate logic in buildModule callback and afterBuild

### PR DESCRIPTION
**Pull request by lingxiaoguang**
When I read the buildModule logic, I found the logic `record the building time in currentProfile` is duplicate in buildModule's callback and the afterBuild method. So I create this pull request.Just a little
 change.

**What kind of change does this PR introduce?**
refactoring

**Did you add tests for your changes?**
no

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
no

### CODE REVIEW

**Comment by lingxiaoguang** [comment]
Ok, but when I modify it agin, I found another duplicate logic in `addModuleDependencies` method. The same problem, duplicate building time record. When you develop it, did you copy the code?😂

And, should I create a new pull request?

**Comment by lingxiaoguang** [comment]
How should I fix this problem? Only this problem should to be fix.

```
    expect(received).toBe(expected) // Object.is equality

    Expected: "4.36.1"
    Received: "4.35.0"

       98 | it("should not fail on optional externals", function() {
       99 |     const external = __webpack_require__(/*! external */ 1);
    > 100 |     expect(external).toBe("4.36.1");
          |                      ^
      101 | });
      102 | 
      103 |
```

**Comment by sokra** [comment]
Please sign the CLA so we can merge your PR

**Comment by lingxiaoguang** [comment]
done～😄

**Comment by sokra** [comment]
Thanks

**Pull request merged**
