### PR TITLE
Fix default

### PR DESCRIPTION
**Pull request by alexander-akait**
**What kind of change does this PR introduce?**

bugfix/feature 

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

Yes, but it is under `experiments`

**What needs to be documented once your changes are merged?**

Yes

### CODE REVIEW

**Comment by alexander-akait** [comment]
/cc @hardfist 

I want to make a change, the reason is performance. If you want to use modules you must use the file name or set  `css/module`, in other cases users usually have a regular/pure CSS, so wasting time at the parsing stage (extra checks and extra parsing) simply does not make sense, this is how our css-loader works

**Review by snitin315 — APPROVED** [review]
LGTM

**Comment by hardfist** [comment]
LGTM, explicit is better than implicit!

But I want to raise a question, even experiments is meant to introduce breaking change in non-major version,
will it be better only release experiments breaking change in minor version other than patch version( that's what we are doing in Rspack, cause experiments is still widely used and it's hard for users to track experiments breaking in patch version)

**Comment by alexander-akait** [comment]
@hardfist Yeah, I agree, let's use `minor`

**Pull request merged**
