### PR TITLE
System.import('Home') -> chunkFilename: '[name].chunk.js' -> Home.chunk.js

### PR DESCRIPTION
**Pull request by shumov**
**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Config option**

```
output: {
  chunkFilename: `[name].chunk.js`,
},
```

**What is the current behavior?**
sistemimport-chunkfilename-before

**What is the new behavior?**
sistemimport-chunkfilename-after

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Kovensky** [comment]
What happens when chunks are combined by, e.g. LimitChunkCountPlugin or MinChunkSizePlugin?

**Comment by stevewillard** [comment]
Any chance this could get merged? It would be really helpful.

**Comment by addyosmani** [comment]
This does look like it would be useful (unclear if it requires additional tests)

**Comment by stevewillard** [comment]
@sokra see any reason why this can't be merged?

**Comment by mischkl** [comment]
We have a definite use case for this, namely that we would like to dynamically load a configuration JS file from the server (it's served with cache-breaking headers). We need to be able to call `System.import('config.js')` and have it actually get the file with that exact name on the server, while in development mode it should use the local copy of the file.

Admittedly, this plugin would only work for files that are served from the same path as the main bundle. Even better would be to allow customizing the output path, so that for instance it could be the same as the input. But at least this pull request provides some solution as opposed to none! :)

**Comment by sokra** [comment]
solved by #4553

**Pull request closed without merging**
