### PR TITLE
Fix handling of non-zero exit codes in azure

### PR DESCRIPTION
**Pull request by sokra**
**What kind of change does this PR introduce?**
bugfix CI

**Did you add tests for your changes?**
N/A

**Does this PR introduce a breaking change?**
N/A

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

**Comment by sokra** [comment]
@DavidStaheli I find it a but unexpected that this is needed. Could this be enabled by default?

**Comment by DavidStaheli** [comment]
@sokra, I see what you mean.  Another way to accomplish this is with the **failOnStderr** property:

```yaml
- script: |
    export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
    node -v
    yarn -v
  failOnStderr: true
  displayName: "Print versions"
```

But the default of **failOnStderr** is `false`, and that's why setting it to `true` or using `set -e` is necessary.  A default of `true` makes more sense to me, but I'm sure there was thought put into why the default is `false`.  @chrisrpatterson, do you recall?

**Comment by chrisrpatterson** [comment]
There are a lot of tools that write stuff that is not an error to stderr which is simply the other stream.  For example git writes progress there.  By default bash does not have set -e so it does not fail the script on standard error either.

**Comment by sokra** [comment]
I understand the position about stderr. I was originally talking about exit codes. When `script` contains multiple commands, only the last exit code is handled by azure and intermediate exit codes are ignored.

I would expect the script to fail if any command has a non-zero exist code.

**Comment by chrisrpatterson** [comment]
@sokra again that is the default behavior for bash.  We can't handle error codes that are not returned to us and our default is to fail on a non-zero exit code.

**Pull request merged**
