### PR TITLE
Use secure links.

### PR DESCRIPTION
**Pull request by bhamodi**
Updated to use secure links.
The only insecure link left is the one on the GitHub repository link field. An admin has to change that. The link field is right beside the repository description.

### CODE REVIEW

**Comment by sokra** [comment]
But the docs doesn't work with https...

**Comment by bhamodi** [comment]
@sokra - The https links work for me? Are you not able to access: https://webpack.github.io/

**Comment by bhamodi** [comment]
One thing that needs to be updated though is your font links from: `http://fonts.googleapis.com/css?...` to also use secure links. I can't seem to find those links in this code base though.

**Comment by bhamodi** [comment]
@sokra - are you interested in making this change? I think the only thing left that needs to change is our assets/font urls. They need to be switched to the secure version too.

**Comment by sokra** [comment]
yes would like to change this. But I need to change the XHR in the docs to a protocol-relative url too.

**Comment by bhamodi** [comment]
@sokra - sound good! Anything else I should change from my end?

Also, where can I find the code for the docs website? Like you said, we will need to make the resources protocol-relative.

**Comment by sokra** [comment]
> sound good! Anything else I should change from my end?

no thanks, it's fine from your side... I just need to find time to change the URL in the docs.

**Comment by sokra** [comment]
Or if you want to do a PR there too: https://github.com/webpack/docs/blob/784c0456b42f53d02de8eb5612feadeffb8612a8/app/downloadWiki.js#L3

Best change it to a protocol-relative URL.

**Comment by bhamodi** [comment]
@sokra - I went ahead and creating a PR that changes it to use a protocol-relative URL here: https://github.com/webpack/docs/pull/40

**Comment by sokra** [comment]
Thanks

**Pull request merged**
