### PR TITLE
Use memoize for expensive functions

### PR DESCRIPTION
**Pull request by timse**
**What kind of change does this PR introduce?**

refactoring

**Did you add tests for your changes?**

Yes

**If relevant, link to documentation update:**

N/A

**Summary**

related to #3073 although maybe fixed by #3086 this fixes it more generally
also it unclutters modules from an extra attribute that is very specific for a single use case.

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by wtgtybhertgeghgtwtg** [comment]
What about just using `lodash` instead of `lodash.memoize`?  I wasn't quite sure about the resolution of #3690, but it is already in the dependency tree.

**Comment by timse** [comment]
If i understand correctly using lodash as a blob is an anti pattern?

**Comment by wtgtybhertgeghgtwtg** [comment]
What makes it an anti-pattern?  `lodash` is already in the dependency tree, it's already there.  `lodash.memoize` isn't; using it instead of `lodash` would increase dependencies, ironically enough.

**Comment by timse** [comment]
closing in favor of #4646

**Pull request closed without merging**
