### PR TITLE
(WIP) Enable TypeScript strictNullChecks

### PR DESCRIPTION
**Pull request by mohsen1**
## Summary
`strictNullChecks` enforces checking for references not to be `undefined` or `null` before accessing them. It is going to catch a lot of issues as the typical JavaScript code don't guard against all nulls. This might require changes in code. I'm going to make an independent PR per error reported by TypeScript.

**Does this PR introduce a breaking change?**
We'll see!

**Other information**
We need help fixing each of those reported errors. Please feel free to open PRs fixing those issues and let me know about it.

## Related Changes 
* [x] https://github.com/webpack/webpack/pull/7033
* [x] https://github.com/webpack/webpack/pull/7031
* [ ] https://github.com/webpack/webpack/pull/7046
* [x] #7051 
* [x] #7047
* [ ] #7050

### CODE REVIEW

**Comment by TheLarkInn** [comment]
@weswigham @sandersn @danielrosenwasser after exploring this feature a bit, I'm wondering if there is a way currently to do non-null assertions via jsdocs. Currently we have a lot of places we ned rotell the compiler to trust us.

**Comment by sandersn** [comment]
There is a way right now, although it is inconvenient, using closure’s type cast syntax: `/** @type {T} */(e)` for any `e` of type `T | undefined`.

Note that the parentheses go around the expression, not the doc comment. You also need to know—and be able to write—`T`. With those two problems, this makes for an error-prone solution. 

We have an open issue to add `@nonnull` or something similar, but this only addresses the second problem. You still have to use the weird parenthesized-inline doc comment. I’ll link it when I get off the bus.

**Comment by hk144** [comment]
в разведке один оперативник может годами с человеком работать а вы там сидите ав разные стороны тянете какое доверие здесь построишь боссу передайте там привет а насчет работы можно поговорить  но только по существу а то я здесь тыкаюсь как слепой куда нажимать что делать вообщем пиши звони если предожить что будет.


Отправлено со смартфона Samsung Galaxy.
-------- Исходное сообщение --------От: Sean Larkin <notifications@github.com> Дата: 07.05.18  17:45  (GMT+03:00) Кому: webpack/webpack <webpack@noreply.github.com> Копия: Subscribed <subscribed@noreply.github.com> Тема: Re: [webpack/webpack] (WIP) Enable TypeScript strictNullChecks (#7037) 
@weswigham @sandersn @DanielRosenwasser after exploring this feature a bit, I'm wondering if there is a way currently to do non-null assertions via jsdocs. Currently we have a lot of places we ned rotell the compiler to trust us.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/webpack/webpack","title":"webpack/webpack","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/webpack/webpack"}},"updates":{"snippets":[{"icon":"PERSON","message":"@TheLarkInn in #7037: @weswigham @sandersn @danielrosenwasser after exploring this feature a bit, I'm wondering if there is a way currently to do non-null assertions via jsdocs. Currently we have a lot of places we ned rotell the compiler to trust us."}],"action":{"name":"View Pull Request","url":"https://github.com/webpack/webpack/pull/7037#issuecomment-387088136"}}}

**Comment by mohsen1** [comment]
We have a long way to go before enabling this

**Pull request closed without merging**
