### PR TITLE
Fix ProfilingPlugin for watch scenarios

### LINKED ISSUE #9114: ProfilingPlugin crashes with devserver and in watch mode
# Bug report

**What is the current behavior?**

When using ProfilingPlugin and run webpack in `--watch` mode or devserver, following error is thrown:

```
 98% after emitting(node:79437) UnhandledPromiseRejectionWarning: Error [ERR_INSPECTOR_NOT_CONNECTED]: Session is not connected
    at Session.post (inspector.js:75:13)
    at Promise (/Users/path/to/code/node_modules/webpack/lib/debug/ProfilingPlugin.js:54:25)
    at new Promise (<anonymous>)
    at Profiler.sendCommand (/Users/path/to/code/node_modules/webpack/lib/debug/ProfilingPlugin.js:53:11)
    at Profiler.stopProfiling (/Users/path/to/code/node_modules/webpack/lib/debug/ProfilingPlugin.js:76:15)
    at compiler.hooks.done.tapAsync (/Users/path/to/code/node_modules/webpack/lib/debug/ProfilingPlugin.js:209:21)
    at args (/Users/path/to/code/node_modules/webpack/lib/debug/ProfilingPlugin.js:394:11)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/path/to/code/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:18:1)
    at Watching._done (/Users/path/to/code/node_modules/webpack/lib/Watching.js:97:28)
    at compiler.emitRecords.err (/Users/path/to/code/node_modules/webpack/lib/Watching.js:72:19)
    at Compiler.emitRecords (/Users/path/to/code/node_modules/webpack/lib/Compiler.js:449:39)
    at compiler.emitAssets.err (/Users/path/to/code/node_modules/webpack/lib/Watching.js:53:20)
    at hooks.afterEmit.callAsync.err (/Users/path/to/code/node_modules/webpack/lib/Compiler.js:435:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/path/to/code/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at asyncLib.forEachLimit.err (/Users/path/to/code/node_modules/webpack/lib/Compiler.js:432:27)
    at /Users/path/to/code/node_modules/neo-async/async.js:2760:7
    at done (/Users/path/to/code/node_modules/neo-async/async.js:3450:9)
    at /Users/path/to/code/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:141:20)
(node:79437) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:79437) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

After this webpack does not crash completely, but no files are watched anymore. events.json file is produced, but I'm fairly sure it does not contain anything from the point when exception is thrown.

This makes it fairly difficult to debug performance issues in incremental builds.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. setup the plugin like in documentation
2. run webpack in watch mode
3. after initial build modify watched file -> error thrown

**What is the expected behavior?**

plugin should not crash

**Other relevant information:**
webpack version:  4.31.0
Node.js version: v10.15.0
Operating System: macOS 10.14.4
Additional tools: 

@pleunv seems to be experiencing the same: https://github.com/webpack/webpack/issues/6767#issuecomment-384713454

### PR DESCRIPTION
**Pull request by markjm**
Fixes #9114
By moving away from noStream mode, we get the same functionality (by pushing the fine "]" to make valid JSON) in non-watch scenario. In the watch scenario, we continue to keep the tracer running until the watch process ends. This will typically result in a near-complete JSON (missing a final "]"). Since streaming traces is so common, common stream inspectors (chrome://inspect) will fix up near-valid JSON for you.

**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Review by sokra — CHANGES_REQUESTED** [review]
CI says there is something slightly off with the stream:

```
  ● Profiling Plugin › should handle output path with folder creation

    Error [ERR_STREAM_PUSH_AFTER_EOF]: stream.push() after EOF



      at Tracer._pushString (node_modules/chrome-trace-event/dist/trace-event.js:101:14)
      at node_modules/chrome-trace-event/dist/trace-event.js:147:22
      at Tracer.end (node_modules/chrome-trace-event/dist/trace-event.js:118:37)
      at r (lib/debug/ProfilingPlugin.js:3912:24)
      at WriteStream.fsStream.on (lib/debug/ProfilingPlugin.js:3456:9)
      at node_modules/graceful-fs/graceful-fs.js:61:14
```

**Comment by markjm** [comment]
> CI says there is something slightly off with the stream:
> 
> ```
>   ● Profiling Plugin › should handle output path with folder creation
> 
>     Error [ERR_STREAM_PUSH_AFTER_EOF]: stream.push() after EOF
> 
> 
> 
>       at Tracer._pushString (node_modules/chrome-trace-event/dist/trace-event.js:101:14)
>       at node_modules/chrome-trace-event/dist/trace-event.js:147:22
>       at Tracer.end (node_modules/chrome-trace-event/dist/trace-event.js:118:37)
>       at r (lib/debug/ProfilingPlugin.js:3912:24)
>       at WriteStream.fsStream.on (lib/debug/ProfilingPlugin.js:3456:9)
>       at node_modules/graceful-fs/graceful-fs.js:61:14
> ```

I believe this some inconsistency with streams in older versions of node. Seems to work consistently on more recent versions of node. Instead of debugging this difference, perhaps we can just merge this into the webpack@6 branch and let the change roll out with that?

**Comment by sokra** [comment]
> I believe this some inconsistency with streams in older versions of node. Seems to work consistently on more recent versions of node. Instead of debugging this difference, perhaps we can just merge this into the webpack@6 branch and let the change roll out with that?

I would prefer to minimize the differences between webpack 5 and 6, so this seem to be solve-able in webpack 5 too. If not check node.js version and only enable it in compatible versions

**Comment by markjm** [comment]
@sokra fixed for all node versions with no version check

**Comment by sokra** [comment]
Awesome 👍

**Comment by vidal7** [comment]
Thank you!

**Pull request merged**
