### PR TITLE
chore: update jest

### PR DESCRIPTION
**Pull request by alexander-akait**
fixes https://github.com/webpack/webpack/pull/16813

Here:
1. Let's use minimum LTS Node.js version for basic/linting/unit testing, i.e. `16`, the end of life of `14` version is 2023-04-30 (so I don't have any point to use it, except integraiton testing), many tools have something like `"node": "^14.15.0 || ^16.10.0 || >=18.0.0"`, i.e. they don't support non LTS versions (so I think we should use only LTS for testing, except the latest node.js version, i.e. `19` right now), but it doesn't mean we don't support old node.js versions, they are still in our integration tests
2. Setup `snapshotFormat` for compatibility between jest snapshots when we use different versions of jest
3. Install `yarn upgrade jest@^27.5.0 jest-circus@27.5.0 jest-cli@27.5.0 jest-diff@27.5.0 jest-junit@13.0.0` for Node.js 10 and 12 and 17 (we need to use 18 node here, WIP on this)
4. Remove `--ignore-engines` where it is unnecessary
5. More CI for new Node.js versions
6. Use `16` version for linting purposes

### <samp>🤖 Generated by Copilot at 4f1ca68</samp>

Updated `jest` and other dependencies in `package.json` to address security and quality issues.

### <samp>🤖 Generated by Copilot at 4f1ca68</samp>

* Updated jest-related dependencies to fix vulnerabilities and improve testing ([link](https://github.com/webpack/webpack/pull/16947/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L69-R73))

### CODE REVIEW

**Review by snitin315 — APPROVED** [review]
Nice fix.

**Comment by snitin315** [comment]
Which PR should ew merge first? this or https://github.com/webpack/webpack/pull/16936? The other PR will need a rebase

**Comment by alexander-akait** [comment]
Will be great to merge - https://github.com/webpack/webpack/pull/16936 firstly, then I will do rebase and improve our CI

**Comment by TheLarkInn** [comment]
What test configuration changes on the repo need to be made before we merge this? I think we're ready to go here.

**Review by TheLarkInn — APPROVED** [review]

**Review by snitin315 — APPROVED** [review]

**Pull request merged**
