### PR TITLE
Also read __webpack_public_path__ in runtime

### PR DESCRIPTION
**Pull request by kebot**
Related issues:

https://github.com/webpack/webpack/issues/443

https://github.com/webpack/webpack/issues/842

### CODE REVIEW

**Comment by sokra** [comment]
I don't want this, because a bundle should be standalone by default without any reference to the environment.

You can do this explicit by adding `__webpack_public_path__ = window.__webpack_public_path__;` as extra entry point.

**Comment by sokra** [comment]
Do you have HMR enabled? This could affect the require function...

**Comment by jperasmus** [comment]
For others also struggling to get this to work, the problem for me was that `import` statements are hoisted to the top of the file, making the `__webpack_public_path__` free variable not available even if set at the top of your entry point.

I had to create a separate file (`public_path.js`) with the code to set the public path during runtime like:
```
__webpack_public_path__ = `${window.location.origin}${(window.location.pathname).replace('index.jsp', '')}`;
```

And then specify this new file in my webpack config's entry points:

```
webpackConfig.entry = {
  preload: ['./app/scripts/public_path', './app/scripts/preload'],
  main: ['./app/scripts/public_path', './app/scripts/main']
};
```

**Comment by Orange637** [comment]
@jperasmus thanks, it works

**Comment by bjornstar** [comment]
I wasted a whole day failing to configure `__webpack_public_path__` so I could use it in a cordova app. Thanks @jperasmus for your info, you saved my bacon.

**Comment by jperasmus** [comment]
Glad I could help 🍻

**Comment by sag1v** [comment]
@jperasmus how would you do it with `CommonsChunkPlugin` ? i mean how can i be sure its preloaded as an entry point?
this is what i have now:
```
  entry: {
    "vendor": path.resolve(__dirname, 'src/vendor'),
    "app": path.resolve(__dirname, 'src/index')
  },
```
can i use a preload here?

**Comment by jperasmus** [comment]
Hi @sag1v 

That should be fine because your vendor code is just a separate entry point.

```
entry: {
  "vendor": [ path.resolve(__dirname, 'src/public_path'), path.resolve(__dirname, 'src/vendor') ],
  "app": [ path.resolve(__dirname, 'src/public_path'), path.resolve(__dirname, 'src/index') ]
},
```

**Comment by sag1v** [comment]
@jperasmus yeah thats exactly what i've tried couple of minutes ago, though i dont see a change. maybe i'm doing it wrong or i am just expecting something that's it is not suppose to do.
basically what i want is to dynamicly set the `publicPath`  so my fonts will be reference correctly (i'm using `url-loader` which fallback to `file-loader` if limit exceeded).

**Comment by jperasmus** [comment]
And you do have the `src/public_path.js` file with content something like this:
```
__webpack_public_path__ = `${window.location.origin}${(window.location.pathname).replace('index.jsp', '')}`;
```

Maybe a good idea to console log `__webpack_public_path__` in that file to see what it sets itself as. This is very specific to one particular app I used it on, serving up a `index.jsp` page; yours might be different.

**Pull request closed without merging**
