### PR TITLE
Update dependencies for webpack v4

### PR DESCRIPTION
**Pull request by GChuf**
This makes sure that (still widely used) v4 stays up to date.

**What kind of change does this PR introduce?**

Dependency updates

**Did you add tests for your changes?**

no

**Does this PR introduce a breaking change?**

no

**What needs to be documented once your changes are merged?**

nothing

### CODE REVIEW

**Review by evilebottnawi — COMMENTED** [review]
Why? Just update your deps and lock file

**Comment by GChuf** [comment]
People dont have time to update every subdependency. It needs to be done for every project ...

The tests are failing right now. If you would like to merge this PR, I will fix it.
If you don't want to merge, i will not continue this PR.

**Comment by evilebottnawi** [comment]
> People dont have time to update every subdependency. It needs to be done for every project ...

Setup bot for this

**Comment by evilebottnawi** [comment]
No thanks. There's no benefit here.

**Comment by GChuf** [comment]
@evilebottnawi there is benefit. why do you think updating deps for v5 is a good idea, but a bad idea for v4?

**Comment by evilebottnawi** [comment]
This is no bad/good ideas, for v4 it just unnecessary

**Pull request closed without merging**
