### PR TITLE
readme bugfix

### PR DESCRIPTION
**Pull request by liuyuanyangscript**
**What kind of change does this PR introduce?**

Readme bugfix

**Did you add tests for your changes?**

Yes.

**If relevant, link to documentation update:**

https://github.com/webpack/webpack/issues/5156

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by abouthiroppy** [comment]
LGTM.

**Comment by liuyuanyangscript** [comment]
@jsf-clabot

I signed CLA today. Ready to merge~

**Comment by sokra** [comment]
Please rewrite your commit to include the correct email address. Github needs to assign the commit to your github accout. See jsf bot comment

**Comment by liuyuanyangscript** [comment]
OK@sokra

**Pull request closed without merging**
