### PR TITLE
upgrade acorn to 7

### PR DESCRIPTION
**Pull request by sokra**
**What kind of change does this PR introduce?**
deps

**Did you add tests for your changes?**
exisiting tests

**Does this PR introduce a breaking change?**
yes, AST change

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

**Comment by dasa** [comment]
Could this be back-ported to v4 for https://github.com/webpack/webpack/issues/10516#issuecomment-703587638?

**Comment by vankop** [comment]
@dasa no, only critical fixes for v4

**Comment by Songoo7** [comment]
How can I use this ?

**Comment by alexander-akait** [comment]
Update to webpack v5

**Pull request merged**
