### PR TITLE
Addition of documentation for CONTRIBUTING.md/Discussions

### PR DESCRIPTION
**Pull request by MagicPoulp**
**What kind of change does this PR introduce?**
**HERE:**
**added doc
see the end of
https://github.com/webpack/webpack/issues/6163**

**Did you add tests for your changes?**
not needed for doc

**If relevant, link to documentation update:**

**Summary**

added doc
see the end of
https://github.com/webpack/webpack/issues/6163

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by MagicPoulp** [comment]
I am curious to know: Why is it bad to have a fake email in the commit @fake.email.org?

**Comment by sokra** [comment]
We need to be able to assign an owner to each commit/LOC for legal reasons. The owner need to sign the CLA, so we can publish the code with the MIT license.

**Comment by MagicPoulp** [comment]
I fixed the email issue. And I used a valid github email.

Sorry I did not know I had a noreply github email.

**Comment by sokra** [comment]
Thanks

**Pull request merged**
