### PR TITLE
support destructuring assignment in import.meta

### PR DESCRIPTION
**Pull request by vankop**
other plugins?

### <samp>🤖 Generated by Copilot at 730dab9</samp>

This pull request improves the `ImportMetaPlugin` class to handle import.meta properties more accurately and efficiently, and adds tests for the new features and the existing behavior. It also warns users when they access import.meta directly, which is not supported by webpack.

### <samp>🤖 Generated by Copilot at 730dab9</samp>

*  Add helper functions for generating import.meta code ([link](https://github.com/webpack/webpack/pull/16996/files?diff=unified&w=0#diff-a265dcfd4104a4b8e394b2085074667c0e575e8cb3e55e476d85c5457137d7b2R78-R88))
*  Support destructuring assignment for import.meta properties ([link](https://github.com/webpack/webpack/pull/16996/files?diff=unified&w=0#diff-a265dcfd4104a4b8e394b2085074667c0e575e8cb3e55e476d85c5457137d7b2L87-R139), [link](https://github.com/webpack/webpack/pull/16996/files?diff=unified&w=0#diff-08f253d98887ffd5d963f1506dee0106dac095c0a8a36a3071dcf990ad5cb780L45-R57), [link](https://github.com/webpack/webpack/pull/16996/files?diff=unified&w=0#diff-ece069395dfb97f35640cbf04fe22351689a5c7fd6fda4055b0359ebf9413f11R1-R3))
*  Simplify import.meta expression handling by using helper functions ([link](https://github.com/webpack/webpack/pull/16996/files?diff=unified&w=0#diff-a265dcfd4104a4b8e394b2085074667c0e575e8cb3e55e476d85c5457137d7b2L123-R162), [link](https://github.com/webpack/webpack/pull/16996/files?diff=unified&w=0#diff-a265dcfd4104a4b8e394b2085074667c0e575e8cb3e55e476d85c5457137d7b2L143-L146), [link](https://github.com/webpack/webpack/pull/16996/files?diff=unified&w=0#diff-a265dcfd4104a4b8e394b2085074667c0e575e8cb3e55e476d85c5457137d7b2L157-R189), [link](https://github.com/webpack/webpack/pull/16996/files?diff=unified&w=0#diff-a265dcfd4104a4b8e394b2085074667c0e575e8cb3e55e476d85c5457137d7b2L171-R203))
*  Move `webpackVersion` variable to the top of `ImportMetaPlugin.js` ([link](https://github.com/webpack/webpack/pull/16996/files?diff=unified&w=0#diff-a265dcfd4104a4b8e394b2085074667c0e575e8cb3e55e476d85c5457137d7b2L143-L146))

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]
Let's fix prettier

**Comment by TheLarkInn** [comment]
Going to mark this as needs documentation @chenxsan, if we don't already have `import.meta` section I feel like a whole page dedicated to how webpack treats `import.meta` (perhaps Module Methods section) is important.

**Review by TheLarkInn — APPROVED** [review]
Great work! 🚀

**Comment by chenxsan** [comment]
> Going to mark this as needs documentation @chenxsan, if we don't already have `import.meta` section I feel like a whole page dedicated to how webpack treats `import.meta` (perhaps Module Methods section) is important.

Nah, we don't have a dedicate page for it. Currently `import.meta`s are listed under [module variables](https://webpack.js.org/api/module-variables/#importmetaurl) page. I'll see if we can group them into a section.

**Pull request merged**
