### PR TITLE
chore(test): add node 7, and 0.12 to travis

### PR DESCRIPTION
**Pull request by TheLarkInn**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] CI related changes

**What is the current behavior?** (You can also link to an open issue here)
Currently we are only testing against node 6 and 4. 

**What is the new behavior?**
Now that node 7 is current and we have agreed to support node 0.12 still, we should add those tests back onto travis. 

**Does this PR introduce a breaking change?**
- [x] No

* Impact: Low to None
* Migration path for existing applications: N/A
* Github Issue(s) this is regarding: (Core team meeting discussion).

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Okay, good idea. So for 0.12 we allow failures to happen, but do you know where we would see those failures? Because we would need some kind of warning when we're merging a PR that breaks with 0.12.

**Comment by TheLarkInn** [comment]
@SpaceK33z That makes sense, I'll take 0.12 out of optional. But leave 4 in there so that we can advise to update to node 6+. Thoughts?

**Comment by TheLarkInn** [comment]
@SpaceK33z there are a lot of cases where `const` is being used in our test cases. I'm moving it back to optional for now, and if we want to separate these tests (which I'm not sure the effort is worth it), we could enlist support.

**Comment by TheLarkInn** [comment]
@SpaceK33z if we do come across anyone having issues and trying to use node v0.12, then I think best solution would be for us or contributors to reference failed test history (at least for now).

**Pull request merged**
