### PR TITLE
Updated Webpack website link

### PR DESCRIPTION
**Pull request by montogeek**
**Please check if the PR fulfills these requirements**
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Other... Please describe:

Updated Webpack 2 website link

**What is the current behavior?** (You can also link to an open issue here)
Webpack website links are outdated for Webpack 2 release

**What is the new behavior?**
Update website links to new website, following https://github.com/webpack/webpack.js.org/issues/262

**Does this PR introduce a breaking change?**
- [x] No

### CODE REVIEW

**Comment by montogeek** [comment]
@sokra Sorry, What else need to be updated? :)

**Comment by TheLarkInn** [comment]
We have some decisions to make in terms of how we are going to handle the large amount of traffic from the existing site to the new one. tl;dr, SEO is very important, and 100% of the content has not been remediated from the old docs. We will have to investigate a little deeper how we approach handling that and a couple other variables involved.

**Comment by TheLarkInn** [comment]
Regardless thank you for putting this in.

**Comment by montogeek** [comment]
I understand how important it is :)

**Comment by SpaceK33z** [comment]
Closing since the readme has been completely overhauled for webpack v2, with also the correct links to webpack.js.org.

**Pull request closed without merging**
