### PR TITLE
Refactoring modulesSize method in Chank

### PR DESCRIPTION
**Pull request by Connormiha**
**What kind of change does this PR introduce?**
Refactoring

**Did you add tests for your changes?**
No

**Summary**
Just a little refactoring function for calculating sum

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by sokra** [comment]
What's the reason for doing so?

**Comment by Connormiha** [comment]
> What's the reason for doing so?

Simplify method. 1 line instead 5.
I think `reduce` is more suitable for calculating sum than classic loop.

**Comment by sokra** [comment]
ah ok. I switched added with removed lines in my brain and thought you changed reduce to for loop.

**Comment by sokra** [comment]
This was changed in the next branch.

**Pull request closed without merging**
