### PR TITLE
Move types to devDependencies

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
I ran in to an issue with `@types/eslint` over here: https://github.com/typed-ember/ember-cli-typescript/issues/1502

here is how I came to conclude the issue was with webpack:
```
❯ pnpm why @types/eslint

devDependencies:
@embroider/webpack 1.6.0
├─┬ @embroider/babel-loader-8 1.6.0
│ └─┬ babel-loader 8.2.5
│   └─┬ webpack 5.72.0 peer
│     └─┬ @types/eslint-scope 3.7.3
│       └── @types/eslint 8.4.2
├─┬ @embroider/hbs-loader 1.6.0
│ └─┬ webpack 5.72.0 peer
│   └─┬ @types/eslint-scope 3.7.3
│     └── @types/eslint 8.4.2
├─┬ babel-loader 8.2.5
│ └─┬ webpack 5.72.0 peer
│   └─┬ @types/eslint-scope 3.7.3
│     └── @types/eslint 8.4.2
├─┬ css-loader 5.2.7
│ └─┬ webpack 5.72.0 peer
│   └─┬ @types/eslint-scope 3.7.3
│     └── @types/eslint 8.4.2

(etc, for a few more pages)
```

This is problematic, because I'm using eslint@v7. _but_ I'm not even working with eslint plugins in the project where I discovered this, and my type checking was throwing errors due to mismatched types versions:
```
node_modules/.pnpm/@types+eslint@7.29.0/node_modules/@types/eslint/helpers.d.ts:1:6 - error TS2300: Duplicate identifier 'Prepend'.

1 type Prepend<Tuple extends any[], Addend> = ((_: Addend, ..._1: Tuple) => any) extends (..._: infer Result) => any
       ~~~~~~~

  node_modules/.pnpm/@types+eslint@8.4.2/node_modules/@types/eslint/helpers.d.ts:1:6
    1 type Prepend<Tuple extends any[], Addend> = ((_: Addend, ..._1: Tuple) => any) extends (..._: infer Result) => any
           ~~~~~~~
    'Prepend' was also declared here.
```

This is, of course, solved by pinning / overrides / resolutions-ing to `@types/eslint @ v7, but this is a bandaid on the real problem -- that webpack is bringing in dev dependencies when it should not be.

**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

### CODE REVIEW

**Comment by alexander-akait** [comment]
I don't think it is valid fix

**Comment by NullVoxPopuli** [comment]
@alexander-akait why's that?

**Comment by alexander-akait** [comment]
You should put `@types/eslint` in your deps

**Comment by NullVoxPopuli** [comment]
> You should put @types/eslint in your deps

Why? that makes no sense. I'm not developing with eslint in the project where I found this erro.

**Comment by alexander-akait** [comment]
But you use types from `@types/eslint`

**Comment by Semigradsky** [comment]
`eslint-scope` doesn't used in `webpack/types.d.ts`, so `@types/eslint-scope` can be moved to `devDependencies`.
But `estree` used in `webpack/types.d.ts`, so `@types/estree` should remain in `dependencies`.

**Comment by vankop** [comment]
both estree and eslint-scope are used ( estree as types inside webpack code base, eslint-scope https://github.com/webpack/webpack/blob/main/lib/optimize/ConcatenatedModule.js#L8 )

**Comment by Semigradsky** [comment]
`eslint-scope` used, but only as `devDependency`. There are no `eslint-scope` 's types exports.

**Comment by chriskrycho** [comment]
@Semigradsky is correct! As a rule of thumb, the only types which should be in `dependencies` are types which are re-exposed as part of *your* public API. Types which are part of your implementation details can be in `devDependencies`, as they are not exposed to end users.

**Comment by Semigradsky** [comment]
@NullVoxPopuli could you update your PR and sign CLA?

**Comment by Semigradsky** [comment]
@NullVoxPopuli hi! `@types/estree` still should be in `dependencies`.

**Comment by guidojw** [comment]
@NullVoxPopuli Hi, could you take a look at Semigradsky's note above so this can be merged in the future?

**Comment by NullVoxPopuli** [comment]
Updated

**Comment by guidojw** [comment]
Hi @sokra,
I see there's some merge activity again, can we get this merged?

**Comment by alexander-akait** [comment]
Fixed

**Pull request closed without merging**
