### PR TITLE
feat(travis): cache directory for yarn and npm

### PR DESCRIPTION
**Pull request by TheLarkInn**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Feature

**Does this PR introduce a breaking change?**
- [x] No

**Other information**:

Should improve travis speed.

### CODE REVIEW

**Comment by TheLarkInn** [comment]
Looks like first travis test flaked so I re ran the job.

**Comment by TheLarkInn** [comment]
@jdalton would you mind reviewing. It appears to be working, however I haven't benched marked anything.

**Comment by jdalton** [comment]
Ya, you'll see it kick in on subsequent commits. After a successful run it will cache. Then on future runs it will load the cache. You manage caches from the travis-ci UI too:

**Comment by TheLarkInn** [comment]
Thank you. Merging.

**Comment by MoOx** [comment]
I saw here https://gist.github.com/MrRio/5071b11a1d02bae30f70ab527c5f2529  that .nvm is cached & not .npm.
Also here https://github.com/javascriptair/site/blob/d026f037f47681df97e3e1a47dfa29081f4dd645/.travis.yml you can see .yarn-cache cached.
Not sure if it's a good idea but I am going to try to cache all this things :D

**Pull request merged**
