### PR TITLE
Revert "Wrap default entry property in array"

### PR DESCRIPTION
**Pull request by sokra**
Reverts webpack/webpack#6394

### CODE REVIEW

**Comment by sokra** [comment]
@TheLarkInn This is a breaking change and would also result in larger bundles, because an array adds an extra module to the bundle.

**Comment by sokra** [comment]
I guess we can find an alternative solution for this.. I. e. a waterfall hook to modify the entry values

**Comment by TheLarkInn** [comment]
Sounds good!

**Comment by shellscape** [comment]
A waterfall hook would be awesome. If it would be possible to update the 3.x branch with that as well, that'd be awesome.

**Pull request merged**
