### PR TITLE
fix: stats.hasWarnings() should respect ignoreWarnings

### PR DESCRIPTION
**Pull request by nanianlisao**
## Summary

Actually, I am not sure if this is a bug or if it was done intentionally. But I think `hasWarnings` in `stats` should respect `ignoreWarnings`。

 Especially in the compiler.hooks.done hooks, stats obtained is directly processed via hasWarnings to handle warnings.

### <samp>🤖 Generated by Copilot at 345939a</samp>

Refactor `Stats.hasWarnings` to use `Compilation.getWarnings`. This is part of a larger effort to optimize and enhance the stats output.

## Details

`stats.hasWarnings()` should respect `ignoreWarnings`

### <samp>🤖 Generated by Copilot at 345939a</samp>

*  Refactor warnings handling logic in `Compilation` class (0,10,10,1,F0L3R

### CODE REVIEW

**Comment by nanianlisao** [comment]
@alexander-akait 
Hi,
I've noticed that my pull request hasn't been reviewed yet. If you could find some time to review it, I'd really appreciate it.

Thanks a lot!

**Review by alexander-akait — COMMENTED** [review]
I am fine with it, but I am afraid it can be a breaking change, because some tools can rely on this behaviour... I think we need a small dicussion here @webpack/core-support @webpack/cli-team

**Comment by snitin315** [comment]
@alexander-akait Yeah, this could be a potential breaking change. I believe we should consider this change for webpack v6

**Comment by vankop** [comment]
I think this is valid, `ignoreWarnings` should be respected.

**Review by vankop — APPROVED** [review]

**Comment by alexander-akait** [comment]
@vankop I think we need a test cases to prevent regression in future

**Comment by alexander-akait** [comment]
Feel free to send it and we can merge it

**Comment by nanianlisao** [comment]
Great, could you please take a look again. @alexander-akait

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
