### PR TITLE
fix: isInstall

### PR DESCRIPTION
**Pull request by yinsang**
https://github.com/webpack/webpack/issues/11836

**What kind of change does this PR introduce?**
bugfix. Instead of using require('webpack-cli'), child_process is a better way.

**Did you add tests for your changes?**
No, but I had test in local environment fully.

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
no

### CODE REVIEW

**Review by evilebottnawi — CHANGES_REQUESTED** [review]
No, it reduce performance, running new process require a lot of memory and CPU

**Comment by yinsang** [comment]
> No, it decreases performance, running new process require a lot of memory and CPU

Agreed!,but an error is not expected. please fix it.

**Comment by yinsang** [comment]
like Error.captureStackTrace

**Comment by evilebottnawi** [comment]
@yinsang This error from `require`, what your expected?

**Comment by yinsang** [comment]
> @yinsang This error from `require`, what your expected?

expect no error but success after **webpack-cli** is installed.

**Comment by yinsang** [comment]
image

**Comment by evilebottnawi** [comment]
`react-babel-study` should have `webpack` and `webpack-cli` in peer deps + you need to install this on package level, also I think you have two version of webpack, because it should be hoist at top

**Pull request closed without merging**
