### PR TITLE
Fix link

### LINKED ISSUE #7384: 404 in Breaking Change about "-loader suffix"
# Bug report

**What is the current behavior?**
When getting this error:

> BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
> You need to specify 'babel-loader' instead of 'babel',
> see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed

The indicated url is broken (404).

**If the current behavior is a bug, please provide the steps to reproduce.**
Use a loader without using `-loader` in webpack configuration, so that the breaking change is displayed:

```
 module: {
      loaders: [
         {
            test: /\.jsx?$/,
            exclude: /node_modules/,
            loader: 'babel',
				
            query: {
                presets: ['es2015', 'react']
            }
         }
      ]
   }
```

The above error message with broken url will be displayed.

**What is the expected behavior?**
The specified url should be valid.

**Other relevant information:**
webpack version:  4.8.3
Node.js version: 8.9.4
Operating System: Win 10 (x64)

### PR DESCRIPTION
**Pull request by moondef**
Fixed #7384

### CODE REVIEW

**Comment by warpdesign** [comment]
@moondef That was faster than my connection took time to clone the webpack repo ;)

**Comment by sokra** [comment]
Please also sign the CLA

**Comment by moondef** [comment]
@sokra done

**Comment by sokra** [comment]
Thanks

**Pull request merged**
