### PR TITLE
fix prefetching with runtime public path

### LINKED ISSUE #7744: Prefetched chunks ignore __webpack_public_path__ value
# Bug report

**What is the current behavior?**

When marking a chunk with `/* webpackPrefetch: true */` the value of `__webpack_public_path__ ` is ignored and the value specified in `webpack.config.js` or the default is used instead. This is not the case for "normal" imports as well as `/* webpackPreload: true */` imports, only prefetched imports are affected.

**If the current behavior is a bug, please provide the steps to reproduce.**

I made the existing test case for prefetch/preload stricter in my fork [here](https://github.com/webpack/webpack/compare/master...no23reason:features/prefetch-public-path). All the changed assertions pass, only the one on [line 27](https://github.com/webpack/webpack/compare/master...no23reason:features/prefetch-public-path#diff-5c81e3d588a59ab32cb1db13062686e1R27) fails (it is the one for prefetched import).

Repro steps:
```
git clone https://github.com/no23reason/webpack.git
cd webpack
git checkout features/prefetch-public-path
yarn
yarn jest ConfigTestCases
```

**What is the expected behavior?**

I believe the prefetched chunks should respect the `__webpack_public_path__ ` value, just like preloaded ones do.

**Other relevant information:**
webpack version:  4.16.1
Node.js version: 8.11.3
Operating System: macOS High Sierra 10.13.6
Additional tools: N/A

### PR DESCRIPTION
**Pull request by sokra**
delay prefetching until all initial code is evaluated

fixes #7744

**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
prefetch will start after the initial code is evaluated

### CODE REVIEW

**Comment by sokra** [comment]
@no23reason could you sign the CLA? I included your commit in this PR.

**Comment by darkowic** [comment]
ooo I was about to look into the issue! Thank you @sokra !

**Comment by no23reason** [comment]
Thank you so much for taking the effort to fix this, @sokra :) I signed the CLA just now

**Comment by sokra** [comment]
Thanks

**Pull request merged**
