### PR TITLE
upgrade terser-webpack-plugin

### PR DESCRIPTION
**Pull request by sokra**
**What kind of change does this PR introduce?**
deps

**Did you add tests for your changes?**
existing tests

**Does this PR introduce a breaking change?**
yes

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Today i will do new release and we can remove https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L448 (all options) because terser setup them from webpack options https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/src/index.js#L198

**Comment by sokra** [comment]
> Today i will do new release and we can remove https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L448 (all options) because terser setup them from webpack options https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/src/index.js#L198

:+1: great, send a PR

**Comment by webmaster128** [comment]
Any plans to do the same change [for webpack 4](https://github.com/webpack/webpack/blob/master/package.json#L27)? There is a security warning in `serialize-javascript "^1.7.0"`, a dependency of `terser-webpack-plugin@^1.4.1`.

**Comment by webmaster128** [comment]
Sorry, false alarm. There is https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v1.4.2 that upgrades serialize-javascript

**Pull request merged**
