### PR TITLE
[WIP] chore(readme): add open-collective badges

### PR DESCRIPTION
**Pull request by TheLarkInn**
* add o.c. badges
* remove old badges

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Later in the readme there is also a "Sponsor" part. Maybe remove that, since that is quite confusing now?

**Comment by TheLarkInn** [comment]
Yes nice catch sounds good

**Comment by TheLarkInn** [comment]
Updated

**Comment by sokra** [comment]
I think it's better to move this part behind the introduction.

**Comment by sokra** [comment]
The main visitor want to know what webpack is and not primary how to sponsor it.

**Comment by TheLarkInn** [comment]
sounds good will do

**Comment by TheLarkInn** [comment]
Closing in favor of #3152

**Pull request closed without merging**
