### PR TITLE
Some minor fixes and comments

### PR DESCRIPTION
**Pull request by sokra**
**What kind of change does this PR introduce?**
CI

**Did you add tests for your changes?**
CI

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

**Comment by sokra** [comment]
cc @xtuc

**Comment by xtuc** [comment]
@sendilkumarn mentionned that we could also test the tagged wasm one, would it make sense here? Some other tests are failing otherwise.

**Comment by sokra** [comment]
I'm acutally interesting in why the tests fail in node.js 11...

**Comment by sokra** [comment]
This seem to be a non-determinism in the chunk sorting part

**Comment by sokra** [comment]
> Test Suites: 1 failed, 3 skipped, 12 passed, 13 of 16 total Tests: 6 failed, 5 skipped, 1073 passed, 1084 total Snapshots: 6 failed, 81 passed, 87 total Time: 84.239s

**Pull request merged**
