### PR TITLE
Replace `eslint-plugin-node` with maintained up to date community fork `eslint-plugin-n`

### PR DESCRIPTION
**Pull request by voxpelli**
`eslint-plugin-n` is a community maintained fork of `eslint-plugin-node`: https://github.com/eslint-community/eslint-plugin-n

It ensures that an important module like `eslint-plugin-node` is kept up to date, with both ESLint 8.x and with Node.js itself.

Its what we switched to in `eslint-config-standard` when we updated it to ESLint 8.x: https://github.com/standard/eslint-config-standard/pull/193

Similar PR: https://github.com/electron/electron/pull/38874

Full disclosure: I'm part of the [ESLint Community Core Team](https://eslint.org/blog/2023/03/announcing-eslint-community-org/#about-the-organization) as well as a co-maintainer of StandardJS.

### <samp>🤖 Generated by Copilot at 015918a</samp>

Renamed the `node` ESLint plugin to `n` to avoid confusion with Node.js and updated all the files that use it. This includes changing the dependency in `package.json`, the plugin name and configuration in `.eslintrc.js`, and the rule overrides in various `webpack.config.js` files and source files.

### <samp>🤖 Generated by Copilot at 015918a</samp>

*  Rename the `eslint-plugin-node` dependency and plugin to `eslint-plugin-n` to avoid confusion with the Node.js runtime ([link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5L3-R6), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5L29-R29), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L60-R60))
*  Replace all occurrences of the `node` plugin prefix with the `n` plugin prefix in the `.eslintrc.js` file and in various files that disable specific rules from the plugin ([link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-a20efb2d907f3490f50c3a395eedb3ab99c6cbb0344bace96ebd867adfbdfa3fL48-R52), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-9206962f55a69b69a39e73a803e2be04b10d454f270e35b482f3f70a74f472a6L1180-R1182), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-9206962f55a69b69a39e73a803e2be04b10d454f270e35b482f3f70a74f472a6L1195-R1197), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-c0078e4713a0e7a24dbc56d6dfda3cf139376325fc65ea70a8389d4d30b27f04L471-R471), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-465062dae5d05d746b72079561dd77bf44580bd09a77aac8868291b5cae99402L34-R34), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-f3d6bdc930b6dea5fec264b1f9135d67954a5008225f134c23b2cd5ad92814d2L117-R119), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-f3d6bdc930b6dea5fec264b1f9135d67954a5008225f134c23b2cd5ad92814d2L148-R150), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-f3d6bdc930b6dea5fec264b1f9135d67954a5008225f134c23b2cd5ad92814d2L160-R162), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-f3d6bdc930b6dea5fec264b1f9135d67954a5008225f134c23b2cd5ad92814d2L170-R172), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-f3d6bdc930b6dea5fec264b1f9135d67954a5008225f134c23b2cd5ad92814d2L188-R197), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-f3d6bdc930b6dea5fec264b1f9135d67954a5008225f134c23b2cd5ad92814d2L203-R205), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-50804bc6488bd0f817ac38f9374557649c39bf1843387c906d04e1ad99e58bfcL105-R115), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-f8f44a54087edd38ebe05a1f4d546b61a34ee8a826964c86f6d13367703b00b6L30-R30), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-f8f44a54087edd38ebe05a1f4d546b61a34ee8a826964c86f6d13367703b00b6L72-R72), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-c79eac69ce385b77ba09184cb6836d908b8554e35ce1daa9f980367e5e4bd4c4L1-R1), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-ce647ca69556b4e43e6e2d737262f60a34c65b12b936e7dd454306e5e2e78a9aL1-R1), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-d4033648747df571ca3eb6e04bb7cd868b47917bec9a5ae6bd603b6a6eda5524L1-R1), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-111c814c28eb56196ccd26eb099850fe66eeece58f74a2a06d1f9f8875f30b9cL1-R1), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-bfd02063c0fe46836fc9384e639703d12d5278888a083ca4489b4892255f03fdL1-R1), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-34d825b06b97ebfe66ec07477392db388a3abbe9d96f2f1bcbde097023558a65L10-R10), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-ff189398a52c9f203ce4d3a4136a9fc1a317580a77fe7610c1cc253eaa127cb9L10-R10), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-e2effc8595c9cf464b7f22329a6078ab38ba9b7c415d6c6d38d410bcb334a4f3L7-R7), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-72b03658501817c63dd10b5cbdbdc6490d06818211f9d37f285b276a6dd53902L7-R7), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-f9f70bb4c4a8cce61f2ce1d53b6e0a1d31549f22bc17d2a6826cf2856775628eL10-R10), [link](https://github.com/webpack/webpack/pull/17411/files?diff=unified&w=0#diff-5c4a4d4074159b7c32f216a477777cbccae458044b1d3380e9398f60ed1e5692L29-R29))

### CODE REVIEW

**Review by snitin315 — CHANGES_REQUESTED** [review]
@voxpelli Thanks for the PR and sorry for the delayed review, can you please rebase the PR and fix conflicts?

**Comment by voxpelli** [comment]
> @voxpelli Thanks for the PR and sorry for the delayed review, can you please rebase the PR and fix conflicts?

Done, was only the `yarn.lock` that was conflicting :)

**Comment by voxpelli** [comment]
@snitin315 Updated the PR and fixed deduplication as well 👍

**Comment by alexander-akait** [comment]
@voxpelli Sorry for delay, can you rebase?

**Pull request closed without merging**
