### PR TITLE
Remove duplicate import

### PR DESCRIPTION
**Pull request by hodovani**
**What kind of change does this PR introduce?**

Refactoring.

**Did you add tests for your changes?**

No need in a new test.

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

Nothing

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Review by snitin315 — APPROVED** [review]

**Comment by alexander-akait** [comment]
Please accept CLA

**Review by anshumanv — APPROVED** [review]

**Comment by hodovani** [comment]
@alexander-akait sorry about that. Could you please help. Where can I  find a link to the form where I can accept CLA?

**Comment by sokra** [comment]
> Where can I find a link to the form where I can accept CLA?

https://cla.js.foundation/webpack/webpack?pullRequest=12289

**Comment by hodovani** [comment]
@sokra thanks, done :)

**Comment by sokra** [comment]
Thanks

**Pull request merged**
