### PR TITLE
Add defensive module check in createFooter

### PR DESCRIPTION
**Pull request by s-panferov**
Please see https://github.com/webpack/webpack/issues/954#issuecomment-139287730

### CODE REVIEW

**Comment by sokra** [comment]
Could you please add a testcase?

**Comment by s-panferov** [comment]
@sokra ok, sure

**Comment by use-strict** [comment]
@s-panferov , any updates/status on this? I'm getting the same error with the latest webpack

**Comment by sokra** [comment]
Not needed

**Pull request closed without merging**
