### PR TITLE
Load modules recursively

### LINKED ISSUE #4959: loaderContext.loadModule does not load modules recursively
**Do you want to request a *feature* or report a *bug*?**

I would like to request a feature, that enables `loaderContext.loadModule` to optionally load modules recursively.

**What is the current behavior?**

When loading a module using `loaderContext.loadModule`, modules are not loaded recursively.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

While implementing [ts-css-loader](https://github.com/MortenHoustonLudvigsen/ts-css-loader), I had trouble loading css modules using `loaderContext.loadModule` for modules loaded by `css-loader`. The error I got was:
```
Error: Cannot find module "../../../../node_modules/css-loader/lib/css-base.js"
```

I turns out that I could solve the problem by writing my own version of `loaderContext.loadModule`, copied from `webpack/lib/dependencies/LoaderPlugin.js`, that loads modules recursively.

I did this by changing the `recursive` parameter from `false` to `true` in the call to `compilation.addModuleDependencies`.

`loaderContext.loadModule`:
```javascript
...
compilation.addModuleDependencies(module, [
	[dep]
], true, "lm", false, (err) => {
...
```

My version of `loadModule`:
```javascript
...
compilation.addModuleDependencies(module, [
	[dep]
], true, "lm", true, (err) => {
...
```

This has solved the problem for now, but it would be much better to use the "official" version of `loadModule`.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

### PR DESCRIPTION
**Pull request by buoyantair**
**What kind of change does this PR introduce?**
Enhancement

**Did you add tests for your changes?**
No

**If relevant, link to documentation update:**
N / A

**Summary**
Attempts to fix #4959 

**Does this PR introduce a breaking change?**
No

**Other information**
N / A

### CODE REVIEW

**Comment by dhruvdutt** [comment]
@buoyantair Can I help adding tests?

**Comment by buoyantair** [comment]
@dhruvdutt Hey, yes please, I didn't get time to work on this and the test suite looked daunting to me :joy:

**Comment by TheLarkInn** [comment]
Let me know how we can help with adding tests. We also have a README.md in the test folder for help

**Comment by buoyantair** [comment]
But how do I know if modules are loading recursively or not? and what does require.include do? (from what I looked up, require.include basically loads a module but doesn't run it..)

**Pull request closed without merging**
