### PR TITLE
fix bail not work bug

### PR DESCRIPTION
**Pull request by AMDvsTMD**
```js
// if we have an error mark module as failed and exit
if (err) {
  this.markModuleAsErrored(err); 
  this._initBuildHash(compilation); 
  return callback();
}
```

should return callback to be return callback(err) then the bail can work

**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**

yes
**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**

### CODE REVIEW

**Comment by shawnatxapp** [comment]
I wanted to find some clarity here:

If jiangliuer does not have a GitHub account how did they contribute any code to this PR?
Is there anything I can do to push the license check forward?

**Comment by sokra** [comment]
> If jiangliuer does not have a GitHub account how did they contribute any code to this PR?
> Is there anything I can do to push the license check forward?

You can put any name and email in git commits. This issue often happen when git configuration is incorrect or email has not been added to github.

**Comment by sokra** [comment]
Closing this as it has been already fixed in webpack 5.

**Comment by benpolinsky** [comment]
Sorry to comment on a closed issue, but how is this a solution? Is there any way to bail on error in webpack 4?

**Pull request closed without merging**
