### PR TITLE
ES6 refactoring in Parser

### PR DESCRIPTION
**Pull request by smelukov**
**What kind of change does this PR introduce?**

Refactoring of Webpack Core

**Did you add tests for your changes?**

No, all current tests still pass

**Summary**

More ES6 code in Webpack Core (`Parser`)

Inspired #4099

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by smelukov** [comment]
God, nooooooo..... ))))

**Comment by sokra** [comment]
see also https://github.com/webpack/webpack/pull/4428

cc @timse

**Comment by sokra** [comment]
awesome rebase and merge with other PR...

**Comment by sokra** [comment]
Thanks

**Comment by smelukov** [comment]
@sokra oh, thanks! I wanted to make some additional tests for the parser
But ok, will make it in some next PR ;)

**Pull request merged**
