### PR TITLE
add a quiet option to HotModuleReplacementPlugin to make it quieter

### PR DESCRIPTION
**Pull request by jlongster**
What do you think about this? I'm using HMR as basically an "eval" server so I'm always looking at the console to see the result of my current eval expression, and it's very verbose right now. This is a simple option that makes it quieter.

### CODE REVIEW

**Comment by jlongster** [comment]
Any word on this? I don't understand the test failure

**Comment by sokra** [comment]
> I don't understand the test failure

The watching test seem to timeout sometimes on CI. Not a real issue... I disabled them now...

---

Regarding the PR: I'm not sure if we should add `quiet` to the `module.hot` API. I think it's wrong here. Logging is part of the HMR management code (`webpack/hot/...`) and not of the HMR API (runtime in `lib/HotModuleReplacementPlugin`).

But not sure how to add parameters to the HMR management code. We could use query parameter (`webpack/hot/dev-server?quiet`) or defines (`new DefinePlugin({ HMR_VERBOSITY: 0 })`).

**Comment by gaearon** [comment]
I'd go with a query parameter.

**Comment by victorwpbastos** [comment]
+1

**Comment by jantimon** [comment]
+1

**Comment by victorwpbastos** [comment]
Any progress on this?

**Comment by jantimon** [comment]
The https://github.com/glenjamin/webpack-hot-middleware allows yo to do that.

**Comment by TheLarkInn** [comment]
Following up from oldest to newest PR's. @jlongster were you wanting to try to implement the query param approach? Feel free to sync master (you may find a crap ton of changes), or just close this and pop a new branch up. We can help offer any API support if needed.

**Pull request closed without merging**
