### PR TITLE
order runtime chunks correctly when they depend on each other

### LINKED ISSUE #11677: __webpack_require__.u returns a undefined hash for webworker scenario
# Bug report

**What is the current behavior?**
It outputs undefine as the hash

```js
/******/ 	/* webpack/runtime/get javascript chunk filename */
/******/ 	(() => {
/******/ 		// This function allow to reference async chunks
/******/ 		__webpack_require__.u = (chunkId) => {
/******/ 			// return url for filenames based on template
/******/ 			return "" + chunkId + "." + undefined + ".js";
/******/ 		};
/******/ 	})();
```
if I change to use `[name].[hash].js` as the `output.filename`, it works

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
`git clone https://github.com/wood1986/webpack-v5-webworker-bug`
`yarn start`
open dist/index.<hash>.js

it should be a hash not "undefined"

**Other relevant information:**
webpack version:  5.1.0
Node.js version: 14.13.0
Operating System: 10.15.7
Additional tools:

### PR DESCRIPTION
**Pull request by sokra**
fixes #11677

**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

**Comment by jraoult** [comment]
Just checking that this has been indeed released in v5.18.0 ? I'm still seeing the same issue when using `filename: "[name].[contenthash].js"`

**Comment by alexander-akait** [comment]
Double check installed version

**Comment by jraoult** [comment]
I doubled check and I'm indeed running 5.18. I dug a little here are my findings:

- in development mode, it works well even with `chunkIds: "deterministic"`
- in production mode, it works if I set `chunkIds: "named"`
- using `fullhash` in the filename always works

**Comment by alexander-akait** [comment]
If you still have the problem, please open the new issue with reproducible test repo

**Comment by rubenlg** [comment]
@jraoult did you open a separate iseue? I also reproduce the bug, and I want to keep an eye on it.

**Comment by jraoult** [comment]
@rubenlg I didn't. I ended up using fullhash instead and called it a day. Feel free to go ahead, I didn't have time back then to create a proper reduction etc.

**Comment by alexander-akait** [comment]
@rubenlg What is version you are use? Maybe you can create reproducible test repo?

**Comment by rubenlg** [comment]
@alexander-akait I'm using `5.20.1`. I have two separate bundles for two separate pages each one with its own web worker. When I build in development, one of the workers gets referenced with an `undefined` hash, and when I build for production, the other one gets that treatment. By using `fullhash`, the problem goes away in both dev and prod, and `fullhash` is good enough for my use case.

I'll try to create a minimal repro, to verify that my description above is sufficient to reproduce the bug, and file it separately if I succeed.

**Comment by alexander-akait** [comment]
@rubenlg thanks, feel free to open issue with reproducible test repo :+1:

**Pull request merged**
