### PR TITLE
fix: add return value to `subtractRuntime` fn

### PR DESCRIPTION
**Pull request by hai-x**
**What kind of change does this PR introduce?**
fixes `subtractRuntime` returns `undefined` when params `a` is `Set<runtime~a, runtime~b,runtime~c>` and params `b` is `runtime~a` but it is expected to return `Set<runtime~b,runtime~c>`

**Did you add tests for your changes?**
No

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
No

### CODE REVIEW

**Review by alexander-akait — CHANGES_REQUESTED** [review]
Can you add a test case?

**Comment by hai-x** [comment]
Sorry for delay.

Try adding a test case, but can't find a specific case that can hit this logic (`a` is SortableSet, `b` is string).

But I try to use `webpack-dev-server` to test HotModuleReplacementPlugin locally.

When one chunk that was before in three runtime is removing  from two runtimes, `removedFromRuntime` should be two removed runtime instead of `undefined`.

image

**Comment by alexander-akait** [comment]
@hai-x hm, can you provide manual steps to reproducible it I will think how we can test it, thank you and sorry for delay

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Thank you

**Pull request merged**
