### PR TITLE
Optimize numberHash.js

### PR DESCRIPTION
**Pull request by alexkuz**
Remove inner cycles from hashing algorithm

### <samp>🤖 Generated by Copilot at f952351</samp>

Optimize `numberHash` function in `lib/util/numberHash.js` by replacing loops with assignments and simplifying hash calculation. Assume fixed constants and add comments.

### <samp>🤖 Generated by Copilot at f952351</samp>

* Optimize the `numberHash` function to generate deterministic hash values for strings faster and more clearly ([link](https://github.com/webpack/webpack/pull/17074/files?diff=unified&w=0#diff-090914f1f98fe81b6aea1dbd55d78274087c8a7a2c5ae6d8cd9788c227a91e88L71-R96))

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Looks good, just interesting how it is faster, maybe you can do small benchmark?

**Comment by alexkuz** [comment]
@alexander-akait for a short string (1M iterations):
image

for a very long string (10 iterations):
image

**Review by alexander-akait — APPROVED** [review]

**Comment by TheLarkInn** [comment]
This seems like a significant improvement.

**Comment by TheLarkInn** [comment]
@alexkuz I'm going to promote this to "Ready for review", I'm interested to see if this modifies our test snapshot hashes.

**Comment by TheLarkInn** [comment]
Oh it did not!

**Review by TheLarkInn — APPROVED** [review]
Thank you for the contribution. 🙏

**Pull request merged**
