### PR TITLE
Allow files which require the same modules to be given the same instance of those modules

### PR DESCRIPTION
**Pull request by mdcone**
This fix is related to Issue #1332 . I have seen different behaviors between nodejs and webpack's module loaders as well as at least other person, the author of #1332 where it is impossible to share the same module instances.

This change allows for the reuse of modules that have been found to be duplicates by pulling out the module.exports of the first seen instance of the module and setting the duplicate's exports to point to it instead of re-executing the module.

### CODE REVIEW

**Comment by davedx** [comment]
We're seeing the same issue. Seems like a pretty fundamental part of how module loading should work. Is there anything I can do to help get this merged?

**Comment by mdcone** [comment]
Sorry been super distracted this past week. I know that the CI build didn't like something about my changes so I'll go look and see what changes I need to make to the tests. Then I would assume it can be merged it?

**Comment by sokra** [comment]
It's wrong. The current behavior is correct. It behaves exactly as node.js. If you are in doubt try to write a test case that proves that the behavior is wrong.

**Comment by mdcone** [comment]
After more digging I figured out what was going on. We are using the ts-loader across multiple repositories. Requires across repositories will cause the ts-loader to re-run for that file, and because each of our repositories is self-contained, it has it's own copy of ts-loader. What I have found is that if the ts-loader is at the root of the project and not in each sub-repo, webpack behaves normally. If not, webpack will keep re-invoking the loader which causes duplicates in the code. 

@sokra , sorry for being too simple with the initial approach, but it does seem like an issue. Now that there is a work around it's not huge, but it should at least be documented somewhere as a gotcha. Do you think that this issue is in the general loader functionality or in the specific loader I am using?

**Comment by smikhalevski** [comment]
I stumbled on this behavior too. After using RequireJS it was a bit confusing so I created a small plugin that forces `require` to return same instance of module regardless the place where import occurs: https://github.com/smikhalevski/single-module-instance-webpack-plugin

@mdcone, I hope this can help you.

**Comment by mdcone** [comment]
@smikhalevski , worked great! Thank you very much.

**Comment by flyon** [comment]
still an issue for me  trying to export a singleton instance, but smikhalevski's module works great!

**Comment by sokra** [comment]
This fixed anyway in webpack 2 as here loaders resolve always relative to configuration file if configured there.

**Comment by Aghassi** [comment]
@sokra Can you expand a little on what you mean by "this is fixed in Webpack 2"? What kind of config changes do you have to make to handle singletons until you have moved your codebase away from them?

**Comment by dougludlow** [comment]
I'm running into this in webpack 2 using jquery.  More than one instance of jquery is Imported and so certain jquery plugins aren't working. I'll have to give the single module instance plugin a try.

**Pull request closed without merging**
